// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: op-catalog/v1/datastore/chain_metadata.proto

package datastore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainMetadataKeyFilter struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Domain        *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Environment   *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	ChainSelector *wrapperspb.UInt64Value `protobuf:"bytes,3,opt,name=chain_selector,json=chainSelector,proto3" json:"chain_selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainMetadataKeyFilter) Reset() {
	*x = ChainMetadataKeyFilter{}
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadataKeyFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadataKeyFilter) ProtoMessage() {}

func (x *ChainMetadataKeyFilter) ProtoReflect() protoreflect.Message {
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadataKeyFilter.ProtoReflect.Descriptor instead.
func (*ChainMetadataKeyFilter) Descriptor() ([]byte, []int) {
	return file_op_catalog_v1_datastore_chain_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ChainMetadataKeyFilter) GetDomain() *wrapperspb.StringValue {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *ChainMetadataKeyFilter) GetEnvironment() *wrapperspb.StringValue {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ChainMetadataKeyFilter) GetChainSelector() *wrapperspb.UInt64Value {
	if x != nil {
		return x.ChainSelector
	}
	return nil
}

type ChainMetadataFindRequest struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	KeyFilter         *ChainMetadataKeyFilter `protobuf:"bytes,1,opt,name=key_filter,json=keyFilter,proto3" json:"key_filter,omitempty"`
	IgnoreTransaction bool                    `protobuf:"varint,2,opt,name=ignore_transaction,json=ignoreTransaction,proto3" json:"ignore_transaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChainMetadataFindRequest) Reset() {
	*x = ChainMetadataFindRequest{}
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadataFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadataFindRequest) ProtoMessage() {}

func (x *ChainMetadataFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadataFindRequest.ProtoReflect.Descriptor instead.
func (*ChainMetadataFindRequest) Descriptor() ([]byte, []int) {
	return file_op_catalog_v1_datastore_chain_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ChainMetadataFindRequest) GetKeyFilter() *ChainMetadataKeyFilter {
	if x != nil {
		return x.KeyFilter
	}
	return nil
}

func (x *ChainMetadataFindRequest) GetIgnoreTransaction() bool {
	if x != nil {
		return x.IgnoreTransaction
	}
	return false
}

type ChainMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	ChainSelector uint64                 `protobuf:"varint,3,opt,name=chain_selector,json=chainSelector,proto3" json:"chain_selector,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RowVersion    int32                  `protobuf:"varint,5,opt,name=row_version,json=rowVersion,proto3" json:"row_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainMetadata) Reset() {
	*x = ChainMetadata{}
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadata) ProtoMessage() {}

func (x *ChainMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadata.ProtoReflect.Descriptor instead.
func (*ChainMetadata) Descriptor() ([]byte, []int) {
	return file_op_catalog_v1_datastore_chain_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *ChainMetadata) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ChainMetadata) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ChainMetadata) GetChainSelector() uint64 {
	if x != nil {
		return x.ChainSelector
	}
	return 0
}

func (x *ChainMetadata) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *ChainMetadata) GetRowVersion() int32 {
	if x != nil {
		return x.RowVersion
	}
	return 0
}

type ChainMetadataFindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	References    []*ChainMetadata       `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainMetadataFindResponse) Reset() {
	*x = ChainMetadataFindResponse{}
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadataFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadataFindResponse) ProtoMessage() {}

func (x *ChainMetadataFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadataFindResponse.ProtoReflect.Descriptor instead.
func (*ChainMetadataFindResponse) Descriptor() ([]byte, []int) {
	return file_op_catalog_v1_datastore_chain_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *ChainMetadataFindResponse) GetReferences() []*ChainMetadata {
	if x != nil {
		return x.References
	}
	return nil
}

type ChainMetadataEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ChainMetadata         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Semantics     EditSemantics          `protobuf:"varint,2,opt,name=semantics,proto3,enum=api.datastore.v1.EditSemantics" json:"semantics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainMetadataEditRequest) Reset() {
	*x = ChainMetadataEditRequest{}
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadataEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadataEditRequest) ProtoMessage() {}

func (x *ChainMetadataEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadataEditRequest.ProtoReflect.Descriptor instead.
func (*ChainMetadataEditRequest) Descriptor() ([]byte, []int) {
	return file_op_catalog_v1_datastore_chain_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *ChainMetadataEditRequest) GetRecord() *ChainMetadata {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ChainMetadataEditRequest) GetSemantics() EditSemantics {
	if x != nil {
		return x.Semantics
	}
	return EditSemantics_SEMANTICS_INSERT
}

type ChainMetadataEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ChainMetadata         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainMetadataEditResponse) Reset() {
	*x = ChainMetadataEditResponse{}
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadataEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadataEditResponse) ProtoMessage() {}

func (x *ChainMetadataEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadataEditResponse.ProtoReflect.Descriptor instead.
func (*ChainMetadataEditResponse) Descriptor() ([]byte, []int) {
	return file_op_catalog_v1_datastore_chain_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *ChainMetadataEditResponse) GetRecord() *ChainMetadata {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_op_catalog_v1_datastore_chain_metadata_proto protoreflect.FileDescriptor

const file_op_catalog_v1_datastore_chain_metadata_proto_rawDesc = "" +
	"\n" +
	",op-catalog/v1/datastore/chain_metadata.proto\x12\x10api.datastore.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a$op-catalog/v1/datastore/common.proto\"\xd3\x01\n" +
	"\x16ChainMetadataKeyFilter\x124\n" +
	"\x06domain\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x06domain\x12>\n" +
	"\venvironment\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\venvironment\x12C\n" +
	"\x0echain_selector\x18\x03 \x01(\v2\x1c.google.protobuf.UInt64ValueR\rchainSelector\"\x92\x01\n" +
	"\x18ChainMetadataFindRequest\x12G\n" +
	"\n" +
	"key_filter\x18\x01 \x01(\v2(.api.datastore.v1.ChainMetadataKeyFilterR\tkeyFilter\x12-\n" +
	"\x12ignore_transaction\x18\x02 \x01(\bR\x11ignoreTransaction\"\xad\x01\n" +
	"\rChainMetadata\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12%\n" +
	"\x0echain_selector\x18\x03 \x01(\x04R\rchainSelector\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x1f\n" +
	"\vrow_version\x18\x05 \x01(\x05R\n" +
	"rowVersion\"\\\n" +
	"\x19ChainMetadataFindResponse\x12?\n" +
	"\n" +
	"references\x18\x01 \x03(\v2\x1f.api.datastore.v1.ChainMetadataR\n" +
	"references\"\x92\x01\n" +
	"\x18ChainMetadataEditRequest\x127\n" +
	"\x06record\x18\x01 \x01(\v2\x1f.api.datastore.v1.ChainMetadataR\x06record\x12=\n" +
	"\tsemantics\x18\x02 \x01(\x0e2\x1f.api.datastore.v1.EditSemanticsR\tsemantics\"T\n" +
	"\x19ChainMetadataEditResponse\x127\n" +
	"\x06record\x18\x01 \x01(\v2\x1f.api.datastore.v1.ChainMetadataR\x06recordBFZDgithub.com/smartcontractkit/chainlink-protos/op-catalog/v1/datastoreb\x06proto3"

var (
	file_op_catalog_v1_datastore_chain_metadata_proto_rawDescOnce sync.Once
	file_op_catalog_v1_datastore_chain_metadata_proto_rawDescData []byte
)

func file_op_catalog_v1_datastore_chain_metadata_proto_rawDescGZIP() []byte {
	file_op_catalog_v1_datastore_chain_metadata_proto_rawDescOnce.Do(func() {
		file_op_catalog_v1_datastore_chain_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_op_catalog_v1_datastore_chain_metadata_proto_rawDesc), len(file_op_catalog_v1_datastore_chain_metadata_proto_rawDesc)))
	})
	return file_op_catalog_v1_datastore_chain_metadata_proto_rawDescData
}

var file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_op_catalog_v1_datastore_chain_metadata_proto_goTypes = []any{
	(*ChainMetadataKeyFilter)(nil),    // 0: api.datastore.v1.ChainMetadataKeyFilter
	(*ChainMetadataFindRequest)(nil),  // 1: api.datastore.v1.ChainMetadataFindRequest
	(*ChainMetadata)(nil),             // 2: api.datastore.v1.ChainMetadata
	(*ChainMetadataFindResponse)(nil), // 3: api.datastore.v1.ChainMetadataFindResponse
	(*ChainMetadataEditRequest)(nil),  // 4: api.datastore.v1.ChainMetadataEditRequest
	(*ChainMetadataEditResponse)(nil), // 5: api.datastore.v1.ChainMetadataEditResponse
	(*wrapperspb.StringValue)(nil),    // 6: google.protobuf.StringValue
	(*wrapperspb.UInt64Value)(nil),    // 7: google.protobuf.UInt64Value
	(EditSemantics)(0),                // 8: api.datastore.v1.EditSemantics
}
var file_op_catalog_v1_datastore_chain_metadata_proto_depIdxs = []int32{
	6, // 0: api.datastore.v1.ChainMetadataKeyFilter.domain:type_name -> google.protobuf.StringValue
	6, // 1: api.datastore.v1.ChainMetadataKeyFilter.environment:type_name -> google.protobuf.StringValue
	7, // 2: api.datastore.v1.ChainMetadataKeyFilter.chain_selector:type_name -> google.protobuf.UInt64Value
	0, // 3: api.datastore.v1.ChainMetadataFindRequest.key_filter:type_name -> api.datastore.v1.ChainMetadataKeyFilter
	2, // 4: api.datastore.v1.ChainMetadataFindResponse.references:type_name -> api.datastore.v1.ChainMetadata
	2, // 5: api.datastore.v1.ChainMetadataEditRequest.record:type_name -> api.datastore.v1.ChainMetadata
	8, // 6: api.datastore.v1.ChainMetadataEditRequest.semantics:type_name -> api.datastore.v1.EditSemantics
	2, // 7: api.datastore.v1.ChainMetadataEditResponse.record:type_name -> api.datastore.v1.ChainMetadata
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_op_catalog_v1_datastore_chain_metadata_proto_init() }
func file_op_catalog_v1_datastore_chain_metadata_proto_init() {
	if File_op_catalog_v1_datastore_chain_metadata_proto != nil {
		return
	}
	file_op_catalog_v1_datastore_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_op_catalog_v1_datastore_chain_metadata_proto_rawDesc), len(file_op_catalog_v1_datastore_chain_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_op_catalog_v1_datastore_chain_metadata_proto_goTypes,
		DependencyIndexes: file_op_catalog_v1_datastore_chain_metadata_proto_depIdxs,
		MessageInfos:      file_op_catalog_v1_datastore_chain_metadata_proto_msgTypes,
	}.Build()
	File_op_catalog_v1_datastore_chain_metadata_proto = out.File
	file_op_catalog_v1_datastore_chain_metadata_proto_goTypes = nil
	file_op_catalog_v1_datastore_chain_metadata_proto_depIdxs = nil
}
