// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: op-catalog/v1/datastore/datastore.proto

package datastore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeploymentsDatastore_DataAccess_FullMethodName = "/api.datastore.v1.DeploymentsDatastore/DataAccess"
)

// DeploymentsDatastoreClient is the client API for DeploymentsDatastore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentsDatastoreClient interface {
	DataAccess(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataAccessRequest, DataAccessResponse], error)
}

type deploymentsDatastoreClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentsDatastoreClient(cc grpc.ClientConnInterface) DeploymentsDatastoreClient {
	return &deploymentsDatastoreClient{cc}
}

func (c *deploymentsDatastoreClient) DataAccess(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataAccessRequest, DataAccessResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeploymentsDatastore_ServiceDesc.Streams[0], DeploymentsDatastore_DataAccess_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataAccessRequest, DataAccessResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeploymentsDatastore_DataAccessClient = grpc.BidiStreamingClient[DataAccessRequest, DataAccessResponse]

// DeploymentsDatastoreServer is the server API for DeploymentsDatastore service.
// All implementations must embed UnimplementedDeploymentsDatastoreServer
// for forward compatibility.
type DeploymentsDatastoreServer interface {
	DataAccess(grpc.BidiStreamingServer[DataAccessRequest, DataAccessResponse]) error
	mustEmbedUnimplementedDeploymentsDatastoreServer()
}

// UnimplementedDeploymentsDatastoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploymentsDatastoreServer struct{}

func (UnimplementedDeploymentsDatastoreServer) DataAccess(grpc.BidiStreamingServer[DataAccessRequest, DataAccessResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DataAccess not implemented")
}
func (UnimplementedDeploymentsDatastoreServer) mustEmbedUnimplementedDeploymentsDatastoreServer() {}
func (UnimplementedDeploymentsDatastoreServer) testEmbeddedByValue()                              {}

// UnsafeDeploymentsDatastoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentsDatastoreServer will
// result in compilation errors.
type UnsafeDeploymentsDatastoreServer interface {
	mustEmbedUnimplementedDeploymentsDatastoreServer()
}

func RegisterDeploymentsDatastoreServer(s grpc.ServiceRegistrar, srv DeploymentsDatastoreServer) {
	// If the following call pancis, it indicates UnimplementedDeploymentsDatastoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploymentsDatastore_ServiceDesc, srv)
}

func _DeploymentsDatastore_DataAccess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeploymentsDatastoreServer).DataAccess(&grpc.GenericServerStream[DataAccessRequest, DataAccessResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeploymentsDatastore_DataAccessServer = grpc.BidiStreamingServer[DataAccessRequest, DataAccessResponse]

// DeploymentsDatastore_ServiceDesc is the grpc.ServiceDesc for DeploymentsDatastore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploymentsDatastore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.datastore.v1.DeploymentsDatastore",
	HandlerType: (*DeploymentsDatastoreServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataAccess",
			Handler:       _DeploymentsDatastore_DataAccess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "op-catalog/v1/datastore/datastore.proto",
}
