preview-staging:
	iron-flask deploy-all -e staging -c ./iron-flask.yaml --preview

deploy-staging:
	iron-flask deploy-all -e staging -c ./iron-flask.yaml

destroy-staging:
	iron-flask deploy-all -e staging -c ./iron-flask.yaml --destroy

preview-prod:
	iron-flask deploy-all -e prod -c ./iron-flask.yaml --preview

deploy-prod:
	iron-flask deploy-all -e prod -c ./iron-flask.yaml

destroy-prod:
	iron-flask deploy-all -e prod -c ./iron-flask.yaml --destroy
