// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: job-distributor/v1/app/app.proto

package app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_job_distributor_v1_app_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_distributor_v1_app_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_job_distributor_v1_app_app_proto_rawDescGZIP(), []int{0}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_job_distributor_v1_app_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_distributor_v1_app_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_job_distributor_v1_app_app_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_job_distributor_v1_app_app_proto protoreflect.FileDescriptor

const file_job_distributor_v1_app_app_proto_rawDesc = "" +
	"\n" +
	" job-distributor/v1/app/app.proto\x12\n" +
	"api.app.v1\"\x10\n" +
	"\x0eVersionRequest\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2R\n" +
	"\n" +
	"AppService\x12D\n" +
	"\aVersion\x12\x1a.api.app.v1.VersionRequest\x1a\x1b.api.app.v1.VersionResponse\"\x00BEZCgithub.com/smartcontractkit/chainlink-protos/job-distributor/v1/appb\x06proto3"

var (
	file_job_distributor_v1_app_app_proto_rawDescOnce sync.Once
	file_job_distributor_v1_app_app_proto_rawDescData []byte
)

func file_job_distributor_v1_app_app_proto_rawDescGZIP() []byte {
	file_job_distributor_v1_app_app_proto_rawDescOnce.Do(func() {
		file_job_distributor_v1_app_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_distributor_v1_app_app_proto_rawDesc), len(file_job_distributor_v1_app_app_proto_rawDesc)))
	})
	return file_job_distributor_v1_app_app_proto_rawDescData
}

var file_job_distributor_v1_app_app_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_job_distributor_v1_app_app_proto_goTypes = []any{
	(*VersionRequest)(nil),  // 0: api.app.v1.VersionRequest
	(*VersionResponse)(nil), // 1: api.app.v1.VersionResponse
}
var file_job_distributor_v1_app_app_proto_depIdxs = []int32{
	0, // 0: api.app.v1.AppService.Version:input_type -> api.app.v1.VersionRequest
	1, // 1: api.app.v1.AppService.Version:output_type -> api.app.v1.VersionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_distributor_v1_app_app_proto_init() }
func file_job_distributor_v1_app_app_proto_init() {
	if File_job_distributor_v1_app_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_distributor_v1_app_app_proto_rawDesc), len(file_job_distributor_v1_app_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_distributor_v1_app_app_proto_goTypes,
		DependencyIndexes: file_job_distributor_v1_app_app_proto_depIdxs,
		MessageInfos:      file_job_distributor_v1_app_app_proto_msgTypes,
	}.Build()
	File_job_distributor_v1_app_app_proto = out.File
	file_job_distributor_v1_app_app_proto_goTypes = nil
	file_job_distributor_v1_app_app_proto_depIdxs = nil
}
