packages:
  - 'job-distributor'
  - 'orchestrator'
  - 'svr'
  - 'rmn'
  - 'storage-service'
  - 'op-catalog'
  - 'rane'
  - 'chainlink-ccv/verifier'
  - 'chainlink-ccv/committee-verifier'
  - 'chainlink-ccv/message-discovery'
  - 'chainlink-ccv/heartbeat'
