# https://taskfile.dev

version: "3"

tasks:
  fmt:
    desc: "Run buf format"
    cmds:
      - buf format -w

  lint:
    desc: "Run buf lint"
    cmds:
      - buf lint

  proto:all:
    desc: Generate all protobuf files for all services
    cmds:
      - task proto:gen:job-distributor
      - task proto:gen:orchestrator
      - task proto:gen:svr
      - task proto:gen:rmn
      - task proto:gen:workflows
      - task go:mod:tidy

  proto:gen:job-distributor:
    desc: Generate all protobuf files for the job-distributor service
    cmds:
      - find ./job-distributor/ -name '*.pb.go' -delete
      - task: proto:gen
        vars:
          SERVICE_NAME: job-distributor

  proto:gen:orchestrator:
    desc: "Generate Go code from protobuf files for orchestrator"
    cmds:
      - find ./orchestrator/ -name '*.pb.go' -delete
      - task: proto:wsrpc:gen
        vars:
          SERVICE_NAME: orchestrator

  proto:gen:svr:
    desc: "Generate Go code from protobuf files for svr"
    cmds:
      - find ./svr/ -name '*.pb.go' -delete
      - task: proto:gen
        vars:
          SERVICE_NAME: svr

  proto:gen:rmn:
      desc: "Generate Go code from protobuf files for rmn"
      cmds:
        - find ./rmn/v1.6/go -name '*.pb.go' -delete
        - |
          proto_files=$(find ./rmn/v1.6/proto -name "*.proto")
          protoc \
            -I=./rmn/v1.6/proto \
            --go_out=./rmn/v1.6/go \
            --go_opt=paths=source_relative \
            --go-grpc_out=./rmn/v1.6/go \
            --go-grpc_opt=paths=source_relative \
            $proto_files
        - cd rmn/v1.6/rust && cargo build

  proto:gen:workflows:
      desc: "Generate Go code from protobuf files for workflows v1"
      cmds:
        - find ./workflows/v1/go -name '*.pb.go' -delete
        - |
          proto_files=$(find ./workflows/v1/proto -name "*.proto")
          protoc \
            -I=./workflows/v1/proto \
            --go_out=./workflows/v1/go \
            --go_opt=paths=source_relative \
            $proto_files

  proto:clean:
    desc: "Clean generated protobuf files for all services"
    cmds:
      - find ./job-distributor/ -name '*.pb.go' -delete
      - find ./orchestrator/ -name '*.pb.go' -delete
      - find ./svr/ -name '*.pb.go' -delete

  go:mod:tidy:
    desc: "Run go mod tidy in each service folder"
    cmds:
      - (cd ./job-distributor && go mod tidy)
      - (cd ./orchestrator && go mod tidy)
      - (cd ./svr && go mod tidy)
      - (cd ./rmn/v1.6/go && go mod tidy)

  proto:gen:
    internal: true
    desc: "Generate Go code from protobuf files"
    cmds:
      - |
        proto_files=$(find ./{{.SERVICE_NAME}} -name "*.proto")
        protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative $proto_files

  proto:wsrpc:gen:
    internal: true
    desc: "Generate Go code from protobuf files with wsrpc"
    cmds:
      - |
        proto_files=$(find ./{{.SERVICE_NAME}} -name "*.proto")
        protoc --go_out=. --go_opt=paths=source_relative --go-wsrpc_out=. --go-wsrpc_opt=paths=source_relative $proto_files
