// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bridge_status/v1/configuration_item.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigurationItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value              string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type               string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Required           bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue       string                 `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	CustomSetting      bool                   `protobuf:"varint,7,opt,name=custom_setting,json=customSetting,proto3" json:"custom_setting,omitempty"`
	EnvDefaultOverride string                 `protobuf:"bytes,8,opt,name=env_default_override,json=envDefaultOverride,proto3" json:"env_default_override,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfigurationItem) Reset() {
	*x = ConfigurationItem{}
	mi := &file_bridge_status_v1_configuration_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationItem) ProtoMessage() {}

func (x *ConfigurationItem) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_status_v1_configuration_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationItem.ProtoReflect.Descriptor instead.
func (*ConfigurationItem) Descriptor() ([]byte, []int) {
	return file_bridge_status_v1_configuration_item_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigurationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigurationItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigurationItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigurationItem) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigurationItem) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigurationItem) GetCustomSetting() bool {
	if x != nil {
		return x.CustomSetting
	}
	return false
}

func (x *ConfigurationItem) GetEnvDefaultOverride() string {
	if x != nil {
		return x.EnvDefaultOverride
	}
	return ""
}

var File_bridge_status_v1_configuration_item_proto protoreflect.FileDescriptor

const file_bridge_status_v1_configuration_item_proto_rawDesc = "" +
	"\n" +
	")bridge_status/v1/configuration_item.proto\x12\x10bridge_status.v1\"\x8d\x02\n" +
	"\x11ConfigurationItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValue\x12%\n" +
	"\x0ecustom_setting\x18\a \x01(\bR\rcustomSetting\x120\n" +
	"\x14env_default_override\x18\b \x01(\tR\x12envDefaultOverrideBJZHgithub.com/smartcontractkit/chainlink-protos/data-feeds/bridge_status/v1b\x06proto3"

var (
	file_bridge_status_v1_configuration_item_proto_rawDescOnce sync.Once
	file_bridge_status_v1_configuration_item_proto_rawDescData []byte
)

func file_bridge_status_v1_configuration_item_proto_rawDescGZIP() []byte {
	file_bridge_status_v1_configuration_item_proto_rawDescOnce.Do(func() {
		file_bridge_status_v1_configuration_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_status_v1_configuration_item_proto_rawDesc), len(file_bridge_status_v1_configuration_item_proto_rawDesc)))
	})
	return file_bridge_status_v1_configuration_item_proto_rawDescData
}

var file_bridge_status_v1_configuration_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bridge_status_v1_configuration_item_proto_goTypes = []any{
	(*ConfigurationItem)(nil), // 0: bridge_status.v1.ConfigurationItem
}
var file_bridge_status_v1_configuration_item_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bridge_status_v1_configuration_item_proto_init() }
func file_bridge_status_v1_configuration_item_proto_init() {
	if File_bridge_status_v1_configuration_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_status_v1_configuration_item_proto_rawDesc), len(file_bridge_status_v1_configuration_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_status_v1_configuration_item_proto_goTypes,
		DependencyIndexes: file_bridge_status_v1_configuration_item_proto_depIdxs,
		MessageInfos:      file_bridge_status_v1_configuration_item_proto_msgTypes,
	}.Build()
	File_bridge_status_v1_configuration_item_proto = out.File
	file_bridge_status_v1_configuration_item_proto_goTypes = nil
	file_bridge_status_v1_configuration_item_proto_depIdxs = nil
}
