// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: bridge_status/v1/runtime_info.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeVersion   string                 `protobuf:"bytes,1,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Architecture  string                 `protobuf:"bytes,3,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_bridge_status_v1_runtime_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_status_v1_runtime_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_bridge_status_v1_runtime_info_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeInfo) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *RuntimeInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RuntimeInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *RuntimeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

var File_bridge_status_v1_runtime_info_proto protoreflect.FileDescriptor

const file_bridge_status_v1_runtime_info_proto_rawDesc = "" +
	"\n" +
	"#bridge_status/v1/runtime_info.proto\x12\x10bridge_status.v1\"\x8c\x01\n" +
	"\vRuntimeInfo\x12!\n" +
	"\fnode_version\x18\x01 \x01(\tR\vnodeVersion\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\"\n" +
	"\farchitecture\x18\x03 \x01(\tR\farchitecture\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostnameBJZHgithub.com/smartcontractkit/chainlink-protos/data-feeds/bridge_status/v1b\x06proto3"

var (
	file_bridge_status_v1_runtime_info_proto_rawDescOnce sync.Once
	file_bridge_status_v1_runtime_info_proto_rawDescData []byte
)

func file_bridge_status_v1_runtime_info_proto_rawDescGZIP() []byte {
	file_bridge_status_v1_runtime_info_proto_rawDescOnce.Do(func() {
		file_bridge_status_v1_runtime_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_status_v1_runtime_info_proto_rawDesc), len(file_bridge_status_v1_runtime_info_proto_rawDesc)))
	})
	return file_bridge_status_v1_runtime_info_proto_rawDescData
}

var file_bridge_status_v1_runtime_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bridge_status_v1_runtime_info_proto_goTypes = []any{
	(*RuntimeInfo)(nil), // 0: bridge_status.v1.RuntimeInfo
}
var file_bridge_status_v1_runtime_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bridge_status_v1_runtime_info_proto_init() }
func file_bridge_status_v1_runtime_info_proto_init() {
	if File_bridge_status_v1_runtime_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_status_v1_runtime_info_proto_rawDesc), len(file_bridge_status_v1_runtime_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bridge_status_v1_runtime_info_proto_goTypes,
		DependencyIndexes: file_bridge_status_v1_runtime_info_proto_depIdxs,
		MessageInfos:      file_bridge_status_v1_runtime_info_proto_msgTypes,
	}.Build()
	File_bridge_status_v1_runtime_info_proto = out.File
	file_bridge_status_v1_runtime_info_proto_goTypes = nil
	file_bridge_status_v1_runtime_info_proto_depIdxs = nil
}
