// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: v1/workflow-ownership-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_workflow_ownership_service_proto protoreflect.FileDescriptor

const file_v1_workflow_ownership_service_proto_rawDesc = "" +
	"\n" +
	"#v1/workflow-ownership-service.proto\x12\x14workflowownership.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a!v1/workflow-ownership-types.proto2\xba\x01\n" +
	"\x1dWorkflowOwnershipProofService\x12\x98\x01\n" +
	"\x1dGetOrganizationFromWorkflowID\x12:.workflowownership.v1.GetOrganizationFromWorkflowIDRequest\x1a;.workflowownership.v1.GetOrganizationFromWorkflowIDResponseBOZMgithub.com/smartcontractkit/chainlink-protos/workflow-ownership-service/go/v1b\x06proto3"

var file_v1_workflow_ownership_service_proto_goTypes = []any{
	(*GetOrganizationFromWorkflowIDRequest)(nil),  // 0: workflowownership.v1.GetOrganizationFromWorkflowIDRequest
	(*GetOrganizationFromWorkflowIDResponse)(nil), // 1: workflowownership.v1.GetOrganizationFromWorkflowIDResponse
}
var file_v1_workflow_ownership_service_proto_depIdxs = []int32{
	0, // 0: workflowownership.v1.WorkflowOwnershipProofService.GetOrganizationFromWorkflowID:input_type -> workflowownership.v1.GetOrganizationFromWorkflowIDRequest
	1, // 1: workflowownership.v1.WorkflowOwnershipProofService.GetOrganizationFromWorkflowID:output_type -> workflowownership.v1.GetOrganizationFromWorkflowIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_workflow_ownership_service_proto_init() }
func file_v1_workflow_ownership_service_proto_init() {
	if File_v1_workflow_ownership_service_proto != nil {
		return
	}
	file_v1_workflow_ownership_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_workflow_ownership_service_proto_rawDesc), len(file_v1_workflow_ownership_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_workflow_ownership_service_proto_goTypes,
		DependencyIndexes: file_v1_workflow_ownership_service_proto_depIdxs,
	}.Build()
	File_v1_workflow_ownership_service_proto = out.File
	file_v1_workflow_ownership_service_proto_goTypes = nil
	file_v1_workflow_ownership_service_proto_depIdxs = nil
}
