// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/linking-types.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrganizationFromWorkflowOwnerRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	WorkflowOwner           string                 `protobuf:"bytes,1,opt,name=workflow_owner,json=workflowOwner,proto3" json:"workflow_owner,omitempty"`
	WorkflowRegistryAddress string                 `protobuf:"bytes,2,opt,name=workflow_registry_address,json=workflowRegistryAddress,proto3" json:"workflow_registry_address,omitempty"`
	ChainSelector           uint64                 `protobuf:"varint,3,opt,name=chain_selector,json=chainSelector,proto3" json:"chain_selector,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetOrganizationFromWorkflowOwnerRequest) Reset() {
	*x = GetOrganizationFromWorkflowOwnerRequest{}
	mi := &file_v1_linking_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationFromWorkflowOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationFromWorkflowOwnerRequest) ProtoMessage() {}

func (x *GetOrganizationFromWorkflowOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_linking_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationFromWorkflowOwnerRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationFromWorkflowOwnerRequest) Descriptor() ([]byte, []int) {
	return file_v1_linking_types_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrganizationFromWorkflowOwnerRequest) GetWorkflowOwner() string {
	if x != nil {
		return x.WorkflowOwner
	}
	return ""
}

func (x *GetOrganizationFromWorkflowOwnerRequest) GetWorkflowRegistryAddress() string {
	if x != nil {
		return x.WorkflowRegistryAddress
	}
	return ""
}

func (x *GetOrganizationFromWorkflowOwnerRequest) GetChainSelector() uint64 {
	if x != nil {
		return x.ChainSelector
	}
	return 0
}

type GetOrganizationFromWorkflowOwnerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizationFromWorkflowOwnerResponse) Reset() {
	*x = GetOrganizationFromWorkflowOwnerResponse{}
	mi := &file_v1_linking_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationFromWorkflowOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationFromWorkflowOwnerResponse) ProtoMessage() {}

func (x *GetOrganizationFromWorkflowOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_linking_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationFromWorkflowOwnerResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationFromWorkflowOwnerResponse) Descriptor() ([]byte, []int) {
	return file_v1_linking_types_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrganizationFromWorkflowOwnerResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

var File_v1_linking_types_proto protoreflect.FileDescriptor

const file_v1_linking_types_proto_rawDesc = "" +
	"\n" +
	"\x16v1/linking-types.proto\x12\n" +
	"linking.v1\"\xb3\x01\n" +
	"'GetOrganizationFromWorkflowOwnerRequest\x12%\n" +
	"\x0eworkflow_owner\x18\x01 \x01(\tR\rworkflowOwner\x12:\n" +
	"\x19workflow_registry_address\x18\x02 \x01(\tR\x17workflowRegistryAddress\x12%\n" +
	"\x0echain_selector\x18\x03 \x01(\x04R\rchainSelector\"S\n" +
	"(GetOrganizationFromWorkflowOwnerResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationIdBDZBgithub.com/smartcontractkit/chainlink-protos/linking-service/go/v1b\x06proto3"

var (
	file_v1_linking_types_proto_rawDescOnce sync.Once
	file_v1_linking_types_proto_rawDescData []byte
)

func file_v1_linking_types_proto_rawDescGZIP() []byte {
	file_v1_linking_types_proto_rawDescOnce.Do(func() {
		file_v1_linking_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_linking_types_proto_rawDesc), len(file_v1_linking_types_proto_rawDesc)))
	})
	return file_v1_linking_types_proto_rawDescData
}

var file_v1_linking_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_linking_types_proto_goTypes = []any{
	(*GetOrganizationFromWorkflowOwnerRequest)(nil),  // 0: linking.v1.GetOrganizationFromWorkflowOwnerRequest
	(*GetOrganizationFromWorkflowOwnerResponse)(nil), // 1: linking.v1.GetOrganizationFromWorkflowOwnerResponse
}
var file_v1_linking_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_linking_types_proto_init() }
func file_v1_linking_types_proto_init() {
	if File_v1_linking_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_linking_types_proto_rawDesc), len(file_v1_linking_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_linking_types_proto_goTypes,
		DependencyIndexes: file_v1_linking_types_proto_depIdxs,
		MessageInfos:      file_v1_linking_types_proto_msgTypes,
	}.Build()
	File_v1_linking_types_proto = out.File
	file_v1_linking_types_proto_goTypes = nil
	file_v1_linking_types_proto_depIdxs = nil
}
