// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: metering/v1/meter_record.proto

package metering

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeterRecord is a durable, first-class billing event. Each record captures one
// signed delta: the level change of one request for a durable resource
// (METER_ACTION_UPDATE) or one instantaneous occurrence of consumption
// (METER_ACTION_USAGE). Records give the consumer precise request-time edges and
// the audit trail. The periodic absolute level of each active resource — and the
// only lifecycle-cleanup signal — is carried by MeterSnapshot; the two streams
// are complementary load-bearing billing data.
//
// Bucket semantics: An org draws down credits in a time bucket if the bucket
// contains any positive-delta UPDATE record, any USAGE record, or any nonzero
// snapshot for a resource attributed to that org. A +N and -N cancelling within
// one bucket still triggers drawdown via the positive delta.
type MeterRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time at which the metered request/occurrence happened (a raw edge, not
	// truncated to a bucket boundary).
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Structured identity of the affected resource (deployment/DON/node
	// dimensions + service + resource/resource_type + the physical resource_id).
	Identity *ResourceIdentity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// Billing semantics of this record: METER_ACTION_UPDATE (signed level delta)
	// or METER_ACTION_USAGE (one-off consumption).
	Action MeterAction `protobuf:"varint,3,opt,name=action,proto3,enum=metering.v1.MeterAction" json:"action,omitempty"`
	// One or more utilization quantities for this event (e.g. multiple billing
	// units affected by the same request).
	Utilizations  []*Utilization `protobuf:"bytes,4,rep,name=utilizations,proto3" json:"utilizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeterRecord) Reset() {
	*x = MeterRecord{}
	mi := &file_metering_v1_meter_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeterRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterRecord) ProtoMessage() {}

func (x *MeterRecord) ProtoReflect() protoreflect.Message {
	mi := &file_metering_v1_meter_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterRecord.ProtoReflect.Descriptor instead.
func (*MeterRecord) Descriptor() ([]byte, []int) {
	return file_metering_v1_meter_record_proto_rawDescGZIP(), []int{0}
}

func (x *MeterRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MeterRecord) GetIdentity() *ResourceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *MeterRecord) GetAction() MeterAction {
	if x != nil {
		return x.Action
	}
	return MeterAction_METER_ACTION_UNSPECIFIED
}

func (x *MeterRecord) GetUtilizations() []*Utilization {
	if x != nil {
		return x.Utilizations
	}
	return nil
}

var File_metering_v1_meter_record_proto protoreflect.FileDescriptor

const file_metering_v1_meter_record_proto_rawDesc = "" +
	"\n" +
	"\x1emetering/v1/meter_record.proto\x12\vmetering.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametering/v1/identity.proto\x1a\x1dmetering/v1/utilization.proto\"\xf2\x01\n" +
	"\vMeterRecord\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\bidentity\x18\x02 \x01(\v2\x1d.metering.v1.ResourceIdentityR\bidentity\x120\n" +
	"\x06action\x18\x03 \x01(\x0e2\x18.metering.v1.MeterActionR\x06action\x12<\n" +
	"\futilizations\x18\x04 \x03(\v2\x18.metering.v1.UtilizationR\futilizationsBCZAgithub.com/smartcontractkit/chainlink-protos/metering/go;meteringb\x06proto3"

var (
	file_metering_v1_meter_record_proto_rawDescOnce sync.Once
	file_metering_v1_meter_record_proto_rawDescData []byte
)

func file_metering_v1_meter_record_proto_rawDescGZIP() []byte {
	file_metering_v1_meter_record_proto_rawDescOnce.Do(func() {
		file_metering_v1_meter_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metering_v1_meter_record_proto_rawDesc), len(file_metering_v1_meter_record_proto_rawDesc)))
	})
	return file_metering_v1_meter_record_proto_rawDescData
}

var file_metering_v1_meter_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metering_v1_meter_record_proto_goTypes = []any{
	(*MeterRecord)(nil),           // 0: metering.v1.MeterRecord
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*ResourceIdentity)(nil),      // 2: metering.v1.ResourceIdentity
	(MeterAction)(0),              // 3: metering.v1.MeterAction
	(*Utilization)(nil),           // 4: metering.v1.Utilization
}
var file_metering_v1_meter_record_proto_depIdxs = []int32{
	1, // 0: metering.v1.MeterRecord.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: metering.v1.MeterRecord.identity:type_name -> metering.v1.ResourceIdentity
	3, // 2: metering.v1.MeterRecord.action:type_name -> metering.v1.MeterAction
	4, // 3: metering.v1.MeterRecord.utilizations:type_name -> metering.v1.Utilization
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metering_v1_meter_record_proto_init() }
func file_metering_v1_meter_record_proto_init() {
	if File_metering_v1_meter_record_proto != nil {
		return
	}
	file_metering_v1_identity_proto_init()
	file_metering_v1_utilization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metering_v1_meter_record_proto_rawDesc), len(file_metering_v1_meter_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metering_v1_meter_record_proto_goTypes,
		DependencyIndexes: file_metering_v1_meter_record_proto_depIdxs,
		MessageInfos:      file_metering_v1_meter_record_proto_msgTypes,
	}.Build()
	File_metering_v1_meter_record_proto = out.File
	file_metering_v1_meter_record_proto_goTypes = nil
	file_metering_v1_meter_record_proto_depIdxs = nil
}
