// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: metering/v1/snapshot.proto

package metering

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MeterSnapshot is the ACTION-LESS periodic absolute level of EXACTLY ONE active
// durable resource, uniquely identified by its ResourceIdentity (including
// resource_id). It is load-bearing billing data: it provides the level and the
// only lifecycle-cleanup signal, giving liveness and level reconciliation that
// bounds drift in the delta-based MeterRecord stream. It is also the magnitude
// the billing median-across-nodes reducer consumes.
//
// One MeterSnapshot covers one resource; the resource manager emits a separate
// MeterSnapshot per active resource each interval. There is no batch and no
// sequence number: each snapshot stands alone, keyed by its ResourceIdentity
// and timestamp. A resource that stops being snapshotted is released — this
// absence is the only lifecycle-cleanup mechanism. MeterAction does NOT apply to
// snapshots.
type MeterSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time at which the snapshot was taken (the interval boundary it covers).
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Full identity of the one resource this snapshot covers: the six coarse
	// dimensions (product, environment, zone, don_id, node_id, service) plus
	// resource, resource_type, and resource_id.
	Identity *ResourceIdentity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// Utilization of this one resource. value is the current level; the
	// per-interval increment is value over the interval below.
	Utilization []*Utilization `protobuf:"bytes,3,rep,name=utilization,proto3" json:"utilization,omitempty"`
	// Nominal period this snapshot covers, for staleness detection and for
	// computing the per-interval increment by the consumer.
	Interval      *durationpb.Duration `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeterSnapshot) Reset() {
	*x = MeterSnapshot{}
	mi := &file_metering_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeterSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeterSnapshot) ProtoMessage() {}

func (x *MeterSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_metering_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeterSnapshot.ProtoReflect.Descriptor instead.
func (*MeterSnapshot) Descriptor() ([]byte, []int) {
	return file_metering_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *MeterSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MeterSnapshot) GetIdentity() *ResourceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *MeterSnapshot) GetUtilization() []*Utilization {
	if x != nil {
		return x.Utilization
	}
	return nil
}

func (x *MeterSnapshot) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_metering_v1_snapshot_proto protoreflect.FileDescriptor

const file_metering_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1ametering/v1/snapshot.proto\x12\vmetering.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametering/v1/identity.proto\x1a\x1dmetering/v1/utilization.proto\"\xf7\x01\n" +
	"\rMeterSnapshot\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\bidentity\x18\x02 \x01(\v2\x1d.metering.v1.ResourceIdentityR\bidentity\x12:\n" +
	"\vutilization\x18\x03 \x03(\v2\x18.metering.v1.UtilizationR\vutilization\x125\n" +
	"\binterval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bintervalBCZAgithub.com/smartcontractkit/chainlink-protos/metering/go;meteringb\x06proto3"

var (
	file_metering_v1_snapshot_proto_rawDescOnce sync.Once
	file_metering_v1_snapshot_proto_rawDescData []byte
)

func file_metering_v1_snapshot_proto_rawDescGZIP() []byte {
	file_metering_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_metering_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metering_v1_snapshot_proto_rawDesc), len(file_metering_v1_snapshot_proto_rawDesc)))
	})
	return file_metering_v1_snapshot_proto_rawDescData
}

var file_metering_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metering_v1_snapshot_proto_goTypes = []any{
	(*MeterSnapshot)(nil),         // 0: metering.v1.MeterSnapshot
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*ResourceIdentity)(nil),      // 2: metering.v1.ResourceIdentity
	(*Utilization)(nil),           // 3: metering.v1.Utilization
	(*durationpb.Duration)(nil),   // 4: google.protobuf.Duration
}
var file_metering_v1_snapshot_proto_depIdxs = []int32{
	1, // 0: metering.v1.MeterSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: metering.v1.MeterSnapshot.identity:type_name -> metering.v1.ResourceIdentity
	3, // 2: metering.v1.MeterSnapshot.utilization:type_name -> metering.v1.Utilization
	4, // 3: metering.v1.MeterSnapshot.interval:type_name -> google.protobuf.Duration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metering_v1_snapshot_proto_init() }
func file_metering_v1_snapshot_proto_init() {
	if File_metering_v1_snapshot_proto != nil {
		return
	}
	file_metering_v1_identity_proto_init()
	file_metering_v1_utilization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metering_v1_snapshot_proto_rawDesc), len(file_metering_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metering_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_metering_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_metering_v1_snapshot_proto_msgTypes,
	}.Build()
	File_metering_v1_snapshot_proto = out.File
	file_metering_v1_snapshot_proto_goTypes = nil
	file_metering_v1_snapshot_proto_depIdxs = nil
}
