// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/shared/ptypes/label.proto

package ptypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SelectorOp defines the operation to be used in a selector
type SelectorOp int32

const (
	SelectorOp_EQ        SelectorOp = 0
	SelectorOp_NOT_EQ    SelectorOp = 1
	SelectorOp_IN        SelectorOp = 2
	SelectorOp_NOT_IN    SelectorOp = 3
	SelectorOp_EXIST     SelectorOp = 4
	SelectorOp_NOT_EXIST SelectorOp = 5
)

// Enum value maps for SelectorOp.
var (
	SelectorOp_name = map[int32]string{
		0: "EQ",
		1: "NOT_EQ",
		2: "IN",
		3: "NOT_IN",
		4: "EXIST",
		5: "NOT_EXIST",
	}
	SelectorOp_value = map[string]int32{
		"EQ":        0,
		"NOT_EQ":    1,
		"IN":        2,
		"NOT_IN":    3,
		"EXIST":     4,
		"NOT_EXIST": 5,
	}
)

func (x SelectorOp) Enum() *SelectorOp {
	p := new(SelectorOp)
	*p = x
	return p
}

func (x SelectorOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectorOp) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_shared_ptypes_label_proto_enumTypes[0].Descriptor()
}

func (SelectorOp) Type() protoreflect.EnumType {
	return &file_v1_shared_ptypes_label_proto_enumTypes[0]
}

func (x SelectorOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectorOp.Descriptor instead.
func (SelectorOp) EnumDescriptor() ([]byte, []int) {
	return file_v1_shared_ptypes_label_proto_rawDescGZIP(), []int{0}
}

// Label defines a label as a key value pair
type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_v1_shared_ptypes_label_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_ptypes_label_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_v1_shared_ptypes_label_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// Selector defines a selector as a key value pair with an operation
type Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Op            SelectorOp             `protobuf:"varint,2,opt,name=op,proto3,enum=api.label.SelectorOp" json:"op,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_v1_shared_ptypes_label_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_v1_shared_ptypes_label_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_v1_shared_ptypes_label_proto_rawDescGZIP(), []int{1}
}

func (x *Selector) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Selector) GetOp() SelectorOp {
	if x != nil {
		return x.Op
	}
	return SelectorOp_EQ
}

func (x *Selector) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

var File_v1_shared_ptypes_label_proto protoreflect.FileDescriptor

const file_v1_shared_ptypes_label_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/shared/ptypes/label.proto\x12\tapi.label\">\n" +
	"\x05Label\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"h\n" +
	"\bSelector\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x02op\x18\x02 \x01(\x0e2\x15.api.label.SelectorOpR\x02op\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value*N\n" +
	"\n" +
	"SelectorOp\x12\x06\n" +
	"\x02EQ\x10\x00\x12\n" +
	"\n" +
	"\x06NOT_EQ\x10\x01\x12\x06\n" +
	"\x02IN\x10\x02\x12\n" +
	"\n" +
	"\x06NOT_IN\x10\x03\x12\t\n" +
	"\x05EXIST\x10\x04\x12\r\n" +
	"\tNOT_EXIST\x10\x05BOZMgithub.com/smartcontractkit/chainlink-protos/job-distributor/v1/shared/ptypesb\x06proto3"

var (
	file_v1_shared_ptypes_label_proto_rawDescOnce sync.Once
	file_v1_shared_ptypes_label_proto_rawDescData []byte
)

func file_v1_shared_ptypes_label_proto_rawDescGZIP() []byte {
	file_v1_shared_ptypes_label_proto_rawDescOnce.Do(func() {
		file_v1_shared_ptypes_label_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_shared_ptypes_label_proto_rawDesc), len(file_v1_shared_ptypes_label_proto_rawDesc)))
	})
	return file_v1_shared_ptypes_label_proto_rawDescData
}

var file_v1_shared_ptypes_label_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_shared_ptypes_label_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_shared_ptypes_label_proto_goTypes = []any{
	(SelectorOp)(0),  // 0: api.label.SelectorOp
	(*Label)(nil),    // 1: api.label.Label
	(*Selector)(nil), // 2: api.label.Selector
}
var file_v1_shared_ptypes_label_proto_depIdxs = []int32{
	0, // 0: api.label.Selector.op:type_name -> api.label.SelectorOp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_shared_ptypes_label_proto_init() }
func file_v1_shared_ptypes_label_proto_init() {
	if File_v1_shared_ptypes_label_proto != nil {
		return
	}
	file_v1_shared_ptypes_label_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_shared_ptypes_label_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_shared_ptypes_label_proto_rawDesc), len(file_v1_shared_ptypes_label_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_shared_ptypes_label_proto_goTypes,
		DependencyIndexes: file_v1_shared_ptypes_label_proto_depIdxs,
		EnumInfos:         file_v1_shared_ptypes_label_proto_enumTypes,
		MessageInfos:      file_v1_shared_ptypes_label_proto_msgTypes,
	}.Build()
	File_v1_shared_ptypes_label_proto = out.File
	file_v1_shared_ptypes_label_proto_goTypes = nil
	file_v1_shared_ptypes_label_proto_depIdxs = nil
}
