// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: job-distributor/v1/csa/csa.proto

package csa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Keypair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keypair) Reset() {
	*x = Keypair{}
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keypair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keypair) ProtoMessage() {}

func (x *Keypair) ProtoReflect() protoreflect.Message {
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keypair.ProtoReflect.Descriptor instead.
func (*Keypair) Descriptor() ([]byte, []int) {
	return file_job_distributor_v1_csa_csa_proto_rawDescGZIP(), []int{0}
}

func (x *Keypair) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Keypair) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Keypair) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetKeypairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeypairRequest) Reset() {
	*x = GetKeypairRequest{}
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeypairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeypairRequest) ProtoMessage() {}

func (x *GetKeypairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeypairRequest.ProtoReflect.Descriptor instead.
func (*GetKeypairRequest) Descriptor() ([]byte, []int) {
	return file_job_distributor_v1_csa_csa_proto_rawDescGZIP(), []int{1}
}

type GetKeypairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keypair       *Keypair               `protobuf:"bytes,1,opt,name=keypair,proto3" json:"keypair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeypairResponse) Reset() {
	*x = GetKeypairResponse{}
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeypairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeypairResponse) ProtoMessage() {}

func (x *GetKeypairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeypairResponse.ProtoReflect.Descriptor instead.
func (*GetKeypairResponse) Descriptor() ([]byte, []int) {
	return file_job_distributor_v1_csa_csa_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeypairResponse) GetKeypair() *Keypair {
	if x != nil {
		return x.Keypair
	}
	return nil
}

type ListKeypairsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeypairsRequest) Reset() {
	*x = ListKeypairsRequest{}
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeypairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeypairsRequest) ProtoMessage() {}

func (x *ListKeypairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeypairsRequest.ProtoReflect.Descriptor instead.
func (*ListKeypairsRequest) Descriptor() ([]byte, []int) {
	return file_job_distributor_v1_csa_csa_proto_rawDescGZIP(), []int{3}
}

type ListKeypairsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keypairs      []*Keypair             `protobuf:"bytes,1,rep,name=keypairs,proto3" json:"keypairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeypairsResponse) Reset() {
	*x = ListKeypairsResponse{}
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeypairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeypairsResponse) ProtoMessage() {}

func (x *ListKeypairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_distributor_v1_csa_csa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeypairsResponse.ProtoReflect.Descriptor instead.
func (*ListKeypairsResponse) Descriptor() ([]byte, []int) {
	return file_job_distributor_v1_csa_csa_proto_rawDescGZIP(), []int{4}
}

func (x *ListKeypairsResponse) GetKeypairs() []*Keypair {
	if x != nil {
		return x.Keypairs
	}
	return nil
}

var File_job_distributor_v1_csa_csa_proto protoreflect.FileDescriptor

const file_job_distributor_v1_csa_csa_proto_rawDesc = "" +
	"\n" +
	" job-distributor/v1/csa/csa.proto\x12\n" +
	"api.csa.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n" +
	"\aKeypair\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x13\n" +
	"\x11GetKeypairRequest\"C\n" +
	"\x12GetKeypairResponse\x12-\n" +
	"\akeypair\x18\x01 \x01(\v2\x13.api.csa.v1.KeypairR\akeypair\"\x15\n" +
	"\x13ListKeypairsRequest\"G\n" +
	"\x14ListKeypairsResponse\x12/\n" +
	"\bkeypairs\x18\x01 \x03(\v2\x13.api.csa.v1.KeypairR\bkeypairs2\xac\x01\n" +
	"\n" +
	"CSAService\x12K\n" +
	"\n" +
	"GetKeypair\x12\x1d.api.csa.v1.GetKeypairRequest\x1a\x1e.api.csa.v1.GetKeypairResponse\x12Q\n" +
	"\fListKeypairs\x12\x1f.api.csa.v1.ListKeypairsRequest\x1a .api.csa.v1.ListKeypairsResponseBEZCgithub.com/smartcontractkit/chainlink-protos/job-distributor/v1/csab\x06proto3"

var (
	file_job_distributor_v1_csa_csa_proto_rawDescOnce sync.Once
	file_job_distributor_v1_csa_csa_proto_rawDescData []byte
)

func file_job_distributor_v1_csa_csa_proto_rawDescGZIP() []byte {
	file_job_distributor_v1_csa_csa_proto_rawDescOnce.Do(func() {
		file_job_distributor_v1_csa_csa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_distributor_v1_csa_csa_proto_rawDesc), len(file_job_distributor_v1_csa_csa_proto_rawDesc)))
	})
	return file_job_distributor_v1_csa_csa_proto_rawDescData
}

var file_job_distributor_v1_csa_csa_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_job_distributor_v1_csa_csa_proto_goTypes = []any{
	(*Keypair)(nil),               // 0: api.csa.v1.Keypair
	(*GetKeypairRequest)(nil),     // 1: api.csa.v1.GetKeypairRequest
	(*GetKeypairResponse)(nil),    // 2: api.csa.v1.GetKeypairResponse
	(*ListKeypairsRequest)(nil),   // 3: api.csa.v1.ListKeypairsRequest
	(*ListKeypairsResponse)(nil),  // 4: api.csa.v1.ListKeypairsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_job_distributor_v1_csa_csa_proto_depIdxs = []int32{
	5, // 0: api.csa.v1.Keypair.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: api.csa.v1.GetKeypairResponse.keypair:type_name -> api.csa.v1.Keypair
	0, // 2: api.csa.v1.ListKeypairsResponse.keypairs:type_name -> api.csa.v1.Keypair
	1, // 3: api.csa.v1.CSAService.GetKeypair:input_type -> api.csa.v1.GetKeypairRequest
	3, // 4: api.csa.v1.CSAService.ListKeypairs:input_type -> api.csa.v1.ListKeypairsRequest
	2, // 5: api.csa.v1.CSAService.GetKeypair:output_type -> api.csa.v1.GetKeypairResponse
	4, // 6: api.csa.v1.CSAService.ListKeypairs:output_type -> api.csa.v1.ListKeypairsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_job_distributor_v1_csa_csa_proto_init() }
func file_job_distributor_v1_csa_csa_proto_init() {
	if File_job_distributor_v1_csa_csa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_distributor_v1_csa_csa_proto_rawDesc), len(file_job_distributor_v1_csa_csa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_distributor_v1_csa_csa_proto_goTypes,
		DependencyIndexes: file_job_distributor_v1_csa_csa_proto_depIdxs,
		MessageInfos:      file_job_distributor_v1_csa_csa_proto_msgTypes,
	}.Build()
	File_job_distributor_v1_csa_csa_proto = out.File
	file_job_distributor_v1_csa_csa_proto_goTypes = nil
	file_job_distributor_v1_csa_csa_proto_depIdxs = nil
}
