// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: node/v1/node_service.proto

package storage_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactType int32

const (
	ArtifactType_ARTIFACT_TYPE_UNSPECIFIED ArtifactType = 0 // Unspecified artifact type
	ArtifactType_ARTIFACT_TYPE_BINARY      ArtifactType = 1 // Workflow binary artifact
	ArtifactType_ARTIFACT_TYPE_CONFIG      ArtifactType = 2 // Workflow configuration artifact
)

// Enum value maps for ArtifactType.
var (
	ArtifactType_name = map[int32]string{
		0: "ARTIFACT_TYPE_UNSPECIFIED",
		1: "ARTIFACT_TYPE_BINARY",
		2: "ARTIFACT_TYPE_CONFIG",
	}
	ArtifactType_value = map[string]int32{
		"ARTIFACT_TYPE_UNSPECIFIED": 0,
		"ARTIFACT_TYPE_BINARY":      1,
		"ARTIFACT_TYPE_CONFIG":      2,
	}
)

func (x ArtifactType) Enum() *ArtifactType {
	p := new(ArtifactType)
	*p = x
	return p
}

func (x ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_v1_node_service_proto_enumTypes[0].Descriptor()
}

func (ArtifactType) Type() protoreflect.EnumType {
	return &file_node_v1_node_service_proto_enumTypes[0]
}

func (x ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactType.Descriptor instead.
func (ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{0}
}

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED WorkflowStatus = 0 // Unspecified workflow status
	WorkflowStatus_WORKFLOW_STATUS_ACTIVE      WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_PAUSED      WorkflowStatus = 2
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_ACTIVE",
		2: "WORKFLOW_STATUS_PAUSED",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_ACTIVE":      1,
		"WORKFLOW_STATUS_PAUSED":      2,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_node_v1_node_service_proto_enumTypes[1].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_node_v1_node_service_proto_enumTypes[1]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{1}
}

// Identifies which system created/updated the workflow metadata.
type WorkflowManagedBy int32

const (
	WorkflowManagedBy_WORKFLOW_MANAGED_BY_UNSPECIFIED WorkflowManagedBy = 0
	WorkflowManagedBy_WORKFLOW_MANAGED_BY_CLI         WorkflowManagedBy = 1
	WorkflowManagedBy_WORKFLOW_MANAGED_BY_CREC        WorkflowManagedBy = 2
)

// Enum value maps for WorkflowManagedBy.
var (
	WorkflowManagedBy_name = map[int32]string{
		0: "WORKFLOW_MANAGED_BY_UNSPECIFIED",
		1: "WORKFLOW_MANAGED_BY_CLI",
		2: "WORKFLOW_MANAGED_BY_CREC",
	}
	WorkflowManagedBy_value = map[string]int32{
		"WORKFLOW_MANAGED_BY_UNSPECIFIED": 0,
		"WORKFLOW_MANAGED_BY_CLI":         1,
		"WORKFLOW_MANAGED_BY_CREC":        2,
	}
)

func (x WorkflowManagedBy) Enum() *WorkflowManagedBy {
	p := new(WorkflowManagedBy)
	*p = x
	return p
}

func (x WorkflowManagedBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowManagedBy) Descriptor() protoreflect.EnumDescriptor {
	return file_node_v1_node_service_proto_enumTypes[2].Descriptor()
}

func (WorkflowManagedBy) Type() protoreflect.EnumType {
	return &file_node_v1_node_service_proto_enumTypes[2]
}

func (x WorkflowManagedBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowManagedBy.Descriptor instead.
func (WorkflowManagedBy) EnumDescriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{2}
}

// Core workflow metadata
type WorkflowMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId         []byte                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"` // bytes32 - globally unique workflow identifier
	WorkflowName       string                 `protobuf:"bytes,2,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Owner              string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"` // 0x... web3 wallet address or address string derived from org
	OrganizationId     string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DonFamily          string                 `protobuf:"bytes,5,opt,name=don_family,json=donFamily,proto3" json:"don_family,omitempty"` // must be a valid DON family, registered on the Capabilities Registry
	Status             WorkflowStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=node.v1.WorkflowStatus" json:"status,omitempty"`
	ManagedBy          WorkflowManagedBy      `protobuf:"varint,7,opt,name=managed_by,json=managedBy,proto3,enum=node.v1.WorkflowManagedBy" json:"managed_by,omitempty"` // origin of this workflow (CLI, CREC, etc.)
	WorkflowAttributes []byte                 `protobuf:"bytes,8,opt,name=workflow_attributes,json=workflowAttributes,proto3" json:"workflow_attributes,omitempty"`      // custom attributes controlled by the caller (e.g. JSON blob)
	// fields not used but added for compatibility
	BinaryUrl     string `protobuf:"bytes,9,opt,name=binary_url,json=binaryUrl,proto3" json:"binary_url,omitempty"`
	ConfigUrl     string `protobuf:"bytes,10,opt,name=config_url,json=configUrl,proto3" json:"config_url,omitempty"`
	Tags          string `protobuf:"bytes,11,opt,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     uint64 `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowMetadata) Reset() {
	*x = WorkflowMetadata{}
	mi := &file_node_v1_node_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowMetadata) ProtoMessage() {}

func (x *WorkflowMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowMetadata.ProtoReflect.Descriptor instead.
func (*WorkflowMetadata) Descriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowMetadata) GetWorkflowId() []byte {
	if x != nil {
		return x.WorkflowId
	}
	return nil
}

func (x *WorkflowMetadata) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *WorkflowMetadata) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *WorkflowMetadata) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *WorkflowMetadata) GetDonFamily() string {
	if x != nil {
		return x.DonFamily
	}
	return ""
}

func (x *WorkflowMetadata) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowMetadata) GetManagedBy() WorkflowManagedBy {
	if x != nil {
		return x.ManagedBy
	}
	return WorkflowManagedBy_WORKFLOW_MANAGED_BY_UNSPECIFIED
}

func (x *WorkflowMetadata) GetWorkflowAttributes() []byte {
	if x != nil {
		return x.WorkflowAttributes
	}
	return nil
}

func (x *WorkflowMetadata) GetBinaryUrl() string {
	if x != nil {
		return x.BinaryUrl
	}
	return ""
}

func (x *WorkflowMetadata) GetConfigUrl() string {
	if x != nil {
		return x.ConfigUrl
	}
	return ""
}

func (x *WorkflowMetadata) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *WorkflowMetadata) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DownloadArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // ID of the artifact to download
	Type          ArtifactType           `protobuf:"varint,2,opt,name=type,proto3,enum=node.v1.ArtifactType" json:"type,omitempty"` // Type of the artifact to download
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactRequest) Reset() {
	*x = DownloadArtifactRequest{}
	mi := &file_node_v1_node_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactRequest) ProtoMessage() {}

func (x *DownloadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactRequest.ProtoReflect.Descriptor instead.
func (*DownloadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadArtifactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadArtifactRequest) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

type DownloadArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`       // The presigned GET URL for downloading
	Expiry        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"` // Expiration time of the presigned URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactResponse) Reset() {
	*x = DownloadArtifactResponse{}
	mi := &file_node_v1_node_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactResponse) ProtoMessage() {}

func (x *DownloadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactResponse.ProtoReflect.Descriptor instead.
func (*DownloadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadArtifactResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadArtifactResponse) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

type GetWorkflowListByDONCursorRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DonFamily string                 `protobuf:"bytes,1,opt,name=don_family,json=donFamily,proto3" json:"don_family,omitempty"`
	// Max number of workflows to return.
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Cursor: unix timestamp seconds of the last workflow from the previous page.
	// Use 0 for the first page.
	LastWorkflowCreatedAt uint64 `protobuf:"varint,3,opt,name=last_workflow_created_at,json=lastWorkflowCreatedAt,proto3" json:"last_workflow_created_at,omitempty"`
	// Cursor: workflow_id (32 bytes) of the last workflow from the previous page.
	// Use empty for the first page.
	LastWorkflowId []byte `protobuf:"bytes,4,opt,name=last_workflow_id,json=lastWorkflowId,proto3" json:"last_workflow_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWorkflowListByDONCursorRequest) Reset() {
	*x = GetWorkflowListByDONCursorRequest{}
	mi := &file_node_v1_node_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowListByDONCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowListByDONCursorRequest) ProtoMessage() {}

func (x *GetWorkflowListByDONCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowListByDONCursorRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowListByDONCursorRequest) Descriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkflowListByDONCursorRequest) GetDonFamily() string {
	if x != nil {
		return x.DonFamily
	}
	return ""
}

func (x *GetWorkflowListByDONCursorRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWorkflowListByDONCursorRequest) GetLastWorkflowCreatedAt() uint64 {
	if x != nil {
		return x.LastWorkflowCreatedAt
	}
	return 0
}

func (x *GetWorkflowListByDONCursorRequest) GetLastWorkflowId() []byte {
	if x != nil {
		return x.LastWorkflowId
	}
	return nil
}

type GetWorkflowListByDONCursorResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Workflows []*WorkflowMetadata    `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	// Cursor values to request the next page.
	// If workflows is empty, these may be unset/zero.
	NextLastWorkflowCreatedAt uint64 `protobuf:"varint,2,opt,name=next_last_workflow_created_at,json=nextLastWorkflowCreatedAt,proto3" json:"next_last_workflow_created_at,omitempty"`
	NextLastWorkflowId        []byte `protobuf:"bytes,3,opt,name=next_last_workflow_id,json=nextLastWorkflowId,proto3" json:"next_last_workflow_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetWorkflowListByDONCursorResponse) Reset() {
	*x = GetWorkflowListByDONCursorResponse{}
	mi := &file_node_v1_node_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowListByDONCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowListByDONCursorResponse) ProtoMessage() {}

func (x *GetWorkflowListByDONCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowListByDONCursorResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowListByDONCursorResponse) Descriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkflowListByDONCursorResponse) GetWorkflows() []*WorkflowMetadata {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *GetWorkflowListByDONCursorResponse) GetNextLastWorkflowCreatedAt() uint64 {
	if x != nil {
		return x.NextLastWorkflowCreatedAt
	}
	return 0
}

func (x *GetWorkflowListByDONCursorResponse) GetNextLastWorkflowId() []byte {
	if x != nil {
		return x.NextLastWorkflowId
	}
	return nil
}

type GetWorkflowListByDONRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DonFamily string                 `protobuf:"bytes,1,opt,name=don_family,json=donFamily,proto3" json:"don_family,omitempty"`
	// Zero-based offset into the result set.
	Start uint32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// Max number of workflows to return.
	Limit         uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowListByDONRequest) Reset() {
	*x = GetWorkflowListByDONRequest{}
	mi := &file_node_v1_node_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowListByDONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowListByDONRequest) ProtoMessage() {}

func (x *GetWorkflowListByDONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowListByDONRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowListByDONRequest) Descriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkflowListByDONRequest) GetDonFamily() string {
	if x != nil {
		return x.DonFamily
	}
	return ""
}

func (x *GetWorkflowListByDONRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetWorkflowListByDONRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetWorkflowListByDONResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Workflows []*WorkflowMetadata    `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	// Next start offset for the subsequent page.
	NextStart     uint32 `protobuf:"varint,2,opt,name=next_start,json=nextStart,proto3" json:"next_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowListByDONResponse) Reset() {
	*x = GetWorkflowListByDONResponse{}
	mi := &file_node_v1_node_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowListByDONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowListByDONResponse) ProtoMessage() {}

func (x *GetWorkflowListByDONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_v1_node_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowListByDONResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowListByDONResponse) Descriptor() ([]byte, []int) {
	return file_node_v1_node_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkflowListByDONResponse) GetWorkflows() []*WorkflowMetadata {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *GetWorkflowListByDONResponse) GetNextStart() uint32 {
	if x != nil {
		return x.NextStart
	}
	return 0
}

var File_node_v1_node_service_proto protoreflect.FileDescriptor

const file_node_v1_node_service_proto_rawDesc = "" +
	"\n" +
	"\x1anode/v1/node_service.proto\x12\anode.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x03\n" +
	"\x10WorkflowMetadata\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\fR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_name\x18\x02 \x01(\tR\fworkflowName\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"don_family\x18\x05 \x01(\tR\tdonFamily\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.node.v1.WorkflowStatusR\x06status\x129\n" +
	"\n" +
	"managed_by\x18\a \x01(\x0e2\x1a.node.v1.WorkflowManagedByR\tmanagedBy\x12/\n" +
	"\x13workflow_attributes\x18\b \x01(\fR\x12workflowAttributes\x12\x1d\n" +
	"\n" +
	"binary_url\x18\t \x01(\tR\tbinaryUrl\x12\x1d\n" +
	"\n" +
	"config_url\x18\n" +
	" \x01(\tR\tconfigUrl\x12\x12\n" +
	"\x04tags\x18\v \x01(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x04R\tcreatedAt\"T\n" +
	"\x17DownloadArtifactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.node.v1.ArtifactTypeR\x04type\"`\n" +
	"\x18DownloadArtifactResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x122\n" +
	"\x06expiry\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\"\xbb\x01\n" +
	"!GetWorkflowListByDONCursorRequest\x12\x1d\n" +
	"\n" +
	"don_family\x18\x01 \x01(\tR\tdonFamily\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x127\n" +
	"\x18last_workflow_created_at\x18\x03 \x01(\x04R\x15lastWorkflowCreatedAt\x12(\n" +
	"\x10last_workflow_id\x18\x04 \x01(\fR\x0elastWorkflowId\"\xd2\x01\n" +
	"\"GetWorkflowListByDONCursorResponse\x127\n" +
	"\tworkflows\x18\x01 \x03(\v2\x19.node.v1.WorkflowMetadataR\tworkflows\x12@\n" +
	"\x1dnext_last_workflow_created_at\x18\x02 \x01(\x04R\x19nextLastWorkflowCreatedAt\x121\n" +
	"\x15next_last_workflow_id\x18\x03 \x01(\fR\x12nextLastWorkflowId\"h\n" +
	"\x1bGetWorkflowListByDONRequest\x12\x1d\n" +
	"\n" +
	"don_family\x18\x01 \x01(\tR\tdonFamily\x12\x14\n" +
	"\x05start\x18\x02 \x01(\rR\x05start\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"v\n" +
	"\x1cGetWorkflowListByDONResponse\x127\n" +
	"\tworkflows\x18\x01 \x03(\v2\x19.node.v1.WorkflowMetadataR\tworkflows\x12\x1d\n" +
	"\n" +
	"next_start\x18\x02 \x01(\rR\tnextStart*a\n" +
	"\fArtifactType\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ARTIFACT_TYPE_BINARY\x10\x01\x12\x18\n" +
	"\x14ARTIFACT_TYPE_CONFIG\x10\x02*i\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_PAUSED\x10\x02*s\n" +
	"\x11WorkflowManagedBy\x12#\n" +
	"\x1fWORKFLOW_MANAGED_BY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_MANAGED_BY_CLI\x10\x01\x12\x1c\n" +
	"\x18WORKFLOW_MANAGED_BY_CREC\x10\x022\xc2\x02\n" +
	"\vNodeService\x12W\n" +
	"\x10DownloadArtifact\x12 .node.v1.DownloadArtifactRequest\x1a!.node.v1.DownloadArtifactResponse\x12u\n" +
	"\x1aGetWorkflowListByDONCursor\x12*.node.v1.GetWorkflowListByDONCursorRequest\x1a+.node.v1.GetWorkflowListByDONCursorResponse\x12c\n" +
	"\x14GetWorkflowListByDON\x12$.node.v1.GetWorkflowListByDONRequest\x1a%.node.v1.GetWorkflowListByDONResponseBQZOgithub.com/smartcontractkit/chainlink-protos/storage-service/go;storage_serviceb\x06proto3"

var (
	file_node_v1_node_service_proto_rawDescOnce sync.Once
	file_node_v1_node_service_proto_rawDescData []byte
)

func file_node_v1_node_service_proto_rawDescGZIP() []byte {
	file_node_v1_node_service_proto_rawDescOnce.Do(func() {
		file_node_v1_node_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_v1_node_service_proto_rawDesc), len(file_node_v1_node_service_proto_rawDesc)))
	})
	return file_node_v1_node_service_proto_rawDescData
}

var file_node_v1_node_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_node_v1_node_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_node_v1_node_service_proto_goTypes = []any{
	(ArtifactType)(0),                          // 0: node.v1.ArtifactType
	(WorkflowStatus)(0),                        // 1: node.v1.WorkflowStatus
	(WorkflowManagedBy)(0),                     // 2: node.v1.WorkflowManagedBy
	(*WorkflowMetadata)(nil),                   // 3: node.v1.WorkflowMetadata
	(*DownloadArtifactRequest)(nil),            // 4: node.v1.DownloadArtifactRequest
	(*DownloadArtifactResponse)(nil),           // 5: node.v1.DownloadArtifactResponse
	(*GetWorkflowListByDONCursorRequest)(nil),  // 6: node.v1.GetWorkflowListByDONCursorRequest
	(*GetWorkflowListByDONCursorResponse)(nil), // 7: node.v1.GetWorkflowListByDONCursorResponse
	(*GetWorkflowListByDONRequest)(nil),        // 8: node.v1.GetWorkflowListByDONRequest
	(*GetWorkflowListByDONResponse)(nil),       // 9: node.v1.GetWorkflowListByDONResponse
	(*timestamppb.Timestamp)(nil),              // 10: google.protobuf.Timestamp
}
var file_node_v1_node_service_proto_depIdxs = []int32{
	1,  // 0: node.v1.WorkflowMetadata.status:type_name -> node.v1.WorkflowStatus
	2,  // 1: node.v1.WorkflowMetadata.managed_by:type_name -> node.v1.WorkflowManagedBy
	0,  // 2: node.v1.DownloadArtifactRequest.type:type_name -> node.v1.ArtifactType
	10, // 3: node.v1.DownloadArtifactResponse.expiry:type_name -> google.protobuf.Timestamp
	3,  // 4: node.v1.GetWorkflowListByDONCursorResponse.workflows:type_name -> node.v1.WorkflowMetadata
	3,  // 5: node.v1.GetWorkflowListByDONResponse.workflows:type_name -> node.v1.WorkflowMetadata
	4,  // 6: node.v1.NodeService.DownloadArtifact:input_type -> node.v1.DownloadArtifactRequest
	6,  // 7: node.v1.NodeService.GetWorkflowListByDONCursor:input_type -> node.v1.GetWorkflowListByDONCursorRequest
	8,  // 8: node.v1.NodeService.GetWorkflowListByDON:input_type -> node.v1.GetWorkflowListByDONRequest
	5,  // 9: node.v1.NodeService.DownloadArtifact:output_type -> node.v1.DownloadArtifactResponse
	7,  // 10: node.v1.NodeService.GetWorkflowListByDONCursor:output_type -> node.v1.GetWorkflowListByDONCursorResponse
	9,  // 11: node.v1.NodeService.GetWorkflowListByDON:output_type -> node.v1.GetWorkflowListByDONResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_node_v1_node_service_proto_init() }
func file_node_v1_node_service_proto_init() {
	if File_node_v1_node_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_v1_node_service_proto_rawDesc), len(file_node_v1_node_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_v1_node_service_proto_goTypes,
		DependencyIndexes: file_node_v1_node_service_proto_depIdxs,
		EnumInfos:         file_node_v1_node_service_proto_enumTypes,
		MessageInfos:      file_node_v1_node_service_proto_msgTypes,
	}.Build()
	File_node_v1_node_service_proto = out.File
	file_node_v1_node_service_proto_goTypes = nil
	file_node_v1_node_service_proto_depIdxs = nil
}
