// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: node_service/v1/node_service.proto

package storage_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactType int32

const (
	ArtifactType_ARTIFACT_TYPE_UNSPECIFIED ArtifactType = 0 // Unspecified artifact type
	ArtifactType_ARTIFACT_TYPE_BINARY      ArtifactType = 1 // Workflow binary artifact
	ArtifactType_ARTIFACT_TYPE_CONFIG      ArtifactType = 2 // Workflow configuration artifact
)

// Enum value maps for ArtifactType.
var (
	ArtifactType_name = map[int32]string{
		0: "ARTIFACT_TYPE_UNSPECIFIED",
		1: "ARTIFACT_TYPE_BINARY",
		2: "ARTIFACT_TYPE_CONFIG",
	}
	ArtifactType_value = map[string]int32{
		"ARTIFACT_TYPE_UNSPECIFIED": 0,
		"ARTIFACT_TYPE_BINARY":      1,
		"ARTIFACT_TYPE_CONFIG":      2,
	}
)

func (x ArtifactType) Enum() *ArtifactType {
	p := new(ArtifactType)
	*p = x
	return p
}

func (x ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_service_v1_node_service_proto_enumTypes[0].Descriptor()
}

func (ArtifactType) Type() protoreflect.EnumType {
	return &file_node_service_v1_node_service_proto_enumTypes[0]
}

func (x ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactType.Descriptor instead.
func (ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_node_service_v1_node_service_proto_rawDescGZIP(), []int{0}
}

// environment indicates which Workflow Registry to use
type EnvironmentName int32

const (
	EnvironmentName_ENVIRONMENT_NAME_UNSPECIFIED EnvironmentName = 0 // Unspecified environment
	EnvironmentName_PRODUCTION_MAINNET           EnvironmentName = 1
	EnvironmentName_PRODUCTION_TESTNET           EnvironmentName = 2
)

// Enum value maps for EnvironmentName.
var (
	EnvironmentName_name = map[int32]string{
		0: "ENVIRONMENT_NAME_UNSPECIFIED",
		1: "PRODUCTION_MAINNET",
		2: "PRODUCTION_TESTNET",
	}
	EnvironmentName_value = map[string]int32{
		"ENVIRONMENT_NAME_UNSPECIFIED": 0,
		"PRODUCTION_MAINNET":           1,
		"PRODUCTION_TESTNET":           2,
	}
)

func (x EnvironmentName) Enum() *EnvironmentName {
	p := new(EnvironmentName)
	*p = x
	return p
}

func (x EnvironmentName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvironmentName) Descriptor() protoreflect.EnumDescriptor {
	return file_node_service_v1_node_service_proto_enumTypes[1].Descriptor()
}

func (EnvironmentName) Type() protoreflect.EnumType {
	return &file_node_service_v1_node_service_proto_enumTypes[1]
}

func (x EnvironmentName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvironmentName.Descriptor instead.
func (EnvironmentName) EnumDescriptor() ([]byte, []int) {
	return file_node_service_v1_node_service_proto_rawDescGZIP(), []int{1}
}

type DownloadArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                         // ID of the artifact to download
	Type          ArtifactType           `protobuf:"varint,2,opt,name=type,proto3,enum=node_service.v1.ArtifactType" json:"type,omitempty"`                  // Type of the artifact to download
	Environment   EnvironmentName        `protobuf:"varint,3,opt,name=environment,proto3,enum=node_service.v1.EnvironmentName" json:"environment,omitempty"` // Environment of the artifact to download
	ChunkSize     int32                  `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`                         // Optional: chunk size in bytes (default 1MB if not set)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactRequest) Reset() {
	*x = DownloadArtifactRequest{}
	mi := &file_node_service_v1_node_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactRequest) ProtoMessage() {}

func (x *DownloadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_v1_node_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactRequest.ProtoReflect.Descriptor instead.
func (*DownloadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_node_service_v1_node_service_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadArtifactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadArtifactRequest) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *DownloadArtifactRequest) GetEnvironment() EnvironmentName {
	if x != nil {
		return x.Environment
	}
	return EnvironmentName_ENVIRONMENT_NAME_UNSPECIFIED
}

func (x *DownloadArtifactRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type DownloadArtifactChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *WorkflowArtifact      `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`                             // Only sent in the first chunk
	ContentChunk  []byte                 `protobuf:"bytes,2,opt,name=content_chunk,json=contentChunk,proto3" json:"content_chunk,omitempty"` // The chunk of file content
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                // Offset of this chunk in the file
	LastChunk     bool                   `protobuf:"varint,4,opt,name=last_chunk,json=lastChunk,proto3" json:"last_chunk,omitempty"`         // True if this is the last chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactChunk) Reset() {
	*x = DownloadArtifactChunk{}
	mi := &file_node_service_v1_node_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactChunk) ProtoMessage() {}

func (x *DownloadArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_v1_node_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactChunk.ProtoReflect.Descriptor instead.
func (*DownloadArtifactChunk) Descriptor() ([]byte, []int) {
	return file_node_service_v1_node_service_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadArtifactChunk) GetArtifact() *WorkflowArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *DownloadArtifactChunk) GetContentChunk() []byte {
	if x != nil {
		return x.ContentChunk
	}
	return nil
}

func (x *DownloadArtifactChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadArtifactChunk) GetLastChunk() bool {
	if x != nil {
		return x.LastChunk
	}
	return false
}

type WorkflowArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                         // Unique workflow ID for the artifact
	Type          ArtifactType           `protobuf:"varint,2,opt,name=type,proto3,enum=node_service.v1.ArtifactType" json:"type,omitempty"`                  // Type of the artifact
	Environment   EnvironmentName        `protobuf:"varint,3,opt,name=environment,proto3,enum=node_service.v1.EnvironmentName" json:"environment,omitempty"` // Environment where the artifact is stored
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowArtifact) Reset() {
	*x = WorkflowArtifact{}
	mi := &file_node_service_v1_node_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowArtifact) ProtoMessage() {}

func (x *WorkflowArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_node_service_v1_node_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowArtifact.ProtoReflect.Descriptor instead.
func (*WorkflowArtifact) Descriptor() ([]byte, []int) {
	return file_node_service_v1_node_service_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowArtifact) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *WorkflowArtifact) GetEnvironment() EnvironmentName {
	if x != nil {
		return x.Environment
	}
	return EnvironmentName_ENVIRONMENT_NAME_UNSPECIFIED
}

var File_node_service_v1_node_service_proto protoreflect.FileDescriptor

const file_node_service_v1_node_service_proto_rawDesc = "" +
	"\n" +
	"\"node_service/v1/node_service.proto\x12\x0fnode_service.v1\"\xbf\x01\n" +
	"\x17DownloadArtifactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.node_service.v1.ArtifactTypeR\x04type\x12B\n" +
	"\venvironment\x18\x03 \x01(\x0e2 .node_service.v1.EnvironmentNameR\venvironment\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\x05R\tchunkSize\"\xb2\x01\n" +
	"\x15DownloadArtifactChunk\x12=\n" +
	"\bartifact\x18\x01 \x01(\v2!.node_service.v1.WorkflowArtifactR\bartifact\x12#\n" +
	"\rcontent_chunk\x18\x02 \x01(\fR\fcontentChunk\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"last_chunk\x18\x04 \x01(\bR\tlastChunk\"\x99\x01\n" +
	"\x10WorkflowArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.node_service.v1.ArtifactTypeR\x04type\x12B\n" +
	"\venvironment\x18\x03 \x01(\x0e2 .node_service.v1.EnvironmentNameR\venvironment*a\n" +
	"\fArtifactType\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ARTIFACT_TYPE_BINARY\x10\x01\x12\x18\n" +
	"\x14ARTIFACT_TYPE_CONFIG\x10\x02*c\n" +
	"\x0fEnvironmentName\x12 \n" +
	"\x1cENVIRONMENT_NAME_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PRODUCTION_MAINNET\x10\x01\x12\x16\n" +
	"\x12PRODUCTION_TESTNET\x10\x022u\n" +
	"\vNodeService\x12f\n" +
	"\x10DownloadArtifact\x12(.node_service.v1.DownloadArtifactRequest\x1a&.node_service.v1.DownloadArtifactChunk0\x01BQZOgithub.com/smartcontractkit/chainlink-protos/storage-service/go;storage_serviceb\x06proto3"

var (
	file_node_service_v1_node_service_proto_rawDescOnce sync.Once
	file_node_service_v1_node_service_proto_rawDescData []byte
)

func file_node_service_v1_node_service_proto_rawDescGZIP() []byte {
	file_node_service_v1_node_service_proto_rawDescOnce.Do(func() {
		file_node_service_v1_node_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_service_v1_node_service_proto_rawDesc), len(file_node_service_v1_node_service_proto_rawDesc)))
	})
	return file_node_service_v1_node_service_proto_rawDescData
}

var file_node_service_v1_node_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_node_service_v1_node_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_service_v1_node_service_proto_goTypes = []any{
	(ArtifactType)(0),               // 0: node_service.v1.ArtifactType
	(EnvironmentName)(0),            // 1: node_service.v1.EnvironmentName
	(*DownloadArtifactRequest)(nil), // 2: node_service.v1.DownloadArtifactRequest
	(*DownloadArtifactChunk)(nil),   // 3: node_service.v1.DownloadArtifactChunk
	(*WorkflowArtifact)(nil),        // 4: node_service.v1.WorkflowArtifact
}
var file_node_service_v1_node_service_proto_depIdxs = []int32{
	0, // 0: node_service.v1.DownloadArtifactRequest.type:type_name -> node_service.v1.ArtifactType
	1, // 1: node_service.v1.DownloadArtifactRequest.environment:type_name -> node_service.v1.EnvironmentName
	4, // 2: node_service.v1.DownloadArtifactChunk.artifact:type_name -> node_service.v1.WorkflowArtifact
	0, // 3: node_service.v1.WorkflowArtifact.type:type_name -> node_service.v1.ArtifactType
	1, // 4: node_service.v1.WorkflowArtifact.environment:type_name -> node_service.v1.EnvironmentName
	2, // 5: node_service.v1.NodeService.DownloadArtifact:input_type -> node_service.v1.DownloadArtifactRequest
	3, // 6: node_service.v1.NodeService.DownloadArtifact:output_type -> node_service.v1.DownloadArtifactChunk
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_node_service_v1_node_service_proto_init() }
func file_node_service_v1_node_service_proto_init() {
	if File_node_service_v1_node_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_service_v1_node_service_proto_rawDesc), len(file_node_service_v1_node_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_service_v1_node_service_proto_goTypes,
		DependencyIndexes: file_node_service_v1_node_service_proto_depIdxs,
		EnumInfos:         file_node_service_v1_node_service_proto_enumTypes,
		MessageInfos:      file_node_service_v1_node_service_proto_msgTypes,
	}.Build()
	File_node_service_v1_node_service_proto = out.File
	file_node_service_v1_node_service_proto_goTypes = nil
	file_node_service_v1_node_service_proto_depIdxs = nil
}
