// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryNetworkClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*BinaryNetworkClientRequest_NewEndpoint
	//	*BinaryNetworkClientRequest_SendTo
	//	*BinaryNetworkClientRequest_Broadcast
	Message       isBinaryNetworkClientRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryNetworkClientRequest) Reset() {
	*x = BinaryNetworkClientRequest{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryNetworkClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryNetworkClientRequest) ProtoMessage() {}

func (x *BinaryNetworkClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryNetworkClientRequest.ProtoReflect.Descriptor instead.
func (*BinaryNetworkClientRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryNetworkClientRequest) GetMessage() isBinaryNetworkClientRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *BinaryNetworkClientRequest) GetNewEndpoint() *NewEndpointRequest {
	if x != nil {
		if x, ok := x.Message.(*BinaryNetworkClientRequest_NewEndpoint); ok {
			return x.NewEndpoint
		}
	}
	return nil
}

func (x *BinaryNetworkClientRequest) GetSendTo() *SendToRequest {
	if x != nil {
		if x, ok := x.Message.(*BinaryNetworkClientRequest_SendTo); ok {
			return x.SendTo
		}
	}
	return nil
}

func (x *BinaryNetworkClientRequest) GetBroadcast() []byte {
	if x != nil {
		if x, ok := x.Message.(*BinaryNetworkClientRequest_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

type isBinaryNetworkClientRequest_Message interface {
	isBinaryNetworkClientRequest_Message()
}

type BinaryNetworkClientRequest_NewEndpoint struct {
	NewEndpoint *NewEndpointRequest `protobuf:"bytes,1,opt,name=newEndpoint,proto3,oneof"`
}

type BinaryNetworkClientRequest_SendTo struct {
	SendTo *SendToRequest `protobuf:"bytes,2,opt,name=sendTo,proto3,oneof"`
}

type BinaryNetworkClientRequest_Broadcast struct {
	Broadcast []byte `protobuf:"bytes,3,opt,name=broadcast,proto3,oneof"`
}

func (*BinaryNetworkClientRequest_NewEndpoint) isBinaryNetworkClientRequest_Message() {}

func (*BinaryNetworkClientRequest_SendTo) isBinaryNetworkClientRequest_Message() {}

func (*BinaryNetworkClientRequest_Broadcast) isBinaryNetworkClientRequest_Message() {}

type NewEndpointRequest struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	ConfigDigest     []byte                       `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	PeerIds          []string                     `protobuf:"bytes,2,rep,name=peer_ids,json=peerIds,proto3" json:"peer_ids,omitempty"`
	V2Bootstrappers  []*BootstrapperLocator       `protobuf:"bytes,3,rep,name=v2_bootstrappers,json=v2Bootstrappers,proto3" json:"v2_bootstrappers,omitempty"`
	FailureThreshold int32                        `protobuf:"varint,4,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	Limits           *BinaryNetworkEndpointLimits `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NewEndpointRequest) Reset() {
	*x = NewEndpointRequest{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEndpointRequest) ProtoMessage() {}

func (x *NewEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEndpointRequest.ProtoReflect.Descriptor instead.
func (*NewEndpointRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *NewEndpointRequest) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *NewEndpointRequest) GetPeerIds() []string {
	if x != nil {
		return x.PeerIds
	}
	return nil
}

func (x *NewEndpointRequest) GetV2Bootstrappers() []*BootstrapperLocator {
	if x != nil {
		return x.V2Bootstrappers
	}
	return nil
}

func (x *NewEndpointRequest) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *NewEndpointRequest) GetLimits() *BinaryNetworkEndpointLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type BootstrapperLocator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapperLocator) Reset() {
	*x = BootstrapperLocator{}
	mi := &file_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapperLocator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapperLocator) ProtoMessage() {}

func (x *BootstrapperLocator) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapperLocator.ProtoReflect.Descriptor instead.
func (*BootstrapperLocator) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *BootstrapperLocator) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *BootstrapperLocator) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type BinaryNetworkEndpointLimits struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	MaxMessageLength          int32                  `protobuf:"varint,1,opt,name=max_message_length,json=maxMessageLength,proto3" json:"max_message_length,omitempty"`
	MessagesRatePerOracle     float64                `protobuf:"fixed64,2,opt,name=messages_rate_per_oracle,json=messagesRatePerOracle,proto3" json:"messages_rate_per_oracle,omitempty"`
	MessagesCapacityPerOracle int32                  `protobuf:"varint,3,opt,name=messages_capacity_per_oracle,json=messagesCapacityPerOracle,proto3" json:"messages_capacity_per_oracle,omitempty"`
	BytesRatePerOracle        float64                `protobuf:"fixed64,4,opt,name=bytes_rate_per_oracle,json=bytesRatePerOracle,proto3" json:"bytes_rate_per_oracle,omitempty"`
	BytesCapacityPerOracle    int32                  `protobuf:"varint,5,opt,name=bytes_capacity_per_oracle,json=bytesCapacityPerOracle,proto3" json:"bytes_capacity_per_oracle,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *BinaryNetworkEndpointLimits) Reset() {
	*x = BinaryNetworkEndpointLimits{}
	mi := &file_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryNetworkEndpointLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryNetworkEndpointLimits) ProtoMessage() {}

func (x *BinaryNetworkEndpointLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryNetworkEndpointLimits.ProtoReflect.Descriptor instead.
func (*BinaryNetworkEndpointLimits) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *BinaryNetworkEndpointLimits) GetMaxMessageLength() int32 {
	if x != nil {
		return x.MaxMessageLength
	}
	return 0
}

func (x *BinaryNetworkEndpointLimits) GetMessagesRatePerOracle() float64 {
	if x != nil {
		return x.MessagesRatePerOracle
	}
	return 0
}

func (x *BinaryNetworkEndpointLimits) GetMessagesCapacityPerOracle() int32 {
	if x != nil {
		return x.MessagesCapacityPerOracle
	}
	return 0
}

func (x *BinaryNetworkEndpointLimits) GetBytesRatePerOracle() float64 {
	if x != nil {
		return x.BytesRatePerOracle
	}
	return 0
}

func (x *BinaryNetworkEndpointLimits) GetBytesCapacityPerOracle() int32 {
	if x != nil {
		return x.BytesCapacityPerOracle
	}
	return 0
}

type SendToRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ToOracleId    uint32                 `protobuf:"varint,3,opt,name=to_oracle_id,json=toOracleId,proto3" json:"to_oracle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToRequest) Reset() {
	*x = SendToRequest{}
	mi := &file_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToRequest) ProtoMessage() {}

func (x *SendToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToRequest.ProtoReflect.Descriptor instead.
func (*SendToRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *SendToRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendToRequest) GetToOracleId() uint32 {
	if x != nil {
		return x.ToOracleId
	}
	return 0
}

type BinaryMessageWithSender struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           []byte                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Sender        uint32                 `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryMessageWithSender) Reset() {
	*x = BinaryMessageWithSender{}
	mi := &file_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryMessageWithSender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryMessageWithSender) ProtoMessage() {}

func (x *BinaryMessageWithSender) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryMessageWithSender.ProtoReflect.Descriptor instead.
func (*BinaryMessageWithSender) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *BinaryMessageWithSender) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *BinaryMessageWithSender) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

type Endpoint2ClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Endpoint2ClientRequest_NewEndpoint
	//	*Endpoint2ClientRequest_SendTo
	//	*Endpoint2ClientRequest_Broadcast
	Message       isEndpoint2ClientRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint2ClientRequest) Reset() {
	*x = Endpoint2ClientRequest{}
	mi := &file_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint2ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint2ClientRequest) ProtoMessage() {}

func (x *Endpoint2ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint2ClientRequest.ProtoReflect.Descriptor instead.
func (*Endpoint2ClientRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *Endpoint2ClientRequest) GetMessage() isEndpoint2ClientRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Endpoint2ClientRequest) GetNewEndpoint() *NewEndpoint2Request {
	if x != nil {
		if x, ok := x.Message.(*Endpoint2ClientRequest_NewEndpoint); ok {
			return x.NewEndpoint
		}
	}
	return nil
}

func (x *Endpoint2ClientRequest) GetSendTo() *Endpoint2Send {
	if x != nil {
		if x, ok := x.Message.(*Endpoint2ClientRequest_SendTo); ok {
			return x.SendTo
		}
	}
	return nil
}

func (x *Endpoint2ClientRequest) GetBroadcast() *Endpoint2Send {
	if x != nil {
		if x, ok := x.Message.(*Endpoint2ClientRequest_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

type isEndpoint2ClientRequest_Message interface {
	isEndpoint2ClientRequest_Message()
}

type Endpoint2ClientRequest_NewEndpoint struct {
	NewEndpoint *NewEndpoint2Request `protobuf:"bytes,1,opt,name=new_endpoint,json=newEndpoint,proto3,oneof"` // must be the first message
}

type Endpoint2ClientRequest_SendTo struct {
	SendTo *Endpoint2Send `protobuf:"bytes,2,opt,name=send_to,json=sendTo,proto3,oneof"`
}

type Endpoint2ClientRequest_Broadcast struct {
	Broadcast *Endpoint2Send `protobuf:"bytes,3,opt,name=broadcast,proto3,oneof"` // to_oracle_id is ignored
}

func (*Endpoint2ClientRequest_NewEndpoint) isEndpoint2ClientRequest_Message() {}

func (*Endpoint2ClientRequest_SendTo) isEndpoint2ClientRequest_Message() {}

func (*Endpoint2ClientRequest_Broadcast) isEndpoint2ClientRequest_Message() {}

type NewEndpoint2Request struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest          []byte                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	PeerIds               []string               `protobuf:"bytes,2,rep,name=peer_ids,json=peerIds,proto3" json:"peer_ids,omitempty"`
	V2Bootstrappers       []*BootstrapperLocator `protobuf:"bytes,3,rep,name=v2_bootstrappers,json=v2Bootstrappers,proto3" json:"v2_bootstrappers,omitempty"`
	DefaultPriorityConfig *Endpoint2Config       `protobuf:"bytes,4,opt,name=default_priority_config,json=defaultPriorityConfig,proto3" json:"default_priority_config,omitempty"`
	LowPriorityConfig     *Endpoint2Config       `protobuf:"bytes,5,opt,name=low_priority_config,json=lowPriorityConfig,proto3" json:"low_priority_config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NewEndpoint2Request) Reset() {
	*x = NewEndpoint2Request{}
	mi := &file_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewEndpoint2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEndpoint2Request) ProtoMessage() {}

func (x *NewEndpoint2Request) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEndpoint2Request.ProtoReflect.Descriptor instead.
func (*NewEndpoint2Request) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *NewEndpoint2Request) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *NewEndpoint2Request) GetPeerIds() []string {
	if x != nil {
		return x.PeerIds
	}
	return nil
}

func (x *NewEndpoint2Request) GetV2Bootstrappers() []*BootstrapperLocator {
	if x != nil {
		return x.V2Bootstrappers
	}
	return nil
}

func (x *NewEndpoint2Request) GetDefaultPriorityConfig() *Endpoint2Config {
	if x != nil {
		return x.DefaultPriorityConfig
	}
	return nil
}

func (x *NewEndpoint2Request) GetLowPriorityConfig() *Endpoint2Config {
	if x != nil {
		return x.LowPriorityConfig
	}
	return nil
}

// Endpoint2Config mirrors ocr2types.BinaryNetworkEndpoint2Config.
type Endpoint2Config struct {
	state                             protoimpl.MessageState       `protogen:"open.v1"`
	Limits                            *BinaryNetworkEndpointLimits `protobuf:"bytes,1,opt,name=limits,proto3" json:"limits,omitempty"`
	OverrideIncomingMessageBufferSize *int32                       `protobuf:"varint,2,opt,name=override_incoming_message_buffer_size,json=overrideIncomingMessageBufferSize,proto3,oneof" json:"override_incoming_message_buffer_size,omitempty"`
	OverrideOutgoingMessageBufferSize *int32                       `protobuf:"varint,3,opt,name=override_outgoing_message_buffer_size,json=overrideOutgoingMessageBufferSize,proto3,oneof" json:"override_outgoing_message_buffer_size,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Endpoint2Config) Reset() {
	*x = Endpoint2Config{}
	mi := &file_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint2Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint2Config) ProtoMessage() {}

func (x *Endpoint2Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint2Config.ProtoReflect.Descriptor instead.
func (*Endpoint2Config) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *Endpoint2Config) GetLimits() *BinaryNetworkEndpointLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Endpoint2Config) GetOverrideIncomingMessageBufferSize() int32 {
	if x != nil && x.OverrideIncomingMessageBufferSize != nil {
		return *x.OverrideIncomingMessageBufferSize
	}
	return 0
}

func (x *Endpoint2Config) GetOverrideOutgoingMessageBufferSize() int32 {
	if x != nil && x.OverrideOutgoingMessageBufferSize != nil {
		return *x.OverrideOutgoingMessageBufferSize
	}
	return 0
}

type Endpoint2Send struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToOracleId    uint32                 `protobuf:"varint,1,opt,name=to_oracle_id,json=toOracleId,proto3" json:"to_oracle_id,omitempty"`
	Msg           *OutboundMessage2      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint2Send) Reset() {
	*x = Endpoint2Send{}
	mi := &file_proxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint2Send) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint2Send) ProtoMessage() {}

func (x *Endpoint2Send) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint2Send.ProtoReflect.Descriptor instead.
func (*Endpoint2Send) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *Endpoint2Send) GetToOracleId() uint32 {
	if x != nil {
		return x.ToOracleId
	}
	return 0
}

func (x *Endpoint2Send) GetMsg() *OutboundMessage2 {
	if x != nil {
		return x.Msg
	}
	return nil
}

// OutboundMessage2 mirrors ocr2types.OutboundBinaryMessage (plain/request/response).
type OutboundMessage2 struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Payload  []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority uint32                 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"` // raw ocr2types.BinaryMessageOutboundPriority value
	// Types that are valid to be assigned to Kind:
	//
	//	*OutboundMessage2_Plain
	//	*OutboundMessage2_Request
	//	*OutboundMessage2_Response
	Kind          isOutboundMessage2_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundMessage2) Reset() {
	*x = OutboundMessage2{}
	mi := &file_proxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundMessage2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage2) ProtoMessage() {}

func (x *OutboundMessage2) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage2.ProtoReflect.Descriptor instead.
func (*OutboundMessage2) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *OutboundMessage2) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OutboundMessage2) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *OutboundMessage2) GetKind() isOutboundMessage2_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *OutboundMessage2) GetPlain() *OutboundPlain2 {
	if x != nil {
		if x, ok := x.Kind.(*OutboundMessage2_Plain); ok {
			return x.Plain
		}
	}
	return nil
}

func (x *OutboundMessage2) GetRequest() *OutboundRequest2 {
	if x != nil {
		if x, ok := x.Kind.(*OutboundMessage2_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *OutboundMessage2) GetResponse() *OutboundResponse2 {
	if x != nil {
		if x, ok := x.Kind.(*OutboundMessage2_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isOutboundMessage2_Kind interface {
	isOutboundMessage2_Kind()
}

type OutboundMessage2_Plain struct {
	Plain *OutboundPlain2 `protobuf:"bytes,3,opt,name=plain,proto3,oneof"`
}

type OutboundMessage2_Request struct {
	Request *OutboundRequest2 `protobuf:"bytes,4,opt,name=request,proto3,oneof"`
}

type OutboundMessage2_Response struct {
	Response *OutboundResponse2 `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

func (*OutboundMessage2_Plain) isOutboundMessage2_Kind() {}

func (*OutboundMessage2_Request) isOutboundMessage2_Kind() {}

func (*OutboundMessage2_Response) isOutboundMessage2_Kind() {}

type OutboundPlain2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundPlain2) Reset() {
	*x = OutboundPlain2{}
	mi := &file_proxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundPlain2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundPlain2) ProtoMessage() {}

func (x *OutboundPlain2) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundPlain2.ProtoReflect.Descriptor instead.
func (*OutboundPlain2) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{11}
}

type OutboundRequest2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SingleUseSizedLimitedResponsePolicy fields.
	PolicyMaxSize      int64 `protobuf:"varint,1,opt,name=policy_max_size,json=policyMaxSize,proto3" json:"policy_max_size,omitempty"`
	PolicyExpiryUnixMs int64 `protobuf:"varint,2,opt,name=policy_expiry_unix_ms,json=policyExpiryUnixMs,proto3" json:"policy_expiry_unix_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OutboundRequest2) Reset() {
	*x = OutboundRequest2{}
	mi := &file_proxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundRequest2) ProtoMessage() {}

func (x *OutboundRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundRequest2.ProtoReflect.Descriptor instead.
func (*OutboundRequest2) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{12}
}

func (x *OutboundRequest2) GetPolicyMaxSize() int64 {
	if x != nil {
		return x.PolicyMaxSize
	}
	return 0
}

func (x *OutboundRequest2) GetPolicyExpiryUnixMs() int64 {
	if x != nil {
		return x.PolicyExpiryUnixMs
	}
	return 0
}

type OutboundResponse2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Refers to the request_id of the InboundRequest2 being responded to; the
	// server holds the real libocr RequestHandle keyed by this id.
	RequestId     uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundResponse2) Reset() {
	*x = OutboundResponse2{}
	mi := &file_proxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundResponse2) ProtoMessage() {}

func (x *OutboundResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundResponse2.ProtoReflect.Descriptor instead.
func (*OutboundResponse2) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{13}
}

func (x *OutboundResponse2) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// Endpoint2ServerMessage mirrors ocr2types.InboundBinaryMessageWithSender.
type Endpoint2ServerMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sender   uint32                 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Payload  []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority uint32                 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // raw ocr2types.BinaryMessageOutboundPriority value
	// Types that are valid to be assigned to Kind:
	//
	//	*Endpoint2ServerMessage_Plain
	//	*Endpoint2ServerMessage_Request
	//	*Endpoint2ServerMessage_Response
	Kind          isEndpoint2ServerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint2ServerMessage) Reset() {
	*x = Endpoint2ServerMessage{}
	mi := &file_proxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint2ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint2ServerMessage) ProtoMessage() {}

func (x *Endpoint2ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint2ServerMessage.ProtoReflect.Descriptor instead.
func (*Endpoint2ServerMessage) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{14}
}

func (x *Endpoint2ServerMessage) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *Endpoint2ServerMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Endpoint2ServerMessage) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Endpoint2ServerMessage) GetKind() isEndpoint2ServerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Endpoint2ServerMessage) GetPlain() *InboundPlain2 {
	if x != nil {
		if x, ok := x.Kind.(*Endpoint2ServerMessage_Plain); ok {
			return x.Plain
		}
	}
	return nil
}

func (x *Endpoint2ServerMessage) GetRequest() *InboundRequest2 {
	if x != nil {
		if x, ok := x.Kind.(*Endpoint2ServerMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Endpoint2ServerMessage) GetResponse() *InboundResponse2 {
	if x != nil {
		if x, ok := x.Kind.(*Endpoint2ServerMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isEndpoint2ServerMessage_Kind interface {
	isEndpoint2ServerMessage_Kind()
}

type Endpoint2ServerMessage_Plain struct {
	Plain *InboundPlain2 `protobuf:"bytes,4,opt,name=plain,proto3,oneof"`
}

type Endpoint2ServerMessage_Request struct {
	Request *InboundRequest2 `protobuf:"bytes,5,opt,name=request,proto3,oneof"`
}

type Endpoint2ServerMessage_Response struct {
	Response *InboundResponse2 `protobuf:"bytes,6,opt,name=response,proto3,oneof"`
}

func (*Endpoint2ServerMessage_Plain) isEndpoint2ServerMessage_Kind() {}

func (*Endpoint2ServerMessage_Request) isEndpoint2ServerMessage_Kind() {}

func (*Endpoint2ServerMessage_Response) isEndpoint2ServerMessage_Kind() {}

type InboundPlain2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundPlain2) Reset() {
	*x = InboundPlain2{}
	mi := &file_proxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundPlain2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundPlain2) ProtoMessage() {}

func (x *InboundPlain2) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundPlain2.ProtoReflect.Descriptor instead.
func (*InboundPlain2) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{15}
}

type InboundRequest2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundRequest2) Reset() {
	*x = InboundRequest2{}
	mi := &file_proxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundRequest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundRequest2) ProtoMessage() {}

func (x *InboundRequest2) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundRequest2.ProtoReflect.Descriptor instead.
func (*InboundRequest2) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{16}
}

func (x *InboundRequest2) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type InboundResponse2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundResponse2) Reset() {
	*x = InboundResponse2{}
	mi := &file_proxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundResponse2) ProtoMessage() {}

func (x *InboundResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundResponse2.ProtoReflect.Descriptor instead.
func (*InboundResponse2) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{17}
}

type KeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysRequest) Reset() {
	*x = KeysRequest{}
	mi := &file_proxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRequest) ProtoMessage() {}

func (x *KeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRequest.ProtoReflect.Descriptor instead.
func (*KeysRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{18}
}

type KeysReply struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	OffchainPublicKey         []byte                 `protobuf:"bytes,1,opt,name=offchain_public_key,json=offchainPublicKey,proto3" json:"offchain_public_key,omitempty"`
	ConfigEncryptionPublicKey []byte                 `protobuf:"bytes,2,opt,name=config_encryption_public_key,json=configEncryptionPublicKey,proto3" json:"config_encryption_public_key,omitempty"`
	OnchainPublicKey          []byte                 `protobuf:"bytes,3,opt,name=onchain_public_key,json=onchainPublicKey,proto3" json:"onchain_public_key,omitempty"`
	// max_signature_length is what libocr budgets for a signature from this
	// keyring, and only the keyring knows it.
	MaxSignatureLength uint32 `protobuf:"varint,4,opt,name=max_signature_length,json=maxSignatureLength,proto3" json:"max_signature_length,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *KeysReply) Reset() {
	*x = KeysReply{}
	mi := &file_proxy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysReply) ProtoMessage() {}

func (x *KeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysReply.ProtoReflect.Descriptor instead.
func (*KeysReply) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{19}
}

func (x *KeysReply) GetOffchainPublicKey() []byte {
	if x != nil {
		return x.OffchainPublicKey
	}
	return nil
}

func (x *KeysReply) GetConfigEncryptionPublicKey() []byte {
	if x != nil {
		return x.ConfigEncryptionPublicKey
	}
	return nil
}

func (x *KeysReply) GetOnchainPublicKey() []byte {
	if x != nil {
		return x.OnchainPublicKey
	}
	return nil
}

func (x *KeysReply) GetMaxSignatureLength() uint32 {
	if x != nil {
		return x.MaxSignatureLength
	}
	return 0
}

type SignOffchainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOffchainRequest) Reset() {
	*x = SignOffchainRequest{}
	mi := &file_proxy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOffchainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOffchainRequest) ProtoMessage() {}

func (x *SignOffchainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOffchainRequest.ProtoReflect.Descriptor instead.
func (*SignOffchainRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{20}
}

func (x *SignOffchainRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type ConfigDiffieHellmanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         []byte                 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"` // [32]byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDiffieHellmanRequest) Reset() {
	*x = ConfigDiffieHellmanRequest{}
	mi := &file_proxy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDiffieHellmanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDiffieHellmanRequest) ProtoMessage() {}

func (x *ConfigDiffieHellmanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDiffieHellmanRequest.ProtoReflect.Descriptor instead.
func (*ConfigDiffieHellmanRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{21}
}

func (x *ConfigDiffieHellmanRequest) GetPoint() []byte {
	if x != nil {
		return x.Point
	}
	return nil
}

type ConfigDiffieHellmanReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharedSecret  []byte                 `protobuf:"bytes,1,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"` // [32]byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDiffieHellmanReply) Reset() {
	*x = ConfigDiffieHellmanReply{}
	mi := &file_proxy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDiffieHellmanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDiffieHellmanReply) ProtoMessage() {}

func (x *ConfigDiffieHellmanReply) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDiffieHellmanReply.ProtoReflect.Descriptor instead.
func (*ConfigDiffieHellmanReply) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{22}
}

func (x *ConfigDiffieHellmanReply) GetSharedSecret() []byte {
	if x != nil {
		return x.SharedSecret
	}
	return nil
}

// SignReportRequest is a report and what identifies the round it belongs to.
// Both are signed over, so a signature cannot be lifted onto another round.
type SignReportRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest []byte                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"` // [32]byte
	SeqNr        uint64                 `protobuf:"varint,2,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	// report is what is signed. A report's Info is deliberately absent: it is
	// out-of-band context for the caller and libocr does not sign it either.
	Report        []byte `protobuf:"bytes,3,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignReportRequest) Reset() {
	*x = SignReportRequest{}
	mi := &file_proxy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignReportRequest) ProtoMessage() {}

func (x *SignReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignReportRequest.ProtoReflect.Descriptor instead.
func (*SignReportRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{23}
}

func (x *SignReportRequest) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *SignReportRequest) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *SignReportRequest) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

type SignatureReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureReply) Reset() {
	*x = SignatureReply{}
	mi := &file_proxy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureReply) ProtoMessage() {}

func (x *SignatureReply) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureReply.ProtoReflect.Descriptor instead.
func (*SignatureReply) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{24}
}

func (x *SignatureReply) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type AccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountsRequest) Reset() {
	*x = AccountsRequest{}
	mi := &file_proxy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsRequest) ProtoMessage() {}

func (x *AccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsRequest.ProtoReflect.Descriptor instead.
func (*AccountsRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{25}
}

type AccountsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []string               `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountsReply) Reset() {
	*x = AccountsReply{}
	mi := &file_proxy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsReply) ProtoMessage() {}

func (x *AccountsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsReply.ProtoReflect.Descriptor instead.
func (*AccountsReply) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{26}
}

func (x *AccountsReply) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type SignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// account is one of the accounts Accounts returned.
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// data is the digest to sign. Empty data is a no-op that checks the account
	// exists, which is what core.Keystore says nil data means.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_proxy_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{27}
}

func (x *SignRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SignRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signed        []byte                 `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignReply) Reset() {
	*x = SignReply{}
	mi := &file_proxy_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignReply) ProtoMessage() {}

func (x *SignReply) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignReply.ProtoReflect.Descriptor instead.
func (*SignReply) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{28}
}

func (x *SignReply) GetSigned() []byte {
	if x != nil {
		return x.Signed
	}
	return nil
}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\x06shared\"\xb8\x01\n" +
	"\x1aBinaryNetworkClientRequest\x12>\n" +
	"\vnewEndpoint\x18\x01 \x01(\v2\x1a.shared.NewEndpointRequestH\x00R\vnewEndpoint\x12/\n" +
	"\x06sendTo\x18\x02 \x01(\v2\x15.shared.SendToRequestH\x00R\x06sendTo\x12\x1e\n" +
	"\tbroadcast\x18\x03 \x01(\fH\x00R\tbroadcastB\t\n" +
	"\amessage\"\x86\x02\n" +
	"\x12NewEndpointRequest\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\fR\fconfigDigest\x12\x19\n" +
	"\bpeer_ids\x18\x02 \x03(\tR\apeerIds\x12F\n" +
	"\x10v2_bootstrappers\x18\x03 \x03(\v2\x1b.shared.BootstrapperLocatorR\x0fv2Bootstrappers\x12+\n" +
	"\x11failure_threshold\x18\x04 \x01(\x05R\x10failureThreshold\x12;\n" +
	"\x06limits\x18\x05 \x01(\v2#.shared.BinaryNetworkEndpointLimitsR\x06limits\"D\n" +
	"\x13BootstrapperLocator\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\"\xb3\x02\n" +
	"\x1bBinaryNetworkEndpointLimits\x12,\n" +
	"\x12max_message_length\x18\x01 \x01(\x05R\x10maxMessageLength\x127\n" +
	"\x18messages_rate_per_oracle\x18\x02 \x01(\x01R\x15messagesRatePerOracle\x12?\n" +
	"\x1cmessages_capacity_per_oracle\x18\x03 \x01(\x05R\x19messagesCapacityPerOracle\x121\n" +
	"\x15bytes_rate_per_oracle\x18\x04 \x01(\x01R\x12bytesRatePerOracle\x129\n" +
	"\x19bytes_capacity_per_oracle\x18\x05 \x01(\x05R\x16bytesCapacityPerOracle\"K\n" +
	"\rSendToRequest\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12 \n" +
	"\fto_oracle_id\x18\x03 \x01(\rR\n" +
	"toOracleId\"C\n" +
	"\x17BinaryMessageWithSender\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\fR\x03msg\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\rR\x06sender\"\xce\x01\n" +
	"\x16Endpoint2ClientRequest\x12@\n" +
	"\fnew_endpoint\x18\x01 \x01(\v2\x1b.shared.NewEndpoint2RequestH\x00R\vnewEndpoint\x120\n" +
	"\asend_to\x18\x02 \x01(\v2\x15.shared.Endpoint2SendH\x00R\x06sendTo\x125\n" +
	"\tbroadcast\x18\x03 \x01(\v2\x15.shared.Endpoint2SendH\x00R\tbroadcastB\t\n" +
	"\amessage\"\xb7\x02\n" +
	"\x13NewEndpoint2Request\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\fR\fconfigDigest\x12\x19\n" +
	"\bpeer_ids\x18\x02 \x03(\tR\apeerIds\x12F\n" +
	"\x10v2_bootstrappers\x18\x03 \x03(\v2\x1b.shared.BootstrapperLocatorR\x0fv2Bootstrappers\x12O\n" +
	"\x17default_priority_config\x18\x04 \x01(\v2\x17.shared.Endpoint2ConfigR\x15defaultPriorityConfig\x12G\n" +
	"\x13low_priority_config\x18\x05 \x01(\v2\x17.shared.Endpoint2ConfigR\x11lowPriorityConfig\"\xd0\x02\n" +
	"\x0fEndpoint2Config\x12;\n" +
	"\x06limits\x18\x01 \x01(\v2#.shared.BinaryNetworkEndpointLimitsR\x06limits\x12U\n" +
	"%override_incoming_message_buffer_size\x18\x02 \x01(\x05H\x00R!overrideIncomingMessageBufferSize\x88\x01\x01\x12U\n" +
	"%override_outgoing_message_buffer_size\x18\x03 \x01(\x05H\x01R!overrideOutgoingMessageBufferSize\x88\x01\x01B(\n" +
	"&_override_incoming_message_buffer_sizeB(\n" +
	"&_override_outgoing_message_buffer_size\"]\n" +
	"\rEndpoint2Send\x12 \n" +
	"\fto_oracle_id\x18\x01 \x01(\rR\n" +
	"toOracleId\x12*\n" +
	"\x03msg\x18\x02 \x01(\v2\x18.shared.OutboundMessage2R\x03msg\"\xef\x01\n" +
	"\x10OutboundMessage2\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\rR\bpriority\x12.\n" +
	"\x05plain\x18\x03 \x01(\v2\x16.shared.OutboundPlain2H\x00R\x05plain\x124\n" +
	"\arequest\x18\x04 \x01(\v2\x18.shared.OutboundRequest2H\x00R\arequest\x127\n" +
	"\bresponse\x18\x05 \x01(\v2\x19.shared.OutboundResponse2H\x00R\bresponseB\x06\n" +
	"\x04kind\"\x10\n" +
	"\x0eOutboundPlain2\"m\n" +
	"\x10OutboundRequest2\x12&\n" +
	"\x0fpolicy_max_size\x18\x01 \x01(\x03R\rpolicyMaxSize\x121\n" +
	"\x15policy_expiry_unix_ms\x18\x02 \x01(\x03R\x12policyExpiryUnixMs\"2\n" +
	"\x11OutboundResponse2\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"\x8a\x02\n" +
	"\x16Endpoint2ServerMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\rR\x06sender\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\x12-\n" +
	"\x05plain\x18\x04 \x01(\v2\x15.shared.InboundPlain2H\x00R\x05plain\x123\n" +
	"\arequest\x18\x05 \x01(\v2\x17.shared.InboundRequest2H\x00R\arequest\x126\n" +
	"\bresponse\x18\x06 \x01(\v2\x18.shared.InboundResponse2H\x00R\bresponseB\x06\n" +
	"\x04kind\"\x0f\n" +
	"\rInboundPlain2\"0\n" +
	"\x0fInboundRequest2\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"\x12\n" +
	"\x10InboundResponse2\"\r\n" +
	"\vKeysRequest\"\xdc\x01\n" +
	"\tKeysReply\x12.\n" +
	"\x13offchain_public_key\x18\x01 \x01(\fR\x11offchainPublicKey\x12?\n" +
	"\x1cconfig_encryption_public_key\x18\x02 \x01(\fR\x19configEncryptionPublicKey\x12,\n" +
	"\x12onchain_public_key\x18\x03 \x01(\fR\x10onchainPublicKey\x120\n" +
	"\x14max_signature_length\x18\x04 \x01(\rR\x12maxSignatureLength\"/\n" +
	"\x13SignOffchainRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"2\n" +
	"\x1aConfigDiffieHellmanRequest\x12\x14\n" +
	"\x05point\x18\x01 \x01(\fR\x05point\"?\n" +
	"\x18ConfigDiffieHellmanReply\x12#\n" +
	"\rshared_secret\x18\x01 \x01(\fR\fsharedSecret\"g\n" +
	"\x11SignReportRequest\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\fR\fconfigDigest\x12\x15\n" +
	"\x06seq_nr\x18\x02 \x01(\x04R\x05seqNr\x12\x16\n" +
	"\x06report\x18\x03 \x01(\fR\x06report\".\n" +
	"\x0eSignatureReply\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"\x11\n" +
	"\x0fAccountsRequest\"+\n" +
	"\rAccountsReply\x12\x1a\n" +
	"\baccounts\x18\x01 \x03(\tR\baccounts\";\n" +
	"\vSignRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"#\n" +
	"\tSignReply\x12\x16\n" +
	"\x06signed\x18\x01 \x01(\fR\x06signed2p\n" +
	"\x1aBinaryNetworkEndpointProxy\x12R\n" +
	"\aConnect\x12\".shared.BinaryNetworkClientRequest\x1a\x1f.shared.BinaryMessageWithSender(\x010\x012_\n" +
	"\x0eEndpoint2Proxy\x12M\n" +
	"\aConnect\x12\x1e.shared.Endpoint2ClientRequest\x1a\x1e.shared.Endpoint2ServerMessage(\x010\x012\x9b\x02\n" +
	"\x06Signer\x12.\n" +
	"\x04Keys\x12\x13.shared.KeysRequest\x1a\x11.shared.KeysReply\x12C\n" +
	"\fSignOffchain\x12\x1b.shared.SignOffchainRequest\x1a\x16.shared.SignatureReply\x12[\n" +
	"\x13ConfigDiffieHellman\x12\".shared.ConfigDiffieHellmanRequest\x1a .shared.ConfigDiffieHellmanReply\x12?\n" +
	"\n" +
	"SignReport\x12\x19.shared.SignReportRequest\x1a\x16.shared.SignatureReply2v\n" +
	"\bKeystore\x12:\n" +
	"\bAccounts\x12\x17.shared.AccountsRequest\x1a\x15.shared.AccountsReply\x12.\n" +
	"\x04Sign\x12\x13.shared.SignRequest\x1a\x11.shared.SignReplyB=Z;github.com/smartcontractkit/chainlink-protos/cre/impl/proxyb\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proxy_proto_goTypes = []any{
	(*BinaryNetworkClientRequest)(nil),  // 0: shared.BinaryNetworkClientRequest
	(*NewEndpointRequest)(nil),          // 1: shared.NewEndpointRequest
	(*BootstrapperLocator)(nil),         // 2: shared.BootstrapperLocator
	(*BinaryNetworkEndpointLimits)(nil), // 3: shared.BinaryNetworkEndpointLimits
	(*SendToRequest)(nil),               // 4: shared.SendToRequest
	(*BinaryMessageWithSender)(nil),     // 5: shared.BinaryMessageWithSender
	(*Endpoint2ClientRequest)(nil),      // 6: shared.Endpoint2ClientRequest
	(*NewEndpoint2Request)(nil),         // 7: shared.NewEndpoint2Request
	(*Endpoint2Config)(nil),             // 8: shared.Endpoint2Config
	(*Endpoint2Send)(nil),               // 9: shared.Endpoint2Send
	(*OutboundMessage2)(nil),            // 10: shared.OutboundMessage2
	(*OutboundPlain2)(nil),              // 11: shared.OutboundPlain2
	(*OutboundRequest2)(nil),            // 12: shared.OutboundRequest2
	(*OutboundResponse2)(nil),           // 13: shared.OutboundResponse2
	(*Endpoint2ServerMessage)(nil),      // 14: shared.Endpoint2ServerMessage
	(*InboundPlain2)(nil),               // 15: shared.InboundPlain2
	(*InboundRequest2)(nil),             // 16: shared.InboundRequest2
	(*InboundResponse2)(nil),            // 17: shared.InboundResponse2
	(*KeysRequest)(nil),                 // 18: shared.KeysRequest
	(*KeysReply)(nil),                   // 19: shared.KeysReply
	(*SignOffchainRequest)(nil),         // 20: shared.SignOffchainRequest
	(*ConfigDiffieHellmanRequest)(nil),  // 21: shared.ConfigDiffieHellmanRequest
	(*ConfigDiffieHellmanReply)(nil),    // 22: shared.ConfigDiffieHellmanReply
	(*SignReportRequest)(nil),           // 23: shared.SignReportRequest
	(*SignatureReply)(nil),              // 24: shared.SignatureReply
	(*AccountsRequest)(nil),             // 25: shared.AccountsRequest
	(*AccountsReply)(nil),               // 26: shared.AccountsReply
	(*SignRequest)(nil),                 // 27: shared.SignRequest
	(*SignReply)(nil),                   // 28: shared.SignReply
}
var file_proxy_proto_depIdxs = []int32{
	1,  // 0: shared.BinaryNetworkClientRequest.newEndpoint:type_name -> shared.NewEndpointRequest
	4,  // 1: shared.BinaryNetworkClientRequest.sendTo:type_name -> shared.SendToRequest
	2,  // 2: shared.NewEndpointRequest.v2_bootstrappers:type_name -> shared.BootstrapperLocator
	3,  // 3: shared.NewEndpointRequest.limits:type_name -> shared.BinaryNetworkEndpointLimits
	7,  // 4: shared.Endpoint2ClientRequest.new_endpoint:type_name -> shared.NewEndpoint2Request
	9,  // 5: shared.Endpoint2ClientRequest.send_to:type_name -> shared.Endpoint2Send
	9,  // 6: shared.Endpoint2ClientRequest.broadcast:type_name -> shared.Endpoint2Send
	2,  // 7: shared.NewEndpoint2Request.v2_bootstrappers:type_name -> shared.BootstrapperLocator
	8,  // 8: shared.NewEndpoint2Request.default_priority_config:type_name -> shared.Endpoint2Config
	8,  // 9: shared.NewEndpoint2Request.low_priority_config:type_name -> shared.Endpoint2Config
	3,  // 10: shared.Endpoint2Config.limits:type_name -> shared.BinaryNetworkEndpointLimits
	10, // 11: shared.Endpoint2Send.msg:type_name -> shared.OutboundMessage2
	11, // 12: shared.OutboundMessage2.plain:type_name -> shared.OutboundPlain2
	12, // 13: shared.OutboundMessage2.request:type_name -> shared.OutboundRequest2
	13, // 14: shared.OutboundMessage2.response:type_name -> shared.OutboundResponse2
	15, // 15: shared.Endpoint2ServerMessage.plain:type_name -> shared.InboundPlain2
	16, // 16: shared.Endpoint2ServerMessage.request:type_name -> shared.InboundRequest2
	17, // 17: shared.Endpoint2ServerMessage.response:type_name -> shared.InboundResponse2
	0,  // 18: shared.BinaryNetworkEndpointProxy.Connect:input_type -> shared.BinaryNetworkClientRequest
	6,  // 19: shared.Endpoint2Proxy.Connect:input_type -> shared.Endpoint2ClientRequest
	18, // 20: shared.Signer.Keys:input_type -> shared.KeysRequest
	20, // 21: shared.Signer.SignOffchain:input_type -> shared.SignOffchainRequest
	21, // 22: shared.Signer.ConfigDiffieHellman:input_type -> shared.ConfigDiffieHellmanRequest
	23, // 23: shared.Signer.SignReport:input_type -> shared.SignReportRequest
	25, // 24: shared.Keystore.Accounts:input_type -> shared.AccountsRequest
	27, // 25: shared.Keystore.Sign:input_type -> shared.SignRequest
	5,  // 26: shared.BinaryNetworkEndpointProxy.Connect:output_type -> shared.BinaryMessageWithSender
	14, // 27: shared.Endpoint2Proxy.Connect:output_type -> shared.Endpoint2ServerMessage
	19, // 28: shared.Signer.Keys:output_type -> shared.KeysReply
	24, // 29: shared.Signer.SignOffchain:output_type -> shared.SignatureReply
	22, // 30: shared.Signer.ConfigDiffieHellman:output_type -> shared.ConfigDiffieHellmanReply
	24, // 31: shared.Signer.SignReport:output_type -> shared.SignatureReply
	26, // 32: shared.Keystore.Accounts:output_type -> shared.AccountsReply
	28, // 33: shared.Keystore.Sign:output_type -> shared.SignReply
	26, // [26:34] is the sub-list for method output_type
	18, // [18:26] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	file_proxy_proto_msgTypes[0].OneofWrappers = []any{
		(*BinaryNetworkClientRequest_NewEndpoint)(nil),
		(*BinaryNetworkClientRequest_SendTo)(nil),
		(*BinaryNetworkClientRequest_Broadcast)(nil),
	}
	file_proxy_proto_msgTypes[6].OneofWrappers = []any{
		(*Endpoint2ClientRequest_NewEndpoint)(nil),
		(*Endpoint2ClientRequest_SendTo)(nil),
		(*Endpoint2ClientRequest_Broadcast)(nil),
	}
	file_proxy_proto_msgTypes[8].OneofWrappers = []any{}
	file_proxy_proto_msgTypes[10].OneofWrappers = []any{
		(*OutboundMessage2_Plain)(nil),
		(*OutboundMessage2_Request)(nil),
		(*OutboundMessage2_Response)(nil),
	}
	file_proxy_proto_msgTypes[14].OneofWrappers = []any{
		(*Endpoint2ServerMessage_Plain)(nil),
		(*Endpoint2ServerMessage_Request)(nil),
		(*Endpoint2ServerMessage_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
