// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: node-platform/common/v1/chain_plugin_config.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainPluginConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsaPublicKey  string                 `protobuf:"bytes,1,opt,name=csa_public_key,json=csaPublicKey,proto3" json:"csa_public_key,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Urls          map[string]string      `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainPluginConfig) Reset() {
	*x = ChainPluginConfig{}
	mi := &file_node_platform_common_v1_chain_plugin_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainPluginConfig) ProtoMessage() {}

func (x *ChainPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_platform_common_v1_chain_plugin_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainPluginConfig.ProtoReflect.Descriptor instead.
func (*ChainPluginConfig) Descriptor() ([]byte, []int) {
	return file_node_platform_common_v1_chain_plugin_config_proto_rawDescGZIP(), []int{0}
}

func (x *ChainPluginConfig) GetCsaPublicKey() string {
	if x != nil {
		return x.CsaPublicKey
	}
	return ""
}

func (x *ChainPluginConfig) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ChainPluginConfig) GetUrls() map[string]string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_node_platform_common_v1_chain_plugin_config_proto protoreflect.FileDescriptor

const file_node_platform_common_v1_chain_plugin_config_proto_rawDesc = "" +
	"\n" +
	"1node-platform/common/v1/chain_plugin_config.proto\x12\tcommon.v1\"\xc9\x01\n" +
	"\x11ChainPluginConfig\x12$\n" +
	"\x0ecsa_public_key\x18\x01 \x01(\tR\fcsaPublicKey\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12:\n" +
	"\x04urls\x18\x03 \x03(\v2&.common.v1.ChainPluginConfig.UrlsEntryR\x04urls\x1a7\n" +
	"\tUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BFZDgithub.com/smartcontractkit/chainlink-protos/node-platform/common/v1b\x06proto3"

var (
	file_node_platform_common_v1_chain_plugin_config_proto_rawDescOnce sync.Once
	file_node_platform_common_v1_chain_plugin_config_proto_rawDescData []byte
)

func file_node_platform_common_v1_chain_plugin_config_proto_rawDescGZIP() []byte {
	file_node_platform_common_v1_chain_plugin_config_proto_rawDescOnce.Do(func() {
		file_node_platform_common_v1_chain_plugin_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_platform_common_v1_chain_plugin_config_proto_rawDesc), len(file_node_platform_common_v1_chain_plugin_config_proto_rawDesc)))
	})
	return file_node_platform_common_v1_chain_plugin_config_proto_rawDescData
}

var file_node_platform_common_v1_chain_plugin_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_platform_common_v1_chain_plugin_config_proto_goTypes = []any{
	(*ChainPluginConfig)(nil), // 0: common.v1.ChainPluginConfig
	nil,                       // 1: common.v1.ChainPluginConfig.UrlsEntry
}
var file_node_platform_common_v1_chain_plugin_config_proto_depIdxs = []int32{
	1, // 0: common.v1.ChainPluginConfig.urls:type_name -> common.v1.ChainPluginConfig.UrlsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_platform_common_v1_chain_plugin_config_proto_init() }
func file_node_platform_common_v1_chain_plugin_config_proto_init() {
	if File_node_platform_common_v1_chain_plugin_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_platform_common_v1_chain_plugin_config_proto_rawDesc), len(file_node_platform_common_v1_chain_plugin_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_platform_common_v1_chain_plugin_config_proto_goTypes,
		DependencyIndexes: file_node_platform_common_v1_chain_plugin_config_proto_depIdxs,
		MessageInfos:      file_node_platform_common_v1_chain_plugin_config_proto_msgTypes,
	}.Build()
	File_node_platform_common_v1_chain_plugin_config_proto = out.File
	file_node_platform_common_v1_chain_plugin_config_proto_goTypes = nil
	file_node_platform_common_v1_chain_plugin_config_proto_depIdxs = nil
}
