// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.5
// source: workflows/v2/cre_info.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreInfo struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	DonID                       int32                  `protobuf:"varint,1,opt,name=donID,proto3" json:"donID,omitempty"`
	DonF                        int32                  `protobuf:"varint,2,opt,name=donF,proto3" json:"donF,omitempty"`
	DonN                        int32                  `protobuf:"varint,3,opt,name=donN,proto3" json:"donN,omitempty"`
	P2PID                       string                 `protobuf:"bytes,4,opt,name=p2pID,proto3" json:"p2pID,omitempty"`
	WorkflowRegistryAddress     string                 `protobuf:"bytes,5,opt,name=workflowRegistryAddress,proto3" json:"workflowRegistryAddress,omitempty"`
	WorkflowRegistryVersion     string                 `protobuf:"bytes,6,opt,name=workflowRegistryVersion,proto3" json:"workflowRegistryVersion,omitempty"`
	WorkflowRegistryChain       string                 `protobuf:"bytes,7,opt,name=workflowRegistryChain,proto3" json:"workflowRegistryChain,omitempty"`
	EngineVersion               string                 `protobuf:"bytes,8,opt,name=engineVersion,proto3" json:"engineVersion,omitempty"`
	CapabilitiesRegistryVersion string                 `protobuf:"bytes,9,opt,name=capabilitiesRegistryVersion,proto3" json:"capabilitiesRegistryVersion,omitempty"`
	DonVersion                  string                 `protobuf:"bytes,10,opt,name=donVersion,proto3" json:"donVersion,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreInfo) Reset() {
	*x = CreInfo{}
	mi := &file_workflows_v2_cre_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreInfo) ProtoMessage() {}

func (x *CreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v2_cre_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreInfo.ProtoReflect.Descriptor instead.
func (*CreInfo) Descriptor() ([]byte, []int) {
	return file_workflows_v2_cre_info_proto_rawDescGZIP(), []int{0}
}

func (x *CreInfo) GetDonID() int32 {
	if x != nil {
		return x.DonID
	}
	return 0
}

func (x *CreInfo) GetDonF() int32 {
	if x != nil {
		return x.DonF
	}
	return 0
}

func (x *CreInfo) GetDonN() int32 {
	if x != nil {
		return x.DonN
	}
	return 0
}

func (x *CreInfo) GetP2PID() string {
	if x != nil {
		return x.P2PID
	}
	return ""
}

func (x *CreInfo) GetWorkflowRegistryAddress() string {
	if x != nil {
		return x.WorkflowRegistryAddress
	}
	return ""
}

func (x *CreInfo) GetWorkflowRegistryVersion() string {
	if x != nil {
		return x.WorkflowRegistryVersion
	}
	return ""
}

func (x *CreInfo) GetWorkflowRegistryChain() string {
	if x != nil {
		return x.WorkflowRegistryChain
	}
	return ""
}

func (x *CreInfo) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *CreInfo) GetCapabilitiesRegistryVersion() string {
	if x != nil {
		return x.CapabilitiesRegistryVersion
	}
	return ""
}

func (x *CreInfo) GetDonVersion() string {
	if x != nil {
		return x.DonVersion
	}
	return ""
}

var File_workflows_v2_cre_info_proto protoreflect.FileDescriptor

const file_workflows_v2_cre_info_proto_rawDesc = "" +
	"\n" +
	"\x1bworkflows/v2/cre_info.proto\x12\fworkflows.v2\"\x8f\x03\n" +
	"\aCreInfo\x12\x14\n" +
	"\x05donID\x18\x01 \x01(\x05R\x05donID\x12\x12\n" +
	"\x04donF\x18\x02 \x01(\x05R\x04donF\x12\x12\n" +
	"\x04donN\x18\x03 \x01(\x05R\x04donN\x12\x14\n" +
	"\x05p2pID\x18\x04 \x01(\tR\x05p2pID\x128\n" +
	"\x17workflowRegistryAddress\x18\x05 \x01(\tR\x17workflowRegistryAddress\x128\n" +
	"\x17workflowRegistryVersion\x18\x06 \x01(\tR\x17workflowRegistryVersion\x124\n" +
	"\x15workflowRegistryChain\x18\a \x01(\tR\x15workflowRegistryChain\x12$\n" +
	"\rengineVersion\x18\b \x01(\tR\rengineVersion\x12@\n" +
	"\x1bcapabilitiesRegistryVersion\x18\t \x01(\tR\x1bcapabilitiesRegistryVersion\x12\x1e\n" +
	"\n" +
	"donVersion\x18\n" +
	" \x01(\tR\n" +
	"donVersionB>Z<github.com/smartcontractkit/chainlink-protos/workflows/go/v2b\x06proto3"

var (
	file_workflows_v2_cre_info_proto_rawDescOnce sync.Once
	file_workflows_v2_cre_info_proto_rawDescData []byte
)

func file_workflows_v2_cre_info_proto_rawDescGZIP() []byte {
	file_workflows_v2_cre_info_proto_rawDescOnce.Do(func() {
		file_workflows_v2_cre_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflows_v2_cre_info_proto_rawDesc), len(file_workflows_v2_cre_info_proto_rawDesc)))
	})
	return file_workflows_v2_cre_info_proto_rawDescData
}

var file_workflows_v2_cre_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workflows_v2_cre_info_proto_goTypes = []any{
	(*CreInfo)(nil), // 0: workflows.v2.CreInfo
}
var file_workflows_v2_cre_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflows_v2_cre_info_proto_init() }
func file_workflows_v2_cre_info_proto_init() {
	if File_workflows_v2_cre_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_v2_cre_info_proto_rawDesc), len(file_workflows_v2_cre_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflows_v2_cre_info_proto_goTypes,
		DependencyIndexes: file_workflows_v2_cre_info_proto_depIdxs,
		MessageInfos:      file_workflows_v2_cre_info_proto_msgTypes,
	}.Build()
	File_workflows_v2_cre_info_proto = out.File
	file_workflows_v2_cre_info_proto_goTypes = nil
	file_workflows_v2_cre_info_proto_depIdxs = nil
}
