// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: workflows/v2/transaction_info.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainSelector string                 `protobuf:"bytes,1,opt,name=chainSelector,proto3" json:"chainSelector,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
	GasCost       string                 `protobuf:"bytes,3,opt,name=gasCost,proto3" json:"gasCost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_workflows_v2_transaction_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v2_transaction_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_workflows_v2_transaction_info_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionInfo) GetChainSelector() string {
	if x != nil {
		return x.ChainSelector
	}
	return ""
}

func (x *TransactionInfo) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionInfo) GetGasCost() string {
	if x != nil {
		return x.GasCost
	}
	return ""
}

var File_workflows_v2_transaction_info_proto protoreflect.FileDescriptor

const file_workflows_v2_transaction_info_proto_rawDesc = "" +
	"\n" +
	"#workflows/v2/transaction_info.proto\x12\fworkflows.v2\"i\n" +
	"\x0fTransactionInfo\x12$\n" +
	"\rchainSelector\x18\x01 \x01(\tR\rchainSelector\x12\x16\n" +
	"\x06txHash\x18\x02 \x01(\tR\x06txHash\x12\x18\n" +
	"\agasCost\x18\x03 \x01(\tR\agasCostB>Z<github.com/smartcontractkit/chainlink-protos/workflows/go/v2b\x06proto3"

var (
	file_workflows_v2_transaction_info_proto_rawDescOnce sync.Once
	file_workflows_v2_transaction_info_proto_rawDescData []byte
)

func file_workflows_v2_transaction_info_proto_rawDescGZIP() []byte {
	file_workflows_v2_transaction_info_proto_rawDescOnce.Do(func() {
		file_workflows_v2_transaction_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflows_v2_transaction_info_proto_rawDesc), len(file_workflows_v2_transaction_info_proto_rawDesc)))
	})
	return file_workflows_v2_transaction_info_proto_rawDescData
}

var file_workflows_v2_transaction_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workflows_v2_transaction_info_proto_goTypes = []any{
	(*TransactionInfo)(nil), // 0: workflows.v2.TransactionInfo
}
var file_workflows_v2_transaction_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflows_v2_transaction_info_proto_init() }
func file_workflows_v2_transaction_info_proto_init() {
	if File_workflows_v2_transaction_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_v2_transaction_info_proto_rawDesc), len(file_workflows_v2_transaction_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflows_v2_transaction_info_proto_goTypes,
		DependencyIndexes: file_workflows_v2_transaction_info_proto_depIdxs,
		MessageInfos:      file_workflows_v2_transaction_info_proto_msgTypes,
	}.Build()
	File_workflows_v2_transaction_info_proto = out.File
	file_workflows_v2_transaction_info_proto_goTypes = nil
	file_workflows_v2_transaction_info_proto_depIdxs = nil
}
