// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: workflows/v2/trigger_execution_started.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerExecutionStarted struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CreInfo             *CreInfo               `protobuf:"bytes,1,opt,name=creInfo,proto3" json:"creInfo,omitempty"`
	Workflow            *WorkflowKey           `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	WorkflowExecutionID string                 `protobuf:"bytes,3,opt,name=workflowExecutionID,proto3" json:"workflowExecutionID,omitempty"`
	Timestamp           string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TriggerID           string                 `protobuf:"bytes,5,opt,name=triggerID,proto3" json:"triggerID,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TriggerExecutionStarted) Reset() {
	*x = TriggerExecutionStarted{}
	mi := &file_workflows_v2_trigger_execution_started_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerExecutionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerExecutionStarted) ProtoMessage() {}

func (x *TriggerExecutionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v2_trigger_execution_started_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerExecutionStarted.ProtoReflect.Descriptor instead.
func (*TriggerExecutionStarted) Descriptor() ([]byte, []int) {
	return file_workflows_v2_trigger_execution_started_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerExecutionStarted) GetCreInfo() *CreInfo {
	if x != nil {
		return x.CreInfo
	}
	return nil
}

func (x *TriggerExecutionStarted) GetWorkflow() *WorkflowKey {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *TriggerExecutionStarted) GetWorkflowExecutionID() string {
	if x != nil {
		return x.WorkflowExecutionID
	}
	return ""
}

func (x *TriggerExecutionStarted) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TriggerExecutionStarted) GetTriggerID() string {
	if x != nil {
		return x.TriggerID
	}
	return ""
}

var File_workflows_v2_trigger_execution_started_proto protoreflect.FileDescriptor

const file_workflows_v2_trigger_execution_started_proto_rawDesc = "" +
	"\n" +
	",workflows/v2/trigger_execution_started.proto\x12\fworkflows.v2\x1a\x1bworkflows/v2/cre_info.proto\x1a\x1fworkflows/v2/workflow_key.proto\"\xef\x01\n" +
	"\x17TriggerExecutionStarted\x12/\n" +
	"\acreInfo\x18\x01 \x01(\v2\x15.workflows.v2.CreInfoR\acreInfo\x125\n" +
	"\bworkflow\x18\x02 \x01(\v2\x19.workflows.v2.WorkflowKeyR\bworkflow\x120\n" +
	"\x13workflowExecutionID\x18\x03 \x01(\tR\x13workflowExecutionID\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\ttriggerID\x18\x05 \x01(\tR\ttriggerIDB>Z<github.com/smartcontractkit/chainlink-protos/workflows/go/v2b\x06proto3"

var (
	file_workflows_v2_trigger_execution_started_proto_rawDescOnce sync.Once
	file_workflows_v2_trigger_execution_started_proto_rawDescData []byte
)

func file_workflows_v2_trigger_execution_started_proto_rawDescGZIP() []byte {
	file_workflows_v2_trigger_execution_started_proto_rawDescOnce.Do(func() {
		file_workflows_v2_trigger_execution_started_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflows_v2_trigger_execution_started_proto_rawDesc), len(file_workflows_v2_trigger_execution_started_proto_rawDesc)))
	})
	return file_workflows_v2_trigger_execution_started_proto_rawDescData
}

var file_workflows_v2_trigger_execution_started_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workflows_v2_trigger_execution_started_proto_goTypes = []any{
	(*TriggerExecutionStarted)(nil), // 0: workflows.v2.TriggerExecutionStarted
	(*CreInfo)(nil),                 // 1: workflows.v2.CreInfo
	(*WorkflowKey)(nil),             // 2: workflows.v2.WorkflowKey
}
var file_workflows_v2_trigger_execution_started_proto_depIdxs = []int32{
	1, // 0: workflows.v2.TriggerExecutionStarted.creInfo:type_name -> workflows.v2.CreInfo
	2, // 1: workflows.v2.TriggerExecutionStarted.workflow:type_name -> workflows.v2.WorkflowKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workflows_v2_trigger_execution_started_proto_init() }
func file_workflows_v2_trigger_execution_started_proto_init() {
	if File_workflows_v2_trigger_execution_started_proto != nil {
		return
	}
	file_workflows_v2_cre_info_proto_init()
	file_workflows_v2_workflow_key_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_v2_trigger_execution_started_proto_rawDesc), len(file_workflows_v2_trigger_execution_started_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflows_v2_trigger_execution_started_proto_goTypes,
		DependencyIndexes: file_workflows_v2_trigger_execution_started_proto_depIdxs,
		MessageInfos:      file_workflows_v2_trigger_execution_started_proto_msgTypes,
	}.Build()
	File_workflows_v2_trigger_execution_started_proto = out.File
	file_workflows_v2_trigger_execution_started_proto_goTypes = nil
	file_workflows_v2_trigger_execution_started_proto_depIdxs = nil
}
