// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: workflows/v2/workflow_execution_profile.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionProfile struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	WorkflowID          string                  `protobuf:"bytes,1,opt,name=workflowID,proto3" json:"workflowID,omitempty"`
	WorkflowExecutionID string                  `protobuf:"bytes,2,opt,name=workflowExecutionID,proto3" json:"workflowExecutionID,omitempty"`
	StartTime           string                  `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime             string                  `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Status              string                  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Steps               []*ExecutionProfileStep `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecutionProfile) Reset() {
	*x = ExecutionProfile{}
	mi := &file_workflows_v2_workflow_execution_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionProfile) ProtoMessage() {}

func (x *ExecutionProfile) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v2_workflow_execution_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionProfile.ProtoReflect.Descriptor instead.
func (*ExecutionProfile) Descriptor() ([]byte, []int) {
	return file_workflows_v2_workflow_execution_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionProfile) GetWorkflowID() string {
	if x != nil {
		return x.WorkflowID
	}
	return ""
}

func (x *ExecutionProfile) GetWorkflowExecutionID() string {
	if x != nil {
		return x.WorkflowExecutionID
	}
	return ""
}

func (x *ExecutionProfile) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ExecutionProfile) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ExecutionProfile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionProfile) GetSteps() []*ExecutionProfileStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type ExecutionProfileStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepID        string                 `protobuf:"bytes,1,opt,name=stepID,proto3" json:"stepID,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	CapabilityID  string                 `protobuf:"bytes,4,opt,name=capabilityID,proto3" json:"capabilityID,omitempty"`
	HasError      bool                   `protobuf:"varint,5,opt,name=hasError,proto3" json:"hasError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionProfileStep) Reset() {
	*x = ExecutionProfileStep{}
	mi := &file_workflows_v2_workflow_execution_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionProfileStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionProfileStep) ProtoMessage() {}

func (x *ExecutionProfileStep) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v2_workflow_execution_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionProfileStep.ProtoReflect.Descriptor instead.
func (*ExecutionProfileStep) Descriptor() ([]byte, []int) {
	return file_workflows_v2_workflow_execution_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionProfileStep) GetStepID() string {
	if x != nil {
		return x.StepID
	}
	return ""
}

func (x *ExecutionProfileStep) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ExecutionProfileStep) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ExecutionProfileStep) GetCapabilityID() string {
	if x != nil {
		return x.CapabilityID
	}
	return ""
}

func (x *ExecutionProfileStep) GetHasError() bool {
	if x != nil {
		return x.HasError
	}
	return false
}

var File_workflows_v2_workflow_execution_profile_proto protoreflect.FileDescriptor

const file_workflows_v2_workflow_execution_profile_proto_rawDesc = "" +
	"\n" +
	"-workflows/v2/workflow_execution_profile.proto\x12\fworkflows.v2\"\xee\x01\n" +
	"\x10ExecutionProfile\x12\x1e\n" +
	"\n" +
	"workflowID\x18\x01 \x01(\tR\n" +
	"workflowID\x120\n" +
	"\x13workflowExecutionID\x18\x02 \x01(\tR\x13workflowExecutionID\x12\x1c\n" +
	"\tstartTime\x18\x03 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x128\n" +
	"\x05steps\x18\x06 \x03(\v2\".workflows.v2.ExecutionProfileStepR\x05steps\"\xa6\x01\n" +
	"\x14ExecutionProfileStep\x12\x16\n" +
	"\x06stepID\x18\x01 \x01(\tR\x06stepID\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\tR\aendTime\x12\"\n" +
	"\fcapabilityID\x18\x04 \x01(\tR\fcapabilityID\x12\x1a\n" +
	"\bhasError\x18\x05 \x01(\bR\bhasErrorB>Z<github.com/smartcontractkit/chainlink-protos/workflows/go/v2b\x06proto3"

var (
	file_workflows_v2_workflow_execution_profile_proto_rawDescOnce sync.Once
	file_workflows_v2_workflow_execution_profile_proto_rawDescData []byte
)

func file_workflows_v2_workflow_execution_profile_proto_rawDescGZIP() []byte {
	file_workflows_v2_workflow_execution_profile_proto_rawDescOnce.Do(func() {
		file_workflows_v2_workflow_execution_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflows_v2_workflow_execution_profile_proto_rawDesc), len(file_workflows_v2_workflow_execution_profile_proto_rawDesc)))
	})
	return file_workflows_v2_workflow_execution_profile_proto_rawDescData
}

var file_workflows_v2_workflow_execution_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workflows_v2_workflow_execution_profile_proto_goTypes = []any{
	(*ExecutionProfile)(nil),     // 0: workflows.v2.ExecutionProfile
	(*ExecutionProfileStep)(nil), // 1: workflows.v2.ExecutionProfileStep
}
var file_workflows_v2_workflow_execution_profile_proto_depIdxs = []int32{
	1, // 0: workflows.v2.ExecutionProfile.steps:type_name -> workflows.v2.ExecutionProfileStep
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workflows_v2_workflow_execution_profile_proto_init() }
func file_workflows_v2_workflow_execution_profile_proto_init() {
	if File_workflows_v2_workflow_execution_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_v2_workflow_execution_profile_proto_rawDesc), len(file_workflows_v2_workflow_execution_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflows_v2_workflow_execution_profile_proto_goTypes,
		DependencyIndexes: file_workflows_v2_workflow_execution_profile_proto_depIdxs,
		MessageInfos:      file_workflows_v2_workflow_execution_profile_proto_msgTypes,
	}.Build()
	File_workflows_v2_workflow_execution_profile_proto = out.File
	file_workflows_v2_workflow_execution_profile_proto_goTypes = nil
	file_workflows_v2_workflow_execution_profile_proto_depIdxs = nil
}
