// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: workflows/v2/workflow_paused.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowPaused struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	CreInfo       *CreInfo                `protobuf:"bytes,1,opt,name=creInfo,proto3" json:"creInfo,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxInfo        *TransactionInfo        `protobuf:"bytes,3,opt,name=txInfo,proto3" json:"txInfo,omitempty"`
	Workflow      *Workflow               `protobuf:"bytes,4,opt,name=workflow,proto3" json:"workflow,omitempty"`
	ErrorMessage  *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"` // present ⇔ failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowPaused) Reset() {
	*x = WorkflowPaused{}
	mi := &file_workflows_v2_workflow_paused_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPaused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPaused) ProtoMessage() {}

func (x *WorkflowPaused) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v2_workflow_paused_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPaused.ProtoReflect.Descriptor instead.
func (*WorkflowPaused) Descriptor() ([]byte, []int) {
	return file_workflows_v2_workflow_paused_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowPaused) GetCreInfo() *CreInfo {
	if x != nil {
		return x.CreInfo
	}
	return nil
}

func (x *WorkflowPaused) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WorkflowPaused) GetTxInfo() *TransactionInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *WorkflowPaused) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowPaused) GetErrorMessage() *wrapperspb.StringValue {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

var File_workflows_v2_workflow_paused_proto protoreflect.FileDescriptor

const file_workflows_v2_workflow_paused_proto_rawDesc = "" +
	"\n" +
	"\"workflows/v2/workflow_paused.proto\x12\fworkflows.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bworkflows/v2/cre_info.proto\x1a#workflows/v2/transaction_info.proto\x1a\x1bworkflows/v2/workflow.proto\"\xa8\x02\n" +
	"\x0eWorkflowPaused\x12/\n" +
	"\acreInfo\x18\x01 \x01(\v2\x15.workflows.v2.CreInfoR\acreInfo\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\x06txInfo\x18\x03 \x01(\v2\x1d.workflows.v2.TransactionInfoR\x06txInfo\x122\n" +
	"\bworkflow\x18\x04 \x01(\v2\x16.workflows.v2.WorkflowR\bworkflow\x12@\n" +
	"\ferrorMessage\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\ferrorMessageB>Z<github.com/smartcontractkit/chainlink-protos/workflows/go/v2b\x06proto3"

var (
	file_workflows_v2_workflow_paused_proto_rawDescOnce sync.Once
	file_workflows_v2_workflow_paused_proto_rawDescData []byte
)

func file_workflows_v2_workflow_paused_proto_rawDescGZIP() []byte {
	file_workflows_v2_workflow_paused_proto_rawDescOnce.Do(func() {
		file_workflows_v2_workflow_paused_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflows_v2_workflow_paused_proto_rawDesc), len(file_workflows_v2_workflow_paused_proto_rawDesc)))
	})
	return file_workflows_v2_workflow_paused_proto_rawDescData
}

var file_workflows_v2_workflow_paused_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workflows_v2_workflow_paused_proto_goTypes = []any{
	(*WorkflowPaused)(nil),         // 0: workflows.v2.WorkflowPaused
	(*CreInfo)(nil),                // 1: workflows.v2.CreInfo
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
	(*TransactionInfo)(nil),        // 3: workflows.v2.TransactionInfo
	(*Workflow)(nil),               // 4: workflows.v2.Workflow
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
}
var file_workflows_v2_workflow_paused_proto_depIdxs = []int32{
	1, // 0: workflows.v2.WorkflowPaused.creInfo:type_name -> workflows.v2.CreInfo
	2, // 1: workflows.v2.WorkflowPaused.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: workflows.v2.WorkflowPaused.txInfo:type_name -> workflows.v2.TransactionInfo
	4, // 3: workflows.v2.WorkflowPaused.workflow:type_name -> workflows.v2.Workflow
	5, // 4: workflows.v2.WorkflowPaused.errorMessage:type_name -> google.protobuf.StringValue
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_workflows_v2_workflow_paused_proto_init() }
func file_workflows_v2_workflow_paused_proto_init() {
	if File_workflows_v2_workflow_paused_proto != nil {
		return
	}
	file_workflows_v2_cre_info_proto_init()
	file_workflows_v2_transaction_info_proto_init()
	file_workflows_v2_workflow_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_v2_workflow_paused_proto_rawDesc), len(file_workflows_v2_workflow_paused_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflows_v2_workflow_paused_proto_goTypes,
		DependencyIndexes: file_workflows_v2_workflow_paused_proto_depIdxs,
		MessageInfos:      file_workflows_v2_workflow_paused_proto_msgTypes,
	}.Build()
	File_workflows_v2_workflow_paused_proto = out.File
	file_workflows_v2_workflow_paused_proto_goTypes = nil
	file_workflows_v2_workflow_paused_proto_depIdxs = nil
}
