// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: workflows/v2/workflow_execution_finished.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowExecutionFinished struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CreInfo             *CreInfo               `protobuf:"bytes,1,opt,name=creInfo,proto3" json:"creInfo,omitempty"`
	Workflow            *WorkflowKey           `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	WorkflowExecutionID string                 `protobuf:"bytes,3,opt,name=workflowExecutionID,proto3" json:"workflowExecutionID,omitempty"`
	Timestamp           string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status              ExecutionStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=workflows.v2.ExecutionStatus" json:"status,omitempty"`
	Error               string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	ExecutedInTEE       bool                   `protobuf:"varint,7,opt,name=executedInTEE,proto3" json:"executedInTEE,omitempty"`
	// classifiedStatus attributes a terminal outcome to the user vs the platform.
	// It is set alongside `status`: SUCCEEDED mirrors status, while a failure is
	// reported as USER_ERROR or SYSTEM_ERROR. Consumers that do not understand it
	// fall back to `status`.
	ClassifiedStatus ClassifiedExecutionStatus `protobuf:"varint,8,opt,name=classifiedStatus,proto3,enum=workflows.v2.ClassifiedExecutionStatus" json:"classifiedStatus,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkflowExecutionFinished) Reset() {
	*x = WorkflowExecutionFinished{}
	mi := &file_workflows_v2_workflow_execution_finished_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecutionFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecutionFinished) ProtoMessage() {}

func (x *WorkflowExecutionFinished) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_v2_workflow_execution_finished_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecutionFinished.ProtoReflect.Descriptor instead.
func (*WorkflowExecutionFinished) Descriptor() ([]byte, []int) {
	return file_workflows_v2_workflow_execution_finished_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowExecutionFinished) GetCreInfo() *CreInfo {
	if x != nil {
		return x.CreInfo
	}
	return nil
}

func (x *WorkflowExecutionFinished) GetWorkflow() *WorkflowKey {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *WorkflowExecutionFinished) GetWorkflowExecutionID() string {
	if x != nil {
		return x.WorkflowExecutionID
	}
	return ""
}

func (x *WorkflowExecutionFinished) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *WorkflowExecutionFinished) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *WorkflowExecutionFinished) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowExecutionFinished) GetExecutedInTEE() bool {
	if x != nil {
		return x.ExecutedInTEE
	}
	return false
}

func (x *WorkflowExecutionFinished) GetClassifiedStatus() ClassifiedExecutionStatus {
	if x != nil {
		return x.ClassifiedStatus
	}
	return ClassifiedExecutionStatus_CLASSIFIED_EXECUTION_STATUS_UNSPECIFIED
}

var File_workflows_v2_workflow_execution_finished_proto protoreflect.FileDescriptor

const file_workflows_v2_workflow_execution_finished_proto_rawDesc = "" +
	"\n" +
	".workflows/v2/workflow_execution_finished.proto\x12\fworkflows.v2\x1a\x1bworkflows/v2/cre_info.proto\x1a\x1fworkflows/v2/workflow_key.proto\x1a\x1eworkflows/v2/xxx_no_send.proto\"\x9b\x03\n" +
	"\x19WorkflowExecutionFinished\x12/\n" +
	"\acreInfo\x18\x01 \x01(\v2\x15.workflows.v2.CreInfoR\acreInfo\x125\n" +
	"\bworkflow\x18\x02 \x01(\v2\x19.workflows.v2.WorkflowKeyR\bworkflow\x120\n" +
	"\x13workflowExecutionID\x18\x03 \x01(\tR\x13workflowExecutionID\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.workflows.v2.ExecutionStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12$\n" +
	"\rexecutedInTEE\x18\a \x01(\bR\rexecutedInTEE\x12S\n" +
	"\x10classifiedStatus\x18\b \x01(\x0e2'.workflows.v2.ClassifiedExecutionStatusR\x10classifiedStatusB>Z<github.com/smartcontractkit/chainlink-protos/workflows/go/v2b\x06proto3"

var (
	file_workflows_v2_workflow_execution_finished_proto_rawDescOnce sync.Once
	file_workflows_v2_workflow_execution_finished_proto_rawDescData []byte
)

func file_workflows_v2_workflow_execution_finished_proto_rawDescGZIP() []byte {
	file_workflows_v2_workflow_execution_finished_proto_rawDescOnce.Do(func() {
		file_workflows_v2_workflow_execution_finished_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflows_v2_workflow_execution_finished_proto_rawDesc), len(file_workflows_v2_workflow_execution_finished_proto_rawDesc)))
	})
	return file_workflows_v2_workflow_execution_finished_proto_rawDescData
}

var file_workflows_v2_workflow_execution_finished_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workflows_v2_workflow_execution_finished_proto_goTypes = []any{
	(*WorkflowExecutionFinished)(nil), // 0: workflows.v2.WorkflowExecutionFinished
	(*CreInfo)(nil),                   // 1: workflows.v2.CreInfo
	(*WorkflowKey)(nil),               // 2: workflows.v2.WorkflowKey
	(ExecutionStatus)(0),              // 3: workflows.v2.ExecutionStatus
	(ClassifiedExecutionStatus)(0),    // 4: workflows.v2.ClassifiedExecutionStatus
}
var file_workflows_v2_workflow_execution_finished_proto_depIdxs = []int32{
	1, // 0: workflows.v2.WorkflowExecutionFinished.creInfo:type_name -> workflows.v2.CreInfo
	2, // 1: workflows.v2.WorkflowExecutionFinished.workflow:type_name -> workflows.v2.WorkflowKey
	3, // 2: workflows.v2.WorkflowExecutionFinished.status:type_name -> workflows.v2.ExecutionStatus
	4, // 3: workflows.v2.WorkflowExecutionFinished.classifiedStatus:type_name -> workflows.v2.ClassifiedExecutionStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_workflows_v2_workflow_execution_finished_proto_init() }
func file_workflows_v2_workflow_execution_finished_proto_init() {
	if File_workflows_v2_workflow_execution_finished_proto != nil {
		return
	}
	file_workflows_v2_cre_info_proto_init()
	file_workflows_v2_workflow_key_proto_init()
	file_workflows_v2_xxx_no_send_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_v2_workflow_execution_finished_proto_rawDesc), len(file_workflows_v2_workflow_execution_finished_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflows_v2_workflow_execution_finished_proto_goTypes,
		DependencyIndexes: file_workflows_v2_workflow_execution_finished_proto_depIdxs,
		MessageInfos:      file_workflows_v2_workflow_execution_finished_proto_msgTypes,
	}.Build()
	File_workflows_v2_workflow_execution_finished_proto = out.File
	file_workflows_v2_workflow_execution_finished_proto_goTypes = nil
	file_workflows_v2_workflow_execution_finished_proto_depIdxs = nil
}
