// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: v1/aggregator.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Aggregator_WriteCommitCCVNodeData_FullMethodName      = "/chainlink_ccv.v1.Aggregator/WriteCommitCCVNodeData"
	Aggregator_BatchWriteCommitCCVNodeData_FullMethodName = "/chainlink_ccv.v1.Aggregator/BatchWriteCommitCCVNodeData"
	Aggregator_ReadCommitCCVNodeData_FullMethodName       = "/chainlink_ccv.v1.Aggregator/ReadCommitCCVNodeData"
	Aggregator_WriteChainStatus_FullMethodName            = "/chainlink_ccv.v1.Aggregator/WriteChainStatus"
	Aggregator_ReadChainStatus_FullMethodName             = "/chainlink_ccv.v1.Aggregator/ReadChainStatus"
)

// AggregatorClient is the client API for Aggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregatorClient interface {
	WriteCommitCCVNodeData(ctx context.Context, in *WriteCommitCCVNodeDataRequest, opts ...grpc.CallOption) (*WriteCommitCCVNodeDataResponse, error)
	BatchWriteCommitCCVNodeData(ctx context.Context, in *BatchWriteCommitCCVNodeDataRequest, opts ...grpc.CallOption) (*BatchWriteCommitCCVNodeDataResponse, error)
	ReadCommitCCVNodeData(ctx context.Context, in *ReadCommitCCVNodeDataRequest, opts ...grpc.CallOption) (*ReadCommitCCVNodeDataResponse, error)
	WriteChainStatus(ctx context.Context, in *WriteChainStatusRequest, opts ...grpc.CallOption) (*WriteChainStatusResponse, error)
	ReadChainStatus(ctx context.Context, in *ReadChainStatusRequest, opts ...grpc.CallOption) (*ReadChainStatusResponse, error)
}

type aggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregatorClient(cc grpc.ClientConnInterface) AggregatorClient {
	return &aggregatorClient{cc}
}

func (c *aggregatorClient) WriteCommitCCVNodeData(ctx context.Context, in *WriteCommitCCVNodeDataRequest, opts ...grpc.CallOption) (*WriteCommitCCVNodeDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteCommitCCVNodeDataResponse)
	err := c.cc.Invoke(ctx, Aggregator_WriteCommitCCVNodeData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorClient) BatchWriteCommitCCVNodeData(ctx context.Context, in *BatchWriteCommitCCVNodeDataRequest, opts ...grpc.CallOption) (*BatchWriteCommitCCVNodeDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchWriteCommitCCVNodeDataResponse)
	err := c.cc.Invoke(ctx, Aggregator_BatchWriteCommitCCVNodeData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorClient) ReadCommitCCVNodeData(ctx context.Context, in *ReadCommitCCVNodeDataRequest, opts ...grpc.CallOption) (*ReadCommitCCVNodeDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCommitCCVNodeDataResponse)
	err := c.cc.Invoke(ctx, Aggregator_ReadCommitCCVNodeData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorClient) WriteChainStatus(ctx context.Context, in *WriteChainStatusRequest, opts ...grpc.CallOption) (*WriteChainStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChainStatusResponse)
	err := c.cc.Invoke(ctx, Aggregator_WriteChainStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregatorClient) ReadChainStatus(ctx context.Context, in *ReadChainStatusRequest, opts ...grpc.CallOption) (*ReadChainStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChainStatusResponse)
	err := c.cc.Invoke(ctx, Aggregator_ReadChainStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregatorServer is the server API for Aggregator service.
// All implementations must embed UnimplementedAggregatorServer
// for forward compatibility.
type AggregatorServer interface {
	WriteCommitCCVNodeData(context.Context, *WriteCommitCCVNodeDataRequest) (*WriteCommitCCVNodeDataResponse, error)
	BatchWriteCommitCCVNodeData(context.Context, *BatchWriteCommitCCVNodeDataRequest) (*BatchWriteCommitCCVNodeDataResponse, error)
	ReadCommitCCVNodeData(context.Context, *ReadCommitCCVNodeDataRequest) (*ReadCommitCCVNodeDataResponse, error)
	WriteChainStatus(context.Context, *WriteChainStatusRequest) (*WriteChainStatusResponse, error)
	ReadChainStatus(context.Context, *ReadChainStatusRequest) (*ReadChainStatusResponse, error)
	mustEmbedUnimplementedAggregatorServer()
}

// UnimplementedAggregatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregatorServer struct{}

func (UnimplementedAggregatorServer) WriteCommitCCVNodeData(context.Context, *WriteCommitCCVNodeDataRequest) (*WriteCommitCCVNodeDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteCommitCCVNodeData not implemented")
}
func (UnimplementedAggregatorServer) BatchWriteCommitCCVNodeData(context.Context, *BatchWriteCommitCCVNodeDataRequest) (*BatchWriteCommitCCVNodeDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchWriteCommitCCVNodeData not implemented")
}
func (UnimplementedAggregatorServer) ReadCommitCCVNodeData(context.Context, *ReadCommitCCVNodeDataRequest) (*ReadCommitCCVNodeDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCommitCCVNodeData not implemented")
}
func (UnimplementedAggregatorServer) WriteChainStatus(context.Context, *WriteChainStatusRequest) (*WriteChainStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteChainStatus not implemented")
}
func (UnimplementedAggregatorServer) ReadChainStatus(context.Context, *ReadChainStatusRequest) (*ReadChainStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadChainStatus not implemented")
}
func (UnimplementedAggregatorServer) mustEmbedUnimplementedAggregatorServer() {}
func (UnimplementedAggregatorServer) testEmbeddedByValue()                    {}

// UnsafeAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregatorServer will
// result in compilation errors.
type UnsafeAggregatorServer interface {
	mustEmbedUnimplementedAggregatorServer()
}

func RegisterAggregatorServer(s grpc.ServiceRegistrar, srv AggregatorServer) {
	// If the following call pancis, it indicates UnimplementedAggregatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Aggregator_ServiceDesc, srv)
}

func _Aggregator_WriteCommitCCVNodeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteCommitCCVNodeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).WriteCommitCCVNodeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aggregator_WriteCommitCCVNodeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).WriteCommitCCVNodeData(ctx, req.(*WriteCommitCCVNodeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aggregator_BatchWriteCommitCCVNodeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchWriteCommitCCVNodeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).BatchWriteCommitCCVNodeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aggregator_BatchWriteCommitCCVNodeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).BatchWriteCommitCCVNodeData(ctx, req.(*BatchWriteCommitCCVNodeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aggregator_ReadCommitCCVNodeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCommitCCVNodeDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).ReadCommitCCVNodeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aggregator_ReadCommitCCVNodeData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).ReadCommitCCVNodeData(ctx, req.(*ReadCommitCCVNodeDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aggregator_WriteChainStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteChainStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).WriteChainStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aggregator_WriteChainStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).WriteChainStatus(ctx, req.(*WriteChainStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aggregator_ReadChainStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChainStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).ReadChainStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aggregator_ReadChainStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).ReadChainStatus(ctx, req.(*ReadChainStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Aggregator_ServiceDesc is the grpc.ServiceDesc for Aggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainlink_ccv.v1.Aggregator",
	HandlerType: (*AggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteCommitCCVNodeData",
			Handler:    _Aggregator_WriteCommitCCVNodeData_Handler,
		},
		{
			MethodName: "BatchWriteCommitCCVNodeData",
			Handler:    _Aggregator_BatchWriteCommitCCVNodeData_Handler,
		},
		{
			MethodName: "ReadCommitCCVNodeData",
			Handler:    _Aggregator_ReadCommitCCVNodeData_Handler,
		},
		{
			MethodName: "WriteChainStatus",
			Handler:    _Aggregator_WriteChainStatus_Handler,
		},
		{
			MethodName: "ReadChainStatus",
			Handler:    _Aggregator_ReadChainStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/aggregator.proto",
}

const (
	VerifierResultAPI_GetVerifierResultForMessage_FullMethodName = "/chainlink_ccv.v1.VerifierResultAPI/GetVerifierResultForMessage"
	VerifierResultAPI_GetMessagesSince_FullMethodName            = "/chainlink_ccv.v1.VerifierResultAPI/GetMessagesSince"
)

// VerifierResultAPIClient is the client API for VerifierResultAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifierResultAPIClient interface {
	GetVerifierResultForMessage(ctx context.Context, in *GetVerifierResultForMessageRequest, opts ...grpc.CallOption) (*VerifierResult, error)
	GetMessagesSince(ctx context.Context, in *GetMessagesSinceRequest, opts ...grpc.CallOption) (*GetMessagesSinceResponse, error)
}

type verifierResultAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierResultAPIClient(cc grpc.ClientConnInterface) VerifierResultAPIClient {
	return &verifierResultAPIClient{cc}
}

func (c *verifierResultAPIClient) GetVerifierResultForMessage(ctx context.Context, in *GetVerifierResultForMessageRequest, opts ...grpc.CallOption) (*VerifierResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifierResult)
	err := c.cc.Invoke(ctx, VerifierResultAPI_GetVerifierResultForMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierResultAPIClient) GetMessagesSince(ctx context.Context, in *GetMessagesSinceRequest, opts ...grpc.CallOption) (*GetMessagesSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesSinceResponse)
	err := c.cc.Invoke(ctx, VerifierResultAPI_GetMessagesSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierResultAPIServer is the server API for VerifierResultAPI service.
// All implementations must embed UnimplementedVerifierResultAPIServer
// for forward compatibility.
type VerifierResultAPIServer interface {
	GetVerifierResultForMessage(context.Context, *GetVerifierResultForMessageRequest) (*VerifierResult, error)
	GetMessagesSince(context.Context, *GetMessagesSinceRequest) (*GetMessagesSinceResponse, error)
	mustEmbedUnimplementedVerifierResultAPIServer()
}

// UnimplementedVerifierResultAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifierResultAPIServer struct{}

func (UnimplementedVerifierResultAPIServer) GetVerifierResultForMessage(context.Context, *GetVerifierResultForMessageRequest) (*VerifierResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerifierResultForMessage not implemented")
}
func (UnimplementedVerifierResultAPIServer) GetMessagesSince(context.Context, *GetMessagesSinceRequest) (*GetMessagesSinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessagesSince not implemented")
}
func (UnimplementedVerifierResultAPIServer) mustEmbedUnimplementedVerifierResultAPIServer() {}
func (UnimplementedVerifierResultAPIServer) testEmbeddedByValue()                           {}

// UnsafeVerifierResultAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifierResultAPIServer will
// result in compilation errors.
type UnsafeVerifierResultAPIServer interface {
	mustEmbedUnimplementedVerifierResultAPIServer()
}

func RegisterVerifierResultAPIServer(s grpc.ServiceRegistrar, srv VerifierResultAPIServer) {
	// If the following call pancis, it indicates UnimplementedVerifierResultAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerifierResultAPI_ServiceDesc, srv)
}

func _VerifierResultAPI_GetVerifierResultForMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerifierResultForMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierResultAPIServer).GetVerifierResultForMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifierResultAPI_GetVerifierResultForMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierResultAPIServer).GetVerifierResultForMessage(ctx, req.(*GetVerifierResultForMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifierResultAPI_GetMessagesSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierResultAPIServer).GetMessagesSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifierResultAPI_GetMessagesSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierResultAPIServer).GetMessagesSince(ctx, req.(*GetMessagesSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifierResultAPI_ServiceDesc is the grpc.ServiceDesc for VerifierResultAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifierResultAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainlink_ccv.v1.VerifierResultAPI",
	HandlerType: (*VerifierResultAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerifierResultForMessage",
			Handler:    _VerifierResultAPI_GetVerifierResultForMessage_Handler,
		},
		{
			MethodName: "GetMessagesSince",
			Handler:    _VerifierResultAPI_GetMessagesSince_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/aggregator.proto",
}
