// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: chainlink-ccv/v1/message-discovery.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageDiscovery_GetMessagesSince_FullMethodName = "/chainlink_ccv.v1.MessageDiscovery/GetMessagesSince"
)

// MessageDiscoveryClient is the client API for MessageDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageDiscoveryClient interface {
	GetMessagesSince(ctx context.Context, in *GetMessagesSinceRequest, opts ...grpc.CallOption) (*GetMessagesSinceResponse, error)
}

type messageDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageDiscoveryClient(cc grpc.ClientConnInterface) MessageDiscoveryClient {
	return &messageDiscoveryClient{cc}
}

func (c *messageDiscoveryClient) GetMessagesSince(ctx context.Context, in *GetMessagesSinceRequest, opts ...grpc.CallOption) (*GetMessagesSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesSinceResponse)
	err := c.cc.Invoke(ctx, MessageDiscovery_GetMessagesSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageDiscoveryServer is the server API for MessageDiscovery service.
// All implementations must embed UnimplementedMessageDiscoveryServer
// for forward compatibility.
type MessageDiscoveryServer interface {
	GetMessagesSince(context.Context, *GetMessagesSinceRequest) (*GetMessagesSinceResponse, error)
	mustEmbedUnimplementedMessageDiscoveryServer()
}

// UnimplementedMessageDiscoveryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageDiscoveryServer struct{}

func (UnimplementedMessageDiscoveryServer) GetMessagesSince(context.Context, *GetMessagesSinceRequest) (*GetMessagesSinceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessagesSince not implemented")
}
func (UnimplementedMessageDiscoveryServer) mustEmbedUnimplementedMessageDiscoveryServer() {}
func (UnimplementedMessageDiscoveryServer) testEmbeddedByValue()                          {}

// UnsafeMessageDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageDiscoveryServer will
// result in compilation errors.
type UnsafeMessageDiscoveryServer interface {
	mustEmbedUnimplementedMessageDiscoveryServer()
}

func RegisterMessageDiscoveryServer(s grpc.ServiceRegistrar, srv MessageDiscoveryServer) {
	// If the following call pancis, it indicates UnimplementedMessageDiscoveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageDiscovery_ServiceDesc, srv)
}

func _MessageDiscovery_GetMessagesSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageDiscoveryServer).GetMessagesSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageDiscovery_GetMessagesSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageDiscoveryServer).GetMessagesSince(ctx, req.(*GetMessagesSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageDiscovery_ServiceDesc is the grpc.ServiceDesc for MessageDiscovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageDiscovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainlink_ccv.v1.MessageDiscovery",
	HandlerType: (*MessageDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessagesSince",
			Handler:    _MessageDiscovery_GetMessagesSince_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainlink-ccv/v1/message-discovery.proto",
}
