// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sdk/v1alpha/sdk.proto

package sdk

import (
	pb "github.com/smartcontractkit/chainlink-protos/cre/go/values/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregationType int32

const (
	AggregationType_AGGREGATION_TYPE_UNSPECIFIED   AggregationType = 0
	AggregationType_AGGREGATION_TYPE_MEDIAN        AggregationType = 1
	AggregationType_AGGREGATION_TYPE_IDENTICAL     AggregationType = 2
	AggregationType_AGGREGATION_TYPE_COMMON_PREFIX AggregationType = 3
	AggregationType_AGGREGATION_TYPE_COMMON_SUFFIX AggregationType = 4
)

// Enum value maps for AggregationType.
var (
	AggregationType_name = map[int32]string{
		0: "AGGREGATION_TYPE_UNSPECIFIED",
		1: "AGGREGATION_TYPE_MEDIAN",
		2: "AGGREGATION_TYPE_IDENTICAL",
		3: "AGGREGATION_TYPE_COMMON_PREFIX",
		4: "AGGREGATION_TYPE_COMMON_SUFFIX",
	}
	AggregationType_value = map[string]int32{
		"AGGREGATION_TYPE_UNSPECIFIED":   0,
		"AGGREGATION_TYPE_MEDIAN":        1,
		"AGGREGATION_TYPE_IDENTICAL":     2,
		"AGGREGATION_TYPE_COMMON_PREFIX": 3,
		"AGGREGATION_TYPE_COMMON_SUFFIX": 4,
	}
)

func (x AggregationType) Enum() *AggregationType {
	p := new(AggregationType)
	*p = x
	return p
}

func (x AggregationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregationType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_v1alpha_sdk_proto_enumTypes[0].Descriptor()
}

func (AggregationType) Type() protoreflect.EnumType {
	return &file_sdk_v1alpha_sdk_proto_enumTypes[0]
}

func (x AggregationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregationType.Descriptor instead.
func (AggregationType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{0}
}

type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_DON         Mode = 1
	Mode_MODE_NODE        Mode = 2
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_DON",
		2: "MODE_NODE",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_DON":         1,
		"MODE_NODE":        2,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_v1alpha_sdk_proto_enumTypes[1].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_sdk_v1alpha_sdk_proto_enumTypes[1]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{1}
}

type TeeType int32

const (
	TeeType_TEE_TYPE_AWS_NITRO TeeType = 0
)

// Enum value maps for TeeType.
var (
	TeeType_name = map[int32]string{
		0: "TEE_TYPE_AWS_NITRO",
	}
	TeeType_value = map[string]int32{
		"TEE_TYPE_AWS_NITRO": 0,
	}
)

func (x TeeType) Enum() *TeeType {
	p := new(TeeType)
	*p = x
	return p
}

func (x TeeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeeType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_v1alpha_sdk_proto_enumTypes[2].Descriptor()
}

func (TeeType) Type() protoreflect.EnumType {
	return &file_sdk_v1alpha_sdk_proto_enumTypes[2]
}

func (x TeeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeeType.Descriptor instead.
func (TeeType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{2}
}

type CapabilityRestrictionType int32

const (
	CapabilityRestrictionType_CAPABILITY_RESTRICTION_TYPE_CLOSED CapabilityRestrictionType = 0
	CapabilityRestrictionType_CAPABILITY_RESTRICTION_TYPE_OPEN   CapabilityRestrictionType = 1
)

// Enum value maps for CapabilityRestrictionType.
var (
	CapabilityRestrictionType_name = map[int32]string{
		0: "CAPABILITY_RESTRICTION_TYPE_CLOSED",
		1: "CAPABILITY_RESTRICTION_TYPE_OPEN",
	}
	CapabilityRestrictionType_value = map[string]int32{
		"CAPABILITY_RESTRICTION_TYPE_CLOSED": 0,
		"CAPABILITY_RESTRICTION_TYPE_OPEN":   1,
	}
)

func (x CapabilityRestrictionType) Enum() *CapabilityRestrictionType {
	p := new(CapabilityRestrictionType)
	*p = x
	return p
}

func (x CapabilityRestrictionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityRestrictionType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_v1alpha_sdk_proto_enumTypes[3].Descriptor()
}

func (CapabilityRestrictionType) Type() protoreflect.EnumType {
	return &file_sdk_v1alpha_sdk_proto_enumTypes[3]
}

func (x CapabilityRestrictionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityRestrictionType.Descriptor instead.
func (CapabilityRestrictionType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{3}
}

type SimpleConsensusInputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Observation:
	//
	//	*SimpleConsensusInputs_Value
	//	*SimpleConsensusInputs_Error
	Observation   isSimpleConsensusInputs_Observation `protobuf_oneof:"observation"`
	Descriptors   *ConsensusDescriptor                `protobuf:"bytes,3,opt,name=descriptors,proto3" json:"descriptors,omitempty"`
	Default       *pb.Value                           `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleConsensusInputs) Reset() {
	*x = SimpleConsensusInputs{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleConsensusInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleConsensusInputs) ProtoMessage() {}

func (x *SimpleConsensusInputs) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleConsensusInputs.ProtoReflect.Descriptor instead.
func (*SimpleConsensusInputs) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleConsensusInputs) GetObservation() isSimpleConsensusInputs_Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *SimpleConsensusInputs) GetValue() *pb.Value {
	if x != nil {
		if x, ok := x.Observation.(*SimpleConsensusInputs_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *SimpleConsensusInputs) GetError() string {
	if x != nil {
		if x, ok := x.Observation.(*SimpleConsensusInputs_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *SimpleConsensusInputs) GetDescriptors() *ConsensusDescriptor {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *SimpleConsensusInputs) GetDefault() *pb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

type isSimpleConsensusInputs_Observation interface {
	isSimpleConsensusInputs_Observation()
}

type SimpleConsensusInputs_Value struct {
	Value *pb.Value `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type SimpleConsensusInputs_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SimpleConsensusInputs_Value) isSimpleConsensusInputs_Observation() {}

func (*SimpleConsensusInputs_Error) isSimpleConsensusInputs_Observation() {}

type FieldsMap struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Fields        map[string]*ConsensusDescriptor `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldsMap) Reset() {
	*x = FieldsMap{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldsMap) ProtoMessage() {}

func (x *FieldsMap) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldsMap.ProtoReflect.Descriptor instead.
func (*FieldsMap) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *FieldsMap) GetFields() map[string]*ConsensusDescriptor {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ConsensusDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Descriptor_:
	//
	//	*ConsensusDescriptor_Aggregation
	//	*ConsensusDescriptor_FieldsMap
	Descriptor_   isConsensusDescriptor_Descriptor_ `protobuf_oneof:"descriptor"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusDescriptor) Reset() {
	*x = ConsensusDescriptor{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusDescriptor) ProtoMessage() {}

func (x *ConsensusDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusDescriptor.ProtoReflect.Descriptor instead.
func (*ConsensusDescriptor) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *ConsensusDescriptor) GetDescriptor_() isConsensusDescriptor_Descriptor_ {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *ConsensusDescriptor) GetAggregation() AggregationType {
	if x != nil {
		if x, ok := x.Descriptor_.(*ConsensusDescriptor_Aggregation); ok {
			return x.Aggregation
		}
	}
	return AggregationType_AGGREGATION_TYPE_UNSPECIFIED
}

func (x *ConsensusDescriptor) GetFieldsMap() *FieldsMap {
	if x != nil {
		if x, ok := x.Descriptor_.(*ConsensusDescriptor_FieldsMap); ok {
			return x.FieldsMap
		}
	}
	return nil
}

type isConsensusDescriptor_Descriptor_ interface {
	isConsensusDescriptor_Descriptor_()
}

type ConsensusDescriptor_Aggregation struct {
	Aggregation AggregationType `protobuf:"varint,1,opt,name=aggregation,proto3,enum=sdk.v1alpha.AggregationType,oneof"`
}

type ConsensusDescriptor_FieldsMap struct {
	FieldsMap *FieldsMap `protobuf:"bytes,2,opt,name=fields_map,json=fieldsMap,proto3,oneof"`
}

func (*ConsensusDescriptor_Aggregation) isConsensusDescriptor_Descriptor_() {}

func (*ConsensusDescriptor_FieldsMap) isConsensusDescriptor_Descriptor_() {}

type ReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EncodedPayload []byte                 `protobuf:"bytes,1,opt,name=encoded_payload,json=encodedPayload,proto3" json:"encoded_payload,omitempty"`
	EncoderName    string                 `protobuf:"bytes,2,opt,name=encoder_name,json=encoderName,proto3" json:"encoder_name,omitempty"`
	SigningAlgo    string                 `protobuf:"bytes,3,opt,name=signing_algo,json=signingAlgo,proto3" json:"signing_algo,omitempty"`
	HashingAlgo    string                 `protobuf:"bytes,4,opt,name=hashing_algo,json=hashingAlgo,proto3" json:"hashing_algo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *ReportRequest) GetEncodedPayload() []byte {
	if x != nil {
		return x.EncodedPayload
	}
	return nil
}

func (x *ReportRequest) GetEncoderName() string {
	if x != nil {
		return x.EncoderName
	}
	return ""
}

func (x *ReportRequest) GetSigningAlgo() string {
	if x != nil {
		return x.SigningAlgo
	}
	return ""
}

func (x *ReportRequest) GetHashingAlgo() string {
	if x != nil {
		return x.HashingAlgo
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest  []byte                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	SeqNr         uint64                 `protobuf:"varint,2,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	ReportContext []byte                 `protobuf:"bytes,3,opt,name=report_context,json=reportContext,proto3" json:"report_context,omitempty"` // combination of seq_nr and config_digest
	RawReport     []byte                 `protobuf:"bytes,4,opt,name=raw_report,json=rawReport,proto3" json:"raw_report,omitempty"`
	Sigs          []*AttributedSignature `protobuf:"bytes,5,rep,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *ReportResponse) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *ReportResponse) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *ReportResponse) GetReportContext() []byte {
	if x != nil {
		return x.ReportContext
	}
	return nil
}

func (x *ReportResponse) GetRawReport() []byte {
	if x != nil {
		return x.RawReport
	}
	return nil
}

func (x *ReportResponse) GetSigs() []*AttributedSignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type AttributedSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	SignerId      uint32                 `protobuf:"varint,2,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributedSignature) Reset() {
	*x = AttributedSignature{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributedSignature) ProtoMessage() {}

func (x *AttributedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributedSignature.ProtoReflect.Descriptor instead.
func (*AttributedSignature) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{5}
}

func (x *AttributedSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AttributedSignature) GetSignerId() uint32 {
	if x != nil {
		return x.SignerId
	}
	return 0
}

type CapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	CallbackId    int32                  `protobuf:"varint,4,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CapabilityRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CapabilityRequest) GetCallbackId() int32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

type CapabilityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CapabilityResponse_Payload
	//	*CapabilityResponse_Error
	Response      isCapabilityResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityResponse) Reset() {
	*x = CapabilityResponse{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityResponse) ProtoMessage() {}

func (x *CapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityResponse.ProtoReflect.Descriptor instead.
func (*CapabilityResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilityResponse) GetResponse() isCapabilityResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CapabilityResponse) GetPayload() *anypb.Any {
	if x != nil {
		if x, ok := x.Response.(*CapabilityResponse_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *CapabilityResponse) GetError() string {
	if x != nil {
		if x, ok := x.Response.(*CapabilityResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isCapabilityResponse_Response interface {
	isCapabilityResponse_Response()
}

type CapabilityResponse_Payload struct {
	Payload *anypb.Any `protobuf:"bytes,1,opt,name=payload,proto3,oneof"`
}

type CapabilityResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CapabilityResponse_Payload) isCapabilityResponse_Response() {}

func (*CapabilityResponse_Error) isCapabilityResponse_Response() {}

type TriggerSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Requirements  *Requirements          `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`
	PreHook       bool                   `protobuf:"varint,5,opt,name=pre_hook,json=preHook,proto3" json:"pre_hook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSubscription) Reset() {
	*x = TriggerSubscription{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSubscription) ProtoMessage() {}

func (x *TriggerSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSubscription.ProtoReflect.Descriptor instead.
func (*TriggerSubscription) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{8}
}

func (x *TriggerSubscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TriggerSubscription) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TriggerSubscription) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TriggerSubscription) GetRequirements() *Requirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *TriggerSubscription) GetPreHook() bool {
	if x != nil {
		return x.PreHook
	}
	return false
}

type TeeTypeAndRegions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TeeType                `protobuf:"varint,1,opt,name=type,proto3,enum=sdk.v1alpha.TeeType" json:"type,omitempty"`
	Regions       []string               `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeeTypeAndRegions) Reset() {
	*x = TeeTypeAndRegions{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeeTypeAndRegions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeeTypeAndRegions) ProtoMessage() {}

func (x *TeeTypeAndRegions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeeTypeAndRegions.ProtoReflect.Descriptor instead.
func (*TeeTypeAndRegions) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{9}
}

func (x *TeeTypeAndRegions) GetType() TeeType {
	if x != nil {
		return x.Type
	}
	return TeeType_TEE_TYPE_AWS_NITRO
}

func (x *TeeTypeAndRegions) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type TeeTypeSelection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*TeeTypeAndRegions   `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeeTypeSelection) Reset() {
	*x = TeeTypeSelection{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeeTypeSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeeTypeSelection) ProtoMessage() {}

func (x *TeeTypeSelection) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeeTypeSelection.ProtoReflect.Descriptor instead.
func (*TeeTypeSelection) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{10}
}

func (x *TeeTypeSelection) GetTypes() []*TeeTypeAndRegions {
	if x != nil {
		return x.Types
	}
	return nil
}

type Tee struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Tee_Any
	//	*Tee_TypeSelection
	Type          isTee_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tee) Reset() {
	*x = Tee{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tee) ProtoMessage() {}

func (x *Tee) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tee.ProtoReflect.Descriptor instead.
func (*Tee) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{11}
}

func (x *Tee) GetType() isTee_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Tee) GetAny() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Type.(*Tee_Any); ok {
			return x.Any
		}
	}
	return nil
}

func (x *Tee) GetTypeSelection() *TeeTypeSelection {
	if x != nil {
		if x, ok := x.Type.(*Tee_TypeSelection); ok {
			return x.TypeSelection
		}
	}
	return nil
}

type isTee_Type interface {
	isTee_Type()
}

type Tee_Any struct {
	Any *emptypb.Empty `protobuf:"bytes,1,opt,name=any,proto3,oneof"`
}

type Tee_TypeSelection struct {
	TypeSelection *TeeTypeSelection `protobuf:"bytes,2,opt,name=type_selection,json=typeSelection,proto3,oneof"`
}

func (*Tee_Any) isTee_Type() {}

func (*Tee_TypeSelection) isTee_Type() {}

type TriggerSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*TriggerSubscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSubscriptionRequest) Reset() {
	*x = TriggerSubscriptionRequest{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSubscriptionRequest) ProtoMessage() {}

func (x *TriggerSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*TriggerSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerSubscriptionRequest) GetSubscriptions() []*TriggerSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{13}
}

func (x *Trigger) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trigger) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Requirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tee           *Tee                   `protobuf:"bytes,1,opt,name=tee,proto3" json:"tee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirements) Reset() {
	*x = Requirements{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirements) ProtoMessage() {}

func (x *Requirements) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirements.ProtoReflect.Descriptor instead.
func (*Requirements) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{14}
}

func (x *Requirements) GetTee() *Tee {
	if x != nil {
		return x.Tee
	}
	return nil
}

type AwaitCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitCapabilitiesRequest) Reset() {
	*x = AwaitCapabilitiesRequest{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitCapabilitiesRequest) ProtoMessage() {}

func (x *AwaitCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*AwaitCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{15}
}

func (x *AwaitCapabilitiesRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AwaitCapabilitiesResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Responses     map[int32]*CapabilityResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitCapabilitiesResponse) Reset() {
	*x = AwaitCapabilitiesResponse{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitCapabilitiesResponse) ProtoMessage() {}

func (x *AwaitCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*AwaitCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{16}
}

func (x *AwaitCapabilitiesResponse) GetResponses() map[int32]*CapabilityResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ExecuteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Config []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*ExecuteRequest_Subscribe
	//	*ExecuteRequest_Trigger
	//	*ExecuteRequest_PreHook
	Request         isExecuteRequest_Request `protobuf_oneof:"request"`
	MaxResponseSize uint64                   `protobuf:"varint,4,opt,name=max_response_size,json=maxResponseSize,proto3" json:"max_response_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecuteRequest) GetRequest() isExecuteRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecuteRequest) GetSubscribe() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Request.(*ExecuteRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ExecuteRequest) GetTrigger() *Trigger {
	if x != nil {
		if x, ok := x.Request.(*ExecuteRequest_Trigger); ok {
			return x.Trigger
		}
	}
	return nil
}

func (x *ExecuteRequest) GetPreHook() *Trigger {
	if x != nil {
		if x, ok := x.Request.(*ExecuteRequest_PreHook); ok {
			return x.PreHook
		}
	}
	return nil
}

func (x *ExecuteRequest) GetMaxResponseSize() uint64 {
	if x != nil {
		return x.MaxResponseSize
	}
	return 0
}

type isExecuteRequest_Request interface {
	isExecuteRequest_Request()
}

type ExecuteRequest_Subscribe struct {
	Subscribe *emptypb.Empty `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type ExecuteRequest_Trigger struct {
	Trigger *Trigger `protobuf:"bytes,3,opt,name=trigger,proto3,oneof"`
}

type ExecuteRequest_PreHook struct {
	PreHook *Trigger `protobuf:"bytes,5,opt,name=pre_hook,json=preHook,proto3,oneof"`
}

func (*ExecuteRequest_Subscribe) isExecuteRequest_Request() {}

func (*ExecuteRequest_Trigger) isExecuteRequest_Request() {}

func (*ExecuteRequest_PreHook) isExecuteRequest_Request() {}

type ExecutionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecutionResult_Value
	//	*ExecutionResult_Error
	//	*ExecutionResult_TriggerSubscriptions
	//	*ExecutionResult_Restrictions
	Result        isExecutionResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{18}
}

func (x *ExecutionResult) GetResult() isExecutionResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecutionResult) GetValue() *pb.Value {
	if x != nil {
		if x, ok := x.Result.(*ExecutionResult_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *ExecutionResult) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ExecutionResult_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *ExecutionResult) GetTriggerSubscriptions() *TriggerSubscriptionRequest {
	if x != nil {
		if x, ok := x.Result.(*ExecutionResult_TriggerSubscriptions); ok {
			return x.TriggerSubscriptions
		}
	}
	return nil
}

func (x *ExecutionResult) GetRestrictions() *Restrictions {
	if x != nil {
		if x, ok := x.Result.(*ExecutionResult_Restrictions); ok {
			return x.Restrictions
		}
	}
	return nil
}

type isExecutionResult_Result interface {
	isExecutionResult_Result()
}

type ExecutionResult_Value struct {
	Value *pb.Value `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type ExecutionResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type ExecutionResult_TriggerSubscriptions struct {
	TriggerSubscriptions *TriggerSubscriptionRequest `protobuf:"bytes,3,opt,name=trigger_subscriptions,json=triggerSubscriptions,proto3,oneof"`
}

type ExecutionResult_Restrictions struct {
	Restrictions *Restrictions `protobuf:"bytes,4,opt,name=restrictions,proto3,oneof"`
}

func (*ExecutionResult_Value) isExecutionResult_Result() {}

func (*ExecutionResult_Error) isExecutionResult_Result() {}

func (*ExecutionResult_TriggerSubscriptions) isExecutionResult_Result() {}

func (*ExecutionResult_Restrictions) isExecutionResult_Result() {}

type GetSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*SecretRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	CallbackId    int32                  `protobuf:"varint,2,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{19}
}

func (x *GetSecretsRequest) GetRequests() []*SecretRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *GetSecretsRequest) GetCallbackId() int32 {
	if x != nil {
		return x.CallbackId
	}
	return 0
}

type AwaitSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitSecretsRequest) Reset() {
	*x = AwaitSecretsRequest{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitSecretsRequest) ProtoMessage() {}

func (x *AwaitSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitSecretsRequest.ProtoReflect.Descriptor instead.
func (*AwaitSecretsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{20}
}

func (x *AwaitSecretsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type AwaitSecretsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Responses     map[int32]*SecretResponses `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitSecretsResponse) Reset() {
	*x = AwaitSecretsResponse{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitSecretsResponse) ProtoMessage() {}

func (x *AwaitSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitSecretsResponse.ProtoReflect.Descriptor instead.
func (*AwaitSecretsResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{21}
}

func (x *AwaitSecretsResponse) GetResponses() map[int32]*SecretResponses {
	if x != nil {
		return x.Responses
	}
	return nil
}

type SecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRequest) Reset() {
	*x = SecretRequest{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRequest) ProtoMessage() {}

func (x *SecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRequest.ProtoReflect.Descriptor instead.
func (*SecretRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{22}
}

func (x *SecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{23}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Secret) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Secret) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SecretError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretError) Reset() {
	*x = SecretError{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretError) ProtoMessage() {}

func (x *SecretError) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretError.ProtoReflect.Descriptor instead.
func (*SecretError) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{24}
}

func (x *SecretError) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretError) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SecretError) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SecretError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SecretResponse_Secret
	//	*SecretResponse_Error
	Response      isSecretResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretResponse) Reset() {
	*x = SecretResponse{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretResponse) ProtoMessage() {}

func (x *SecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretResponse.ProtoReflect.Descriptor instead.
func (*SecretResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{25}
}

func (x *SecretResponse) GetResponse() isSecretResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SecretResponse) GetSecret() *Secret {
	if x != nil {
		if x, ok := x.Response.(*SecretResponse_Secret); ok {
			return x.Secret
		}
	}
	return nil
}

func (x *SecretResponse) GetError() *SecretError {
	if x != nil {
		if x, ok := x.Response.(*SecretResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSecretResponse_Response interface {
	isSecretResponse_Response()
}

type SecretResponse_Secret struct {
	Secret *Secret `protobuf:"bytes,1,opt,name=secret,proto3,oneof"`
}

type SecretResponse_Error struct {
	Error *SecretError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SecretResponse_Secret) isSecretResponse_Response() {}

func (*SecretResponse_Error) isSecretResponse_Response() {}

type SecretResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*SecretResponse      `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretResponses) Reset() {
	*x = SecretResponses{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretResponses) ProtoMessage() {}

func (x *SecretResponses) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretResponses.ProtoReflect.Descriptor instead.
func (*SecretResponses) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{26}
}

func (x *SecretResponses) GetResponses() []*SecretResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type MethodRestriction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	MaxCalls      int32                  `protobuf:"varint,3,opt,name=max_calls,json=maxCalls,proto3" json:"max_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodRestriction) Reset() {
	*x = MethodRestriction{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodRestriction) ProtoMessage() {}

func (x *MethodRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodRestriction.ProtoReflect.Descriptor instead.
func (*MethodRestriction) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{27}
}

func (x *MethodRestriction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MethodRestriction) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MethodRestriction) GetMaxCalls() int32 {
	if x != nil {
		return x.MaxCalls
	}
	return 0
}

type CapabilityRestriction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Restriction:
	//
	//	*CapabilityRestriction_Method
	Restriction   isCapabilityRestriction_Restriction `protobuf_oneof:"restriction"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRestriction) Reset() {
	*x = CapabilityRestriction{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRestriction) ProtoMessage() {}

func (x *CapabilityRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRestriction.ProtoReflect.Descriptor instead.
func (*CapabilityRestriction) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{28}
}

func (x *CapabilityRestriction) GetRestriction() isCapabilityRestriction_Restriction {
	if x != nil {
		return x.Restriction
	}
	return nil
}

func (x *CapabilityRestriction) GetMethod() *MethodRestriction {
	if x != nil {
		if x, ok := x.Restriction.(*CapabilityRestriction_Method); ok {
			return x.Method
		}
	}
	return nil
}

type isCapabilityRestriction_Restriction interface {
	isCapabilityRestriction_Restriction()
}

type CapabilityRestriction_Method struct {
	Method *MethodRestriction `protobuf:"bytes,1,opt,name=method,proto3,oneof"`
}

func (*CapabilityRestriction_Method) isCapabilityRestriction_Restriction() {}

type CapabilityRestrictions struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Restrictions  []*CapabilityRestriction  `protobuf:"bytes,1,rep,name=restrictions,proto3" json:"restrictions,omitempty"`
	MaxTotalCalls int32                     `protobuf:"varint,2,opt,name=max_total_calls,json=maxTotalCalls,proto3" json:"max_total_calls,omitempty"`
	Type          CapabilityRestrictionType `protobuf:"varint,3,opt,name=type,proto3,enum=sdk.v1alpha.CapabilityRestrictionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRestrictions) Reset() {
	*x = CapabilityRestrictions{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRestrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRestrictions) ProtoMessage() {}

func (x *CapabilityRestrictions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRestrictions.ProtoReflect.Descriptor instead.
func (*CapabilityRestrictions) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{29}
}

func (x *CapabilityRestrictions) GetRestrictions() []*CapabilityRestriction {
	if x != nil {
		return x.Restrictions
	}
	return nil
}

func (x *CapabilityRestrictions) GetMaxTotalCalls() int32 {
	if x != nil {
		return x.MaxTotalCalls
	}
	return 0
}

func (x *CapabilityRestrictions) GetType() CapabilityRestrictionType {
	if x != nil {
		return x.Type
	}
	return CapabilityRestrictionType_CAPABILITY_RESTRICTION_TYPE_CLOSED
}

type SecretPrefixRestriction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MaxSecrets    int32                  `protobuf:"varint,3,opt,name=max_secrets,json=maxSecrets,proto3" json:"max_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretPrefixRestriction) Reset() {
	*x = SecretPrefixRestriction{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretPrefixRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretPrefixRestriction) ProtoMessage() {}

func (x *SecretPrefixRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretPrefixRestriction.ProtoReflect.Descriptor instead.
func (*SecretPrefixRestriction) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{30}
}

func (x *SecretPrefixRestriction) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SecretPrefixRestriction) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SecretPrefixRestriction) GetMaxSecrets() int32 {
	if x != nil {
		return x.MaxSecrets
	}
	return 0
}

type SecretRestriction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Restriction:
	//
	//	*SecretRestriction_ExactSecret
	//	*SecretRestriction_PrefixedSecret
	Restriction   isSecretRestriction_Restriction `protobuf_oneof:"restriction"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRestriction) Reset() {
	*x = SecretRestriction{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRestriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRestriction) ProtoMessage() {}

func (x *SecretRestriction) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRestriction.ProtoReflect.Descriptor instead.
func (*SecretRestriction) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{31}
}

func (x *SecretRestriction) GetRestriction() isSecretRestriction_Restriction {
	if x != nil {
		return x.Restriction
	}
	return nil
}

func (x *SecretRestriction) GetExactSecret() *Secret {
	if x != nil {
		if x, ok := x.Restriction.(*SecretRestriction_ExactSecret); ok {
			return x.ExactSecret
		}
	}
	return nil
}

func (x *SecretRestriction) GetPrefixedSecret() *SecretPrefixRestriction {
	if x != nil {
		if x, ok := x.Restriction.(*SecretRestriction_PrefixedSecret); ok {
			return x.PrefixedSecret
		}
	}
	return nil
}

type isSecretRestriction_Restriction interface {
	isSecretRestriction_Restriction()
}

type SecretRestriction_ExactSecret struct {
	ExactSecret *Secret `protobuf:"bytes,1,opt,name=exact_secret,json=exactSecret,proto3,oneof"`
}

type SecretRestriction_PrefixedSecret struct {
	PrefixedSecret *SecretPrefixRestriction `protobuf:"bytes,2,opt,name=prefixed_secret,json=prefixedSecret,proto3,oneof"`
}

func (*SecretRestriction_ExactSecret) isSecretRestriction_Restriction() {}

func (*SecretRestriction_PrefixedSecret) isSecretRestriction_Restriction() {}

type SecretsRestritions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restrictions  []*SecretRestriction   `protobuf:"bytes,1,rep,name=restrictions,proto3" json:"restrictions,omitempty"`
	MaxSecrets    int32                  `protobuf:"varint,2,opt,name=max_secrets,json=maxSecrets,proto3" json:"max_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsRestritions) Reset() {
	*x = SecretsRestritions{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsRestritions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsRestritions) ProtoMessage() {}

func (x *SecretsRestritions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsRestritions.ProtoReflect.Descriptor instead.
func (*SecretsRestritions) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{32}
}

func (x *SecretsRestritions) GetRestrictions() []*SecretRestriction {
	if x != nil {
		return x.Restrictions
	}
	return nil
}

func (x *SecretsRestritions) GetMaxSecrets() int32 {
	if x != nil {
		return x.MaxSecrets
	}
	return 0
}

type Restrictions struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Secrets       *SecretsRestritions     `protobuf:"bytes,1,opt,name=secrets,proto3" json:"secrets,omitempty"`
	Capabilities  *CapabilityRestrictions `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restrictions) Reset() {
	*x = Restrictions{}
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restrictions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restrictions) ProtoMessage() {}

func (x *Restrictions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1alpha_sdk_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restrictions.ProtoReflect.Descriptor instead.
func (*Restrictions) Descriptor() ([]byte, []int) {
	return file_sdk_v1alpha_sdk_proto_rawDescGZIP(), []int{33}
}

func (x *Restrictions) GetSecrets() *SecretsRestritions {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *Restrictions) GetCapabilities() *CapabilityRestrictions {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_sdk_v1alpha_sdk_proto protoreflect.FileDescriptor

const file_sdk_v1alpha_sdk_proto_rawDesc = "" +
	"\n" +
	"\x15sdk/v1alpha/sdk.proto\x12\vsdk.v1alpha\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16values/v1/values.proto\"\xd8\x01\n" +
	"\x15SimpleConsensusInputs\x12(\n" +
	"\x05value\x18\x01 \x01(\v2\x10.values.v1.ValueH\x00R\x05value\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12B\n" +
	"\vdescriptors\x18\x03 \x01(\v2 .sdk.v1alpha.ConsensusDescriptorR\vdescriptors\x12*\n" +
	"\adefault\x18\x04 \x01(\v2\x10.values.v1.ValueR\adefaultB\r\n" +
	"\vobservation\"\xa4\x01\n" +
	"\tFieldsMap\x12:\n" +
	"\x06fields\x18\x01 \x03(\v2\".sdk.v1alpha.FieldsMap.FieldsEntryR\x06fields\x1a[\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .sdk.v1alpha.ConsensusDescriptorR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x13ConsensusDescriptor\x12@\n" +
	"\vaggregation\x18\x01 \x01(\x0e2\x1c.sdk.v1alpha.AggregationTypeH\x00R\vaggregation\x127\n" +
	"\n" +
	"fields_map\x18\x02 \x01(\v2\x16.sdk.v1alpha.FieldsMapH\x00R\tfieldsMapB\f\n" +
	"\n" +
	"descriptor\"\xa1\x01\n" +
	"\rReportRequest\x12'\n" +
	"\x0fencoded_payload\x18\x01 \x01(\fR\x0eencodedPayload\x12!\n" +
	"\fencoder_name\x18\x02 \x01(\tR\vencoderName\x12!\n" +
	"\fsigning_algo\x18\x03 \x01(\tR\vsigningAlgo\x12!\n" +
	"\fhashing_algo\x18\x04 \x01(\tR\vhashingAlgo\"\xc8\x01\n" +
	"\x0eReportResponse\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\fR\fconfigDigest\x12\x15\n" +
	"\x06seq_nr\x18\x02 \x01(\x04R\x05seqNr\x12%\n" +
	"\x0ereport_context\x18\x03 \x01(\fR\rreportContext\x12\x1d\n" +
	"\n" +
	"raw_report\x18\x04 \x01(\fR\trawReport\x124\n" +
	"\x04sigs\x18\x05 \x03(\v2 .sdk.v1alpha.AttributedSignatureR\x04sigs\"P\n" +
	"\x13AttributedSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigner_id\x18\x02 \x01(\rR\bsignerId\"\x8c\x01\n" +
	"\x11CapabilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1f\n" +
	"\vcallback_id\x18\x04 \x01(\x05R\n" +
	"callbackId\"j\n" +
	"\x12CapabilityResponse\x120\n" +
	"\apayload\x18\x01 \x01(\v2\x14.google.protobuf.AnyH\x00R\apayload\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xc7\x01\n" +
	"\x13TriggerSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12=\n" +
	"\frequirements\x18\x04 \x01(\v2\x19.sdk.v1alpha.RequirementsR\frequirements\x12\x19\n" +
	"\bpre_hook\x18\x05 \x01(\bR\apreHook\"W\n" +
	"\x11TeeTypeAndRegions\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.sdk.v1alpha.TeeTypeR\x04type\x12\x18\n" +
	"\aregions\x18\x02 \x03(\tR\aregions\"H\n" +
	"\x10TeeTypeSelection\x124\n" +
	"\x05types\x18\x01 \x03(\v2\x1e.sdk.v1alpha.TeeTypeAndRegionsR\x05types\"\x81\x01\n" +
	"\x03Tee\x12*\n" +
	"\x03any\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x03any\x12F\n" +
	"\x0etype_selection\x18\x02 \x01(\v2\x1d.sdk.v1alpha.TeeTypeSelectionH\x00R\rtypeSelectionB\x06\n" +
	"\x04type\"d\n" +
	"\x1aTriggerSubscriptionRequest\x12F\n" +
	"\rsubscriptions\x18\x01 \x03(\v2 .sdk.v1alpha.TriggerSubscriptionR\rsubscriptions\"I\n" +
	"\aTrigger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\"2\n" +
	"\fRequirements\x12\"\n" +
	"\x03tee\x18\x01 \x01(\v2\x10.sdk.v1alpha.TeeR\x03tee\",\n" +
	"\x18AwaitCapabilitiesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"\xcf\x01\n" +
	"\x19AwaitCapabilitiesResponse\x12S\n" +
	"\tresponses\x18\x01 \x03(\v25.sdk.v1alpha.AwaitCapabilitiesResponse.ResponsesEntryR\tresponses\x1a]\n" +
	"\x0eResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.sdk.v1alpha.CapabilityResponseR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x126\n" +
	"\tsubscribe\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\tsubscribe\x120\n" +
	"\atrigger\x18\x03 \x01(\v2\x14.sdk.v1alpha.TriggerH\x00R\atrigger\x121\n" +
	"\bpre_hook\x18\x05 \x01(\v2\x14.sdk.v1alpha.TriggerH\x00R\apreHook\x12*\n" +
	"\x11max_response_size\x18\x04 \x01(\x04R\x0fmaxResponseSizeB\t\n" +
	"\arequest\"\xfe\x01\n" +
	"\x0fExecutionResult\x12(\n" +
	"\x05value\x18\x01 \x01(\v2\x10.values.v1.ValueH\x00R\x05value\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12^\n" +
	"\x15trigger_subscriptions\x18\x03 \x01(\v2'.sdk.v1alpha.TriggerSubscriptionRequestH\x00R\x14triggerSubscriptions\x12?\n" +
	"\frestrictions\x18\x04 \x01(\v2\x19.sdk.v1alpha.RestrictionsH\x00R\frestrictionsB\b\n" +
	"\x06result\"l\n" +
	"\x11GetSecretsRequest\x126\n" +
	"\brequests\x18\x01 \x03(\v2\x1a.sdk.v1alpha.SecretRequestR\brequests\x12\x1f\n" +
	"\vcallback_id\x18\x02 \x01(\x05R\n" +
	"callbackId\"'\n" +
	"\x13AwaitSecretsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"\xc2\x01\n" +
	"\x14AwaitSecretsResponse\x12N\n" +
	"\tresponses\x18\x01 \x03(\v20.sdk.v1alpha.AwaitSecretsResponse.ResponsesEntryR\tresponses\x1aZ\n" +
	"\x0eResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.sdk.v1alpha.SecretResponsesR\x05value:\x028\x01\"=\n" +
	"\rSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"b\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"g\n" +
	"\vSecretError\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"}\n" +
	"\x0eSecretResponse\x12-\n" +
	"\x06secret\x18\x01 \x01(\v2\x13.sdk.v1alpha.SecretH\x00R\x06secret\x120\n" +
	"\x05error\x18\x02 \x01(\v2\x18.sdk.v1alpha.SecretErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"L\n" +
	"\x0fSecretResponses\x129\n" +
	"\tresponses\x18\x01 \x03(\v2\x1b.sdk.v1alpha.SecretResponseR\tresponses\"X\n" +
	"\x11MethodRestriction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1b\n" +
	"\tmax_calls\x18\x03 \x01(\x05R\bmaxCalls\"`\n" +
	"\x15CapabilityRestriction\x128\n" +
	"\x06method\x18\x01 \x01(\v2\x1e.sdk.v1alpha.MethodRestrictionH\x00R\x06methodB\r\n" +
	"\vrestriction\"\xc4\x01\n" +
	"\x16CapabilityRestrictions\x12F\n" +
	"\frestrictions\x18\x01 \x03(\v2\".sdk.v1alpha.CapabilityRestrictionR\frestrictions\x12&\n" +
	"\x0fmax_total_calls\x18\x02 \x01(\x05R\rmaxTotalCalls\x12:\n" +
	"\x04type\x18\x03 \x01(\x0e2&.sdk.v1alpha.CapabilityRestrictionTypeR\x04type\"p\n" +
	"\x17SecretPrefixRestriction\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vmax_secrets\x18\x03 \x01(\x05R\n" +
	"maxSecrets\"\xad\x01\n" +
	"\x11SecretRestriction\x128\n" +
	"\fexact_secret\x18\x01 \x01(\v2\x13.sdk.v1alpha.SecretH\x00R\vexactSecret\x12O\n" +
	"\x0fprefixed_secret\x18\x02 \x01(\v2$.sdk.v1alpha.SecretPrefixRestrictionH\x00R\x0eprefixedSecretB\r\n" +
	"\vrestriction\"y\n" +
	"\x12SecretsRestritions\x12B\n" +
	"\frestrictions\x18\x01 \x03(\v2\x1e.sdk.v1alpha.SecretRestrictionR\frestrictions\x12\x1f\n" +
	"\vmax_secrets\x18\x02 \x01(\x05R\n" +
	"maxSecrets\"\x92\x01\n" +
	"\fRestrictions\x129\n" +
	"\asecrets\x18\x01 \x01(\v2\x1f.sdk.v1alpha.SecretsRestritionsR\asecrets\x12G\n" +
	"\fcapabilities\x18\x02 \x01(\v2#.sdk.v1alpha.CapabilityRestrictionsR\fcapabilities*\xb8\x01\n" +
	"\x0fAggregationType\x12 \n" +
	"\x1cAGGREGATION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17AGGREGATION_TYPE_MEDIAN\x10\x01\x12\x1e\n" +
	"\x1aAGGREGATION_TYPE_IDENTICAL\x10\x02\x12\"\n" +
	"\x1eAGGREGATION_TYPE_COMMON_PREFIX\x10\x03\x12\"\n" +
	"\x1eAGGREGATION_TYPE_COMMON_SUFFIX\x10\x04*9\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bMODE_DON\x10\x01\x12\r\n" +
	"\tMODE_NODE\x10\x02*!\n" +
	"\aTeeType\x12\x16\n" +
	"\x12TEE_TYPE_AWS_NITRO\x10\x00*i\n" +
	"\x19CapabilityRestrictionType\x12&\n" +
	"\"CAPABILITY_RESTRICTION_TYPE_CLOSED\x10\x00\x12$\n" +
	" CAPABILITY_RESTRICTION_TYPE_OPEN\x10\x01b\x06proto3"

var (
	file_sdk_v1alpha_sdk_proto_rawDescOnce sync.Once
	file_sdk_v1alpha_sdk_proto_rawDescData []byte
)

func file_sdk_v1alpha_sdk_proto_rawDescGZIP() []byte {
	file_sdk_v1alpha_sdk_proto_rawDescOnce.Do(func() {
		file_sdk_v1alpha_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_v1alpha_sdk_proto_rawDesc), len(file_sdk_v1alpha_sdk_proto_rawDesc)))
	})
	return file_sdk_v1alpha_sdk_proto_rawDescData
}

var file_sdk_v1alpha_sdk_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sdk_v1alpha_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_sdk_v1alpha_sdk_proto_goTypes = []any{
	(AggregationType)(0),               // 0: sdk.v1alpha.AggregationType
	(Mode)(0),                          // 1: sdk.v1alpha.Mode
	(TeeType)(0),                       // 2: sdk.v1alpha.TeeType
	(CapabilityRestrictionType)(0),     // 3: sdk.v1alpha.CapabilityRestrictionType
	(*SimpleConsensusInputs)(nil),      // 4: sdk.v1alpha.SimpleConsensusInputs
	(*FieldsMap)(nil),                  // 5: sdk.v1alpha.FieldsMap
	(*ConsensusDescriptor)(nil),        // 6: sdk.v1alpha.ConsensusDescriptor
	(*ReportRequest)(nil),              // 7: sdk.v1alpha.ReportRequest
	(*ReportResponse)(nil),             // 8: sdk.v1alpha.ReportResponse
	(*AttributedSignature)(nil),        // 9: sdk.v1alpha.AttributedSignature
	(*CapabilityRequest)(nil),          // 10: sdk.v1alpha.CapabilityRequest
	(*CapabilityResponse)(nil),         // 11: sdk.v1alpha.CapabilityResponse
	(*TriggerSubscription)(nil),        // 12: sdk.v1alpha.TriggerSubscription
	(*TeeTypeAndRegions)(nil),          // 13: sdk.v1alpha.TeeTypeAndRegions
	(*TeeTypeSelection)(nil),           // 14: sdk.v1alpha.TeeTypeSelection
	(*Tee)(nil),                        // 15: sdk.v1alpha.Tee
	(*TriggerSubscriptionRequest)(nil), // 16: sdk.v1alpha.TriggerSubscriptionRequest
	(*Trigger)(nil),                    // 17: sdk.v1alpha.Trigger
	(*Requirements)(nil),               // 18: sdk.v1alpha.Requirements
	(*AwaitCapabilitiesRequest)(nil),   // 19: sdk.v1alpha.AwaitCapabilitiesRequest
	(*AwaitCapabilitiesResponse)(nil),  // 20: sdk.v1alpha.AwaitCapabilitiesResponse
	(*ExecuteRequest)(nil),             // 21: sdk.v1alpha.ExecuteRequest
	(*ExecutionResult)(nil),            // 22: sdk.v1alpha.ExecutionResult
	(*GetSecretsRequest)(nil),          // 23: sdk.v1alpha.GetSecretsRequest
	(*AwaitSecretsRequest)(nil),        // 24: sdk.v1alpha.AwaitSecretsRequest
	(*AwaitSecretsResponse)(nil),       // 25: sdk.v1alpha.AwaitSecretsResponse
	(*SecretRequest)(nil),              // 26: sdk.v1alpha.SecretRequest
	(*Secret)(nil),                     // 27: sdk.v1alpha.Secret
	(*SecretError)(nil),                // 28: sdk.v1alpha.SecretError
	(*SecretResponse)(nil),             // 29: sdk.v1alpha.SecretResponse
	(*SecretResponses)(nil),            // 30: sdk.v1alpha.SecretResponses
	(*MethodRestriction)(nil),          // 31: sdk.v1alpha.MethodRestriction
	(*CapabilityRestriction)(nil),      // 32: sdk.v1alpha.CapabilityRestriction
	(*CapabilityRestrictions)(nil),     // 33: sdk.v1alpha.CapabilityRestrictions
	(*SecretPrefixRestriction)(nil),    // 34: sdk.v1alpha.SecretPrefixRestriction
	(*SecretRestriction)(nil),          // 35: sdk.v1alpha.SecretRestriction
	(*SecretsRestritions)(nil),         // 36: sdk.v1alpha.SecretsRestritions
	(*Restrictions)(nil),               // 37: sdk.v1alpha.Restrictions
	nil,                                // 38: sdk.v1alpha.FieldsMap.FieldsEntry
	nil,                                // 39: sdk.v1alpha.AwaitCapabilitiesResponse.ResponsesEntry
	nil,                                // 40: sdk.v1alpha.AwaitSecretsResponse.ResponsesEntry
	(*pb.Value)(nil),                   // 41: values.v1.Value
	(*anypb.Any)(nil),                  // 42: google.protobuf.Any
	(*emptypb.Empty)(nil),              // 43: google.protobuf.Empty
}
var file_sdk_v1alpha_sdk_proto_depIdxs = []int32{
	41, // 0: sdk.v1alpha.SimpleConsensusInputs.value:type_name -> values.v1.Value
	6,  // 1: sdk.v1alpha.SimpleConsensusInputs.descriptors:type_name -> sdk.v1alpha.ConsensusDescriptor
	41, // 2: sdk.v1alpha.SimpleConsensusInputs.default:type_name -> values.v1.Value
	38, // 3: sdk.v1alpha.FieldsMap.fields:type_name -> sdk.v1alpha.FieldsMap.FieldsEntry
	0,  // 4: sdk.v1alpha.ConsensusDescriptor.aggregation:type_name -> sdk.v1alpha.AggregationType
	5,  // 5: sdk.v1alpha.ConsensusDescriptor.fields_map:type_name -> sdk.v1alpha.FieldsMap
	9,  // 6: sdk.v1alpha.ReportResponse.sigs:type_name -> sdk.v1alpha.AttributedSignature
	42, // 7: sdk.v1alpha.CapabilityRequest.payload:type_name -> google.protobuf.Any
	42, // 8: sdk.v1alpha.CapabilityResponse.payload:type_name -> google.protobuf.Any
	42, // 9: sdk.v1alpha.TriggerSubscription.payload:type_name -> google.protobuf.Any
	18, // 10: sdk.v1alpha.TriggerSubscription.requirements:type_name -> sdk.v1alpha.Requirements
	2,  // 11: sdk.v1alpha.TeeTypeAndRegions.type:type_name -> sdk.v1alpha.TeeType
	13, // 12: sdk.v1alpha.TeeTypeSelection.types:type_name -> sdk.v1alpha.TeeTypeAndRegions
	43, // 13: sdk.v1alpha.Tee.any:type_name -> google.protobuf.Empty
	14, // 14: sdk.v1alpha.Tee.type_selection:type_name -> sdk.v1alpha.TeeTypeSelection
	12, // 15: sdk.v1alpha.TriggerSubscriptionRequest.subscriptions:type_name -> sdk.v1alpha.TriggerSubscription
	42, // 16: sdk.v1alpha.Trigger.payload:type_name -> google.protobuf.Any
	15, // 17: sdk.v1alpha.Requirements.tee:type_name -> sdk.v1alpha.Tee
	39, // 18: sdk.v1alpha.AwaitCapabilitiesResponse.responses:type_name -> sdk.v1alpha.AwaitCapabilitiesResponse.ResponsesEntry
	43, // 19: sdk.v1alpha.ExecuteRequest.subscribe:type_name -> google.protobuf.Empty
	17, // 20: sdk.v1alpha.ExecuteRequest.trigger:type_name -> sdk.v1alpha.Trigger
	17, // 21: sdk.v1alpha.ExecuteRequest.pre_hook:type_name -> sdk.v1alpha.Trigger
	41, // 22: sdk.v1alpha.ExecutionResult.value:type_name -> values.v1.Value
	16, // 23: sdk.v1alpha.ExecutionResult.trigger_subscriptions:type_name -> sdk.v1alpha.TriggerSubscriptionRequest
	37, // 24: sdk.v1alpha.ExecutionResult.restrictions:type_name -> sdk.v1alpha.Restrictions
	26, // 25: sdk.v1alpha.GetSecretsRequest.requests:type_name -> sdk.v1alpha.SecretRequest
	40, // 26: sdk.v1alpha.AwaitSecretsResponse.responses:type_name -> sdk.v1alpha.AwaitSecretsResponse.ResponsesEntry
	27, // 27: sdk.v1alpha.SecretResponse.secret:type_name -> sdk.v1alpha.Secret
	28, // 28: sdk.v1alpha.SecretResponse.error:type_name -> sdk.v1alpha.SecretError
	29, // 29: sdk.v1alpha.SecretResponses.responses:type_name -> sdk.v1alpha.SecretResponse
	31, // 30: sdk.v1alpha.CapabilityRestriction.method:type_name -> sdk.v1alpha.MethodRestriction
	32, // 31: sdk.v1alpha.CapabilityRestrictions.restrictions:type_name -> sdk.v1alpha.CapabilityRestriction
	3,  // 32: sdk.v1alpha.CapabilityRestrictions.type:type_name -> sdk.v1alpha.CapabilityRestrictionType
	27, // 33: sdk.v1alpha.SecretRestriction.exact_secret:type_name -> sdk.v1alpha.Secret
	34, // 34: sdk.v1alpha.SecretRestriction.prefixed_secret:type_name -> sdk.v1alpha.SecretPrefixRestriction
	35, // 35: sdk.v1alpha.SecretsRestritions.restrictions:type_name -> sdk.v1alpha.SecretRestriction
	36, // 36: sdk.v1alpha.Restrictions.secrets:type_name -> sdk.v1alpha.SecretsRestritions
	33, // 37: sdk.v1alpha.Restrictions.capabilities:type_name -> sdk.v1alpha.CapabilityRestrictions
	6,  // 38: sdk.v1alpha.FieldsMap.FieldsEntry.value:type_name -> sdk.v1alpha.ConsensusDescriptor
	11, // 39: sdk.v1alpha.AwaitCapabilitiesResponse.ResponsesEntry.value:type_name -> sdk.v1alpha.CapabilityResponse
	30, // 40: sdk.v1alpha.AwaitSecretsResponse.ResponsesEntry.value:type_name -> sdk.v1alpha.SecretResponses
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_sdk_v1alpha_sdk_proto_init() }
func file_sdk_v1alpha_sdk_proto_init() {
	if File_sdk_v1alpha_sdk_proto != nil {
		return
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[0].OneofWrappers = []any{
		(*SimpleConsensusInputs_Value)(nil),
		(*SimpleConsensusInputs_Error)(nil),
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[2].OneofWrappers = []any{
		(*ConsensusDescriptor_Aggregation)(nil),
		(*ConsensusDescriptor_FieldsMap)(nil),
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[7].OneofWrappers = []any{
		(*CapabilityResponse_Payload)(nil),
		(*CapabilityResponse_Error)(nil),
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[11].OneofWrappers = []any{
		(*Tee_Any)(nil),
		(*Tee_TypeSelection)(nil),
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[17].OneofWrappers = []any{
		(*ExecuteRequest_Subscribe)(nil),
		(*ExecuteRequest_Trigger)(nil),
		(*ExecuteRequest_PreHook)(nil),
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[18].OneofWrappers = []any{
		(*ExecutionResult_Value)(nil),
		(*ExecutionResult_Error)(nil),
		(*ExecutionResult_TriggerSubscriptions)(nil),
		(*ExecutionResult_Restrictions)(nil),
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[25].OneofWrappers = []any{
		(*SecretResponse_Secret)(nil),
		(*SecretResponse_Error)(nil),
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[28].OneofWrappers = []any{
		(*CapabilityRestriction_Method)(nil),
	}
	file_sdk_v1alpha_sdk_proto_msgTypes[31].OneofWrappers = []any{
		(*SecretRestriction_ExactSecret)(nil),
		(*SecretRestriction_PrefixedSecret)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_v1alpha_sdk_proto_rawDesc), len(file_sdk_v1alpha_sdk_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_v1alpha_sdk_proto_goTypes,
		DependencyIndexes: file_sdk_v1alpha_sdk_proto_depIdxs,
		EnumInfos:         file_sdk_v1alpha_sdk_proto_enumTypes,
		MessageInfos:      file_sdk_v1alpha_sdk_proto_msgTypes,
	}.Build()
	File_sdk_v1alpha_sdk_proto = out.File
	file_sdk_v1alpha_sdk_proto_goTypes = nil
	file_sdk_v1alpha_sdk_proto_depIdxs = nil
}
