name: Lint and breaking check for cre

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  buf-cre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4.1.7

      - name: Install buf CLI (v1.45.0, SHA bee67191e0a207d52b6c7f0ac9d3d1210898d2f9)
        run: |
          if ! command -v buf >/dev/null; then
            echo "Installing buf CLI v1.45.0..."
            curl -sSL https://github.com/bufbuild/buf/releases/download/v1.45.0/buf-$(uname -s)-$(uname -m) -o /usr/local/bin/buf
            chmod +x /usr/local/bin/buf
          else
            echo "buf CLI already available."
          fi

      - name: Check if cre/ files were modified
        id: changes
        run: |
          if git diff --name-only origin/main...HEAD | grep '^cre/'; then
            echo "cre_changed=true" >> $GITHUB_OUTPUT
          else
            echo "cre_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set tool versions
        if: steps.changes.outputs.cre_changed == 'true'
        id: tool-versions
        uses: smartcontractkit/tool-versions-to-env-action@v1.0.8

      - name: Run buf lint for cre
        if: steps.changes.outputs.cre_changed == 'true'
        run: buf lint cre

      - name: Run buf breaking for cre
        if: steps.changes.outputs.cre_changed == 'true'
        run: buf breaking cre --against ".git#branch=main,subdir=cre" --exclude-path node_modules

      - name: Skip buf checks — no cre/ changes
        if: steps.changes.outputs.cre_changed == 'false'
        run: echo "No changes to cre/ — skipping buf lint and breaking checks."

