name: push-main

on:
  push:
    branches:
      - main

jobs:
  cd-release:
    name: Changesets
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checking Changesets
        uses: smartcontractkit/.github/actions/cicd-changesets@7a4d99cb349ea8f25195d2390d157942031f8a57
        with:
          # aws inputs
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_IAM_ROLE_ARN_GATI }}
          aws-lambda-url: ${{ secrets.AWS_LAMBDA_URL_GATI }}
