name: register-workflows-schemas

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/register-workflows-schemas.yaml"
      - "workflows/**/*.proto"
  pull_request:
    paths:
      - ".github/workflows/register-workflows-schemas.yaml"
      - "workflows/**/*.proto"

jobs:
  register-schemas:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: cre,        file: chip-cre.json }
#          - { name: platform,   file: chip-platform.json }

    steps:
      - uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ARN_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Register Workflows Schemas for ${{ matrix.config.name }} domain
        uses: smartcontractkit/.github/actions/chip-schema-registration@6fcf464d30c3678d46f775dc97e71704ead79184  # v1.0.2
        with:
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: us-west-2
          chip-schema-dir: "workflows"
          chip-config-file-path: "workflows/${{ matrix.config.file }}"
          chip-config-host: ${{ github.ref_name == 'master' && secrets.chip_config_host_prod || secrets.chip_config_host_staging }}
          chip-config-user: ${{ secrets.chip_config_gha_user }}
          chip-config-password: ${{ github.ref_name == 'master' && secrets.chip_config_gha_password_prod || secrets.chip_config_gha_password_staging }}
          ts-ouath-client-id: ${{ secrets.chip_config_ts_oauth_client_id }}
          ts-ouath-secret: ${{ secrets.chip_config_ts_oauth_secret }}
